### ISSUE TITLE
Disable when fullscreen: gamma control turning off on non-fullscreen windows

### ISSUE THREAD

**Issue by Puncia** [Tyrrrz/LightBulb#10]
Clicking on the desktop makes LightBulb reset the current temperature to daytime (6600K) as if an application switched to fullscreen.
Clicking back and giving focus to any other program makes the temperature go back to normal.
This happens with proper fading.

I can replicate this by also switching between two windows: let's say I have Discord and Chrome, with Chrome being in the foreground and Discord being the 2nd application in the "Windows focus order". Clicking the Chrome icon in the taskbar or using the [top-left button](http://i.imgur.com/cGm4Em4.png) will minimize its window and will switch the focus back to Discord. This will make the temperature go back to 6600K and, once the fading animation has terminated, it will switch back to whatever the temperature was _without_ fading.
This does not happen if I click on Discord manually or using Alt+Tab.

I can replicate the 2nd case with basically any window - tried to use two basic explorer windows as well.
Killing the explorer.exe process does not change anything (worth a try).

I also tried to close as many background apps as possible without success. I do not use Rainmeter nor any related or similar programs.

I'm on Windows 10 (1607 version).

**Comment by Tyrrrz** [comment]
This is with "Disable when fullscreen" option turned on, right?

**Comment by Puncia** [comment]
Yes, forgot to mention it.
Worth mentioning that I can also replicate if the "Automatically hide the taskbar" option is enabled. Only the fullscreen option in your app seems to affect it.

**Comment by Tyrrrz** [comment]
[Try this test version](http://tyrrrz.me/dl/LightBulb_Install_1.6.1.zip)

It should work now. Windows API is super clunky, especially when it comes to... well... windows. Looks like the desktop that runs normally and the desktop that has a wallpaper slideshow are actually two different windows! And what's more, when you switch to a different window, the desktop becomes foreground for a moment, probably to re-arrange windows(?).

Anyway, tell me if this works and I'll make a release.

**Comment by Puncia** [comment]
Yay! Doesn't happen anymore, thank god. My eyes thank you.
