### ISSUE TITLE
The new Win10 update to 1903 broke this app

### ISSUE THREAD

**Issue by Win10pissesmeoff** [Tyrrrz/LightBulb#100]
Never had any issues before but after this Windows 10 update to 1903 this app doesn't work at all anymore. Not sure if there is an setting to fix this but figured you'd want to know about it. 

Edit- After doing a bit more searching I found a fix on this page https://answers.microsoft.com/en-us/windows/forum/all/windows-10-1903-may-update-breaks-night-light/75f21187-07ff-4c3d-b552-f390f205db67?auth=1 

I had slightly different files other than what was listed but I found 2 by ctrl+F "windows.data.bluelightreduction" and deleted that one and "windows.data.bluelightreduction.settings"

I restarted and it seems to be working again. Will update if the problem persists.

**Comment by dolevu** [comment]
It worked for me after deleting the registry keys also

**Comment by dolevu** [comment]
In my case, the first restart, it works. Then it breaks after second restart, I have to delete the registry keys again

**Comment by dolevu** [comment]
After installing Cumulative Update for Windows 10 Version 1903 for x64-based Systems (KB4503293)
The problem fixed.

**Comment by scarystuff** [comment]
I have the Cumulative Update for Windows 10 Version 1903 for x64-based Systems (KB4503293) and it's not fixed for me :-/

**Comment by dolevu** [comment]
@scarystuff my LightBulb and Windows Night Mode stopped working today. So the issue is windows update itself, the problem still persists

**Comment by TacosAreYum** [comment]
Broken on 1903 for me too.

**Comment by Win10pissesmeoff** [comment]
Not sure if anyone else is still having issues, but I had it not work once after a reset. I just deleted the 2 registry files again and it seems to be working as intended now after resetting multiple times. This is on the  Cumulative Update for Windows 10 Version 1903 for x64-based Systems (KB4503293).

**Comment by dolevu** [comment]
@Win10pissesmeoff I deleted the registry keys, but after restarting, the problem comes back.
Right now I only sleep the computer, not shutting down so I won't have to delete the registry keys again and again.

**Comment by Win10pissesmeoff** [comment]
The problem comes back for me if I shut down my PC but I usually just keep it on sleep so that's why it wasn't resetting for me. Not sure how to fix other than deleting the registry files after every shut down.

**Comment by dolevu** [comment]
Finally it's fixed
https://support.microsoft.com/en-us/help/4501375/windows-10-update-kb4501375

**Comment by broizter** [comment]
Still not fixed after installing kb4501375 for me.

**Comment by dolevu** [comment]
I can confirm it's still working for me after many times restarting.
Maybe you should try to delete the registry keys mentioned above @broizter?

**Comment by SethBergen** [comment]
Not working for me either on the latest cumulative update (KB4507453).
Any deleted keys reappear on restart.

**Comment by broizter** [comment]
My problem seems to be related to multi monitors. As soon as I disable my second monitor it starts working again.

**Comment by Jefferderp** [comment]
> Enabling or disabling multi-monitor in Windows fixes the problem temporarily until next scheduled color shift.

I just tested, and this is true for me as well. Updating to the latest (KB4507453) made no difference, but Lightbulb immediately began working once I disconnected all but my primary monitor.

**Comment by starsoccer** [comment]
+1 same issue, disabling multi-monitor fixes it.

**Comment by Tyrrrz** [comment]
Looks like Windows broke something with this update. The fact that it affects only multi-monitor setup leads me to think they changed something related to how the [`GetDC`](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getdc) native function works with `null` pointer (which used to mean "all monitors").

I'll try to figure out if there's a workaround as soon as I have some time.

**Comment by MariusSpangenberger** [comment]
Any news on this front?

**Comment by Tyrrrz** [comment]
Working on it #105

**Comment by Dainius14** [comment]
As of af48000a1fd29644f1a456fbd453c039ad1ecead seems to be working fine in Windows 10 build 18362.418

**Comment by Dainius14** [comment]
Unfortunately, does not work on multi-monitor setup. At least works when only single monitor is used. Previous version did not work for single or multi monitor setup.

**Comment by Tyrrrz** [comment]
@Dainius14 just to clarify, "does not work on multi-monitor setup" means that neither of the two monitors' gamma change? or does it mean only primary monitor is affected but the other monitors stay the same?

**Comment by starsoccer** [comment]
I think it means both, I briefly tested it a few days ago and couldnt notice any change

**Comment by Dainius14** [comment]
None of the monitors work

**Comment by Tyrrrz** [comment]
Closed accidentally sorry.
Please check out [latest build](https://github.com/Tyrrrz/LightBulb/commit/61927b3a95f6f8a5dec26dd4d0b5d88975117174/checks?check_suite_id=305454084). I've changed how the device context of the virtual screen is resolved, it might have fixed this issue.

**Comment by starsoccer** [comment]
@Tyrrrz For me this build doesnt even start. I click it and see nothing. I dont see it in the task bar, cant find it in task manager etc..

**Comment by Tyrrrz** [comment]
Hm. Did you download the installer or the portable version?

**Comment by Dainius14** [comment]
Tried it now. 

Does not work :( Nothing happens on multi-monitor setup

**Comment by starsoccer** [comment]
I used the portable version(not installer)

**Comment by Tyrrrz** [comment]
@Dainius14 try this one https://github.com/Tyrrrz/LightBulb/commit/9018e191f2c36c501566ad111c8ca64c3cc9d2e7/checks?check_suite_id=305727114
I've switched to a different approach for grabbing DC, hope it helps. Unfortunately I don't have a second monitor nor Win10 1903 to test.

**Comment by Dainius14** [comment]
Great work! It's working!

**Comment by Tyrrrz** [comment]
Sweet :)

**Comment by starsoccer** [comment]
@Dainius14 Did you use the portable or installer? Portable for me is still not starting.

**Comment by Tyrrrz** [comment]
Fix is in master, build is [here](https://github.com/Tyrrrz/LightBulb/commit/b8df79a614ab85bd6787dbe7632110c906b83626/checks?check_suite_id=305800526), please test this on both single monitor and multi-monitor setups. And if you have access to Win7, Win8, Win8.1, it would be nice to test on them too.

CC @mirh @NomDeMorte @aure2006 if you guys can help test the latest build.

@starsoccer 
Did you unpack all of the files to a separate directory? Does it say anything at all or just quietly does nothing? Do you remember which was the last build that worked?

**Comment by Tyrrrz** [comment]
Also, @starsoccer you might need to install .NET Core 3.0 runtime (installer sets it up automatically).
https://dotnet.microsoft.com/download/thank-you/dotnet-runtime-3.0.0-windows-x64-installer
https://dotnet.microsoft.com/download/thank-you/dotnet-runtime-3.0.0-windows-x64-installer

**Comment by starsoccer** [comment]
Giving it a try now, but I dont think thats the issue. Mainly because my other portable install, 1.6.4.1 starts fine. So unless this is a new requirement I dont think its related.

**Comment by Tyrrrz** [comment]
Yes, it's new in 2.0

**Comment by starsoccer** [comment]
Nice that worked, would be useful to have that as an error popup. Like if its not found to show an error saying both are needed

**Comment by Tyrrrz** [comment]
I will include a notice on release page when 2.0 is released

**Comment by NomDeMorte** [comment]
Seems to be working here, on both monitors - although I'm still on 1809 so I'm not sure if this is of any relevance.... at least, the change didn't break old versions ;)

**Comment by spacecheese** [comment]
I couldn't get this to work on 1903. I just updated to 1909 and it still doesn't seem to be working on either monitor. Windows night light doesn't seem to do anything either.

**Comment by Tyrrrz** [comment]
@spacecheese what interface are your monitors connected with? Does f.lux not work either?

**Comment by spacecheese** [comment]
@Tyrrrz my monitors are connected to a gtx 970, f.lux seems to work fine though I'll try an update my graphics drivers and see if that makes any difference.

**Comment by ChrisLMerrill** [comment]
I've also updated to 1909 today and there is no change in LightBulb functionality (or f.lux).

**Comment by spacecheese** [comment]
New drivers didn't seem to make any difference.

**Comment by Tyrrrz** [comment]
@spacecheese I mean, are you using DisplayLink dock connect by any chance?

**Comment by spacecheese** [comment]
@Tyrrrz not using anything like that. My monitors are directly connected to the graphics card outputs.

**Comment by spacecheese** [comment]
Appologies. I've resolved my issue- it seems that the display drivers that TeamViewer installs don't support gamma ramps so that SetDeviceGammaRamp was failing.

**Comment by Tyrrrz** [comment]
@spacecheese 
Hmm, that's weird, although nice that it was resolved. How does it work, TeamViewer just installs display drivers that replace your GPU's drivers? Or were you connected to another computer through TeamViewer and had LightBulb installed there?

**Comment by spacecheese** [comment]
Teamviewer has an optional monitor driver that replaces the Windows "Generic PnP" one so that you can draw pictures over the screen. Pretty annoying to track down.

**Comment by Tyrrrz** [comment]
Good to know. We should probably have a list of known issues like this.

**Comment by ChrisLMerrill** [comment]
FWIW, I do occasionally use a MS Teams conferencing project, can't recall if it is called TeamViewer, but that sounds familiar. I don't install the full version - just the one-time download when joining a meeting. I can't tell if it has mucked with my driver or not. Or if f.lux would be similarly affected by that?

On a separate note, I've also confirmed that I do not have a DisplayLink driver installed (as described in the link from the Troubleshooting page). That's what I would expect since I'm using DVI via my dock, but thought I'd double-check.

**Comment by Tyrrrz** [comment]
@ChrisLMerrill I think your situation is a bit different. Also, I have MS Teams installed on my other PC and it works fine with LightBulb, so I don't think it's related to that.

You could however open device manager (Windows key + type "device manager" + press enter) and check what it says under "Display adapters".

**Comment by ChrisLMerrill** [comment]
Under display adapters, it lists AMD Radeon M370 and Intel HD Graphics 530, which is correct for my Dell E5570. 

Under Monitors, it shows Dell U2410 (twice for my dual monitors) and Generic PnP Monitor, which I assume is my built-in display (inactive at the moment).

**Comment by Tyrrrz** [comment]
@ChrisLMerrill let's continue discussion in #102, I left a comment.
