### ISSUE TITLE
LightBulb Flickering at Windows 10 Startup

### ISSUE THREAD

**Issue by yasomal** [Tyrrrz/LightBulb#101]
My screen color temperature filker at Windows 10 startup. I've already disabled Windows Night Light option at Settings > System > Display.
Windows version: 1809 (OS build 17763.557)
LightBulb release: v1.6.4.1

**Comment by Tyrrrz** [comment]
Hi, what exactly do you mean "flicker"?

**Comment by yasomal** [comment]
Flickering: (of a flame or light) burning or shining unsteadily; wavering.
Color temperature changes rapidly white to yellowish, yellow to white etc. at the startup. After about half a minute of this annoying flickering thing, color temperature stops at a certain point and works as normal. Have to face this flickering issue at each and every startup.

**Comment by Tyrrrz** [comment]
Did it start happening recently or has it always been like this for you?

**Comment by yasomal** [comment]
I think I found the solution.
My laptop is an Asus laptop. And it has ASUS Splendid Video Enhancement Technology which is a program developed by ASUS. It allow users to change color temperature of screen. I uninstalled it and restart several times at day time. It is not flickered. But I wish to check it at night. So please wait..

**Comment by yasomal** [comment]
No, it didn't fix anything.
And I discovered another strange behavior. I opened up two explorer windows, and snapped them side by side. Then scroll one windows content by two fingers gestures on mouse pad. When I scrolled up screen color tempreature changes to yellowish. When I scrolled down it changes back to normal.

**Comment by yasomal** [comment]
I don't know the exact reason. But the issue has disappeared now, Might be a Windows update fixed this.

**Comment by hotellinawebmaster** [comment]
I could experience random flickering during use. 
A very short flash of pure 100% full blast brightness during work on a Windows 10 laptop, not at boot but in the middle of writing emails ( using LightBulb 2.3.0. )

Your app is awesome though, keep up the hard work!

Aldo

**Comment by Tyrrrz** [comment]
> A very short flash of pure 100% full blast brightness during work on a Windows 10 laptop, not at boot but in the middle of writing emails ( using LightBulb 2.3.0. )

That sounds like something resets the gamma (and then LightBulb probably sets it back). I noticed on latest builds Windows 10 is doing this quite a lot.

**Comment by Tyrrrz** [comment]
> @Tyrrrz, I'd like to help out to figure out what is causing it, maybe it's indeed some other process fiddling gamma settings. Is there some Windows systems protocol tracing log which allows to see which processes may interfere with gamma settings?

Unfortunately there is not, to my knowledge, which is what makes this so difficult :/
