### ISSUE TITLE
Color reverts when display wakes

### ISSUE THREAD

**Issue by ChrisLMerrill** [Tyrrrz/LightBulb#102]
After I wake my monitors, the color is reset to daylight. For example, when I walk away and Windows puts the displays to sleep. If I use the Preview (play button) in LightBulb, then it returns to normal operation.

Windows 10 on a Dell laptop, docked in the Dell E-Port Replicator with 2 Dell monitors driven by DVI connection. Laptop monitor not in use.

Maybe related to #53 and #86. Let me know if I can assist with troubleshooting.

Thanks for the app, BTW!  I switched from f.lux for better control over the schedule and more linear color change. Other than this bug, it is perfect for me :)

**Comment by Tyrrrz** [comment]
Hi @ChrisLMerrill 

Can you try [latest master build](https://github.com/Tyrrrz/LightBulb/suites/302403101/artifacts/277186) and see if it's fixed there?

**Comment by Dainius14** [comment]
Turning off the display programatically, physically, sleeping PC, connecting, disconnecting the display does not reset the color and everything works correctly.

**Comment by ChrisLMerrill** [comment]
> Hi @ChrisLMerrill
> 
> Can you try [latest master build](https://github.com/Tyrrrz/LightBulb/suites/302403101/artifacts/277186) and see if it's fixed there?

Hmmm...this version doesn't work at all for me :(  Windows 10 Pro with latest updates. I uninstalled and re-installed. Twice, to be sure. Also rebooted. Twice. Running it results in no GUI and no icon in the system tray. Running in command prompt provides no output. Are there any diagnostic logs I can send you? Or do you have any debugging tips? Other info I can provide?

I do have f.lux installed (since this problem started), but exited it before trying to run LightBulb.

TIA!
Chris

**Comment by Tyrrrz** [comment]
Sorry, forgot to mention.
If you're trying to use the non-installer version, you will have to install .NET Core 3.0 runtime first.
https://dotnet.microsoft.com/download/thank-you/dotnet-runtime-3.0.0-windows-x64-installer
https://dotnet.microsoft.com/download/thank-you/dotnet-runtime-3.0.0-windows-x64-desktop-runtime-installer

The installer will install them automatically.

**Comment by ChrisLMerrill** [comment]
I ran the installer contained in the zip file that you linked above (latest master build). I recall that it said something about installing .NET something 3.0.

**Comment by Tyrrrz** [comment]
Ok that's weird. Does the app not start up at all without any error?
I will try to investigate this tomorrow.

**Comment by ChrisLMerrill** [comment]
That is correct. No error, no GUI, no change in monitor color ... just nothing. I also tried undocking my laptop so that I was using only the single, built-in monitor. No change in behavior. Not sure if it helps, but: f.lux works fine in this regard on this computer in every configuration I've tried.

**Comment by Tyrrrz** [comment]
That's weird, couldn't reproduce it on a fresh Win10 machine.
Can you try going to `c:\Program Files\LightBulb\` (or wherever LightBulb is installed), opening command line and typing `dotnet LightBulb.dll`. Does the command line freeze after that or is there an error maybe?

**Comment by ChrisLMerrill** [comment]
Tried it, but I only see:

'dotnet' is not recognized as an internal or external command,
operable program or batch file.

**Comment by Tyrrrz** [comment]
Interesting. It sounds like .NET Runtime didn't actually get installed, perhaps there was some issue with the installer.
Can you try manually downloading and installing it from [here](https://dotnet.microsoft.com/download/dotnet-core/3.0/runtime)? You need both.

**Comment by ChrisLMerrill** [comment]
So yeah, it looks like the LightBulb installer didn't actually install .NET, even though it appeared that it did. After installing them manually, Lightbulb now runs. 

However, using the Preview feature does not result in _any_ change in monitor color when I have two external monitors configured. Works fine with the single built-in monitor (laptop). Also does not work using the laptop display + 2 external monitors.

I have not yet rebooted since installing .NET. I'll try that and report back if there is any change.

**Comment by Tyrrrz** [comment]
Are the external monitors connected by DisplayLink by any chance?

**Comment by ChrisLMerrill** [comment]
No, I am using a Dell dock and the monitors are connected via DVI.  I also have a portable USB-C monitor, so I tried hooking that up as well. No luck. Doesn't work on either the portable or the laptop monitor when that external is hooked up. Works fine when only the laptop monitor is in use.

Also, rebooting had no effect.

Not sure if this helps: It is a Dell Latitude 5570 with integrated Intel graphics as well as a Radeon processor. The Intel control panel has separate color profiles for each monitor configuration and it automatically switches profiles when I connect/disconnect or dock/undock. But I guess that shouldn't matter, though, since f.lux works.

**Comment by Dainius14** [comment]
Did you really build from the latest commit and run that, not the old version? From: ChrisLMerrillSent: 2019 m. lapkričio 12 d., antradienis 22:59To: Tyrrrz/LightBulbCc: Dainius; CommentSubject: Re: [Tyrrrz/LightBulb] Color reverts when display wakes (#102) No, I am using a Dell dock and the monitors are connected via DVI. I also have a portable USB-C monitor, so I tried hooking that up as well. No luck. Doesn't work on either the portable or the laptop monitor when that external is hooked up. Works fine when only the laptop monitor is in use.Also, rebooting had no effect.Not sure if this helps: It is a Dell Latitude 5570 with integrated Intel graphics as well as a Radeon processor. The Intel control panel has separate color profiles for each monitor configuration and it automatically switches profiles when I connect/disconnect or dock/undock. But I guess that shouldn't matter, though, since f.lux works.—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Tyrrrz** [comment]
@ChrisLMerrill can you please test [this](https://github.com/Tyrrrz/LightBulb/suites/302403101/artifacts/277186) build instead? This is before the fix for Win10 issues was added, maybe it broke something for you. Also, did LightBulb 1.6.* work fine with your multimonitor setup?

Sorry for asking you to test all bunch of stuff but unfortunately I can't reproduce it on my PC.

**Comment by Tyrrrz** [comment]
@ChrisLMerrill one more question, with f.lux when you take a screenshot of something when it's active, do you see the orange tint on the image or does it appear normal?

**Comment by ChrisLMerrill** [comment]
No change when running that version - still works with laptop display, doesn't work with external monitors.

Yes, 1.6 worked as expected with my dual external monitor setup. I'd been using it for a while and had ditched f.lux. Until the 1903 updates.

No problem, I understand. I'm happy to help out in any way I can.

**Comment by ChrisLMerrill** [comment]
The screenshot appears normal when taken with f.lux running (preview), pasted into paint.net and then reverting back to normal (daytime) display.

**Comment by Tyrrrz** [comment]
Very interesting, I will have to look at it again tomorrow, so far all my guesses were incorrect.

**Comment by Tyrrrz** [comment]
@ChrisLMerrill 
I had another idea after reading this:

>The Intel control panel has separate color profiles for each monitor configuration and it automatically switches profiles when I connect/disconnect or dock/undock.

Any way to turn this off temporarily to test out? I think this might be overwriting gamma changes.

**Comment by ChrisLMerrill** [comment]
Hmmm...I don't know. Let me look into it.

**Comment by ChrisLMerrill** [comment]
I haven't found a way to disable that, but I did find something that I think conflicts with my previous statement. Despite not finding anything about DisplayPort in my drivers, the Intel control panel seems to say otherwise (see Connector Type). These monitors are not hooked up with DispalyPort cables, but maybe the dock only exposes DisplayPort connections to the computer and then exposes physical DisplayPort and DVI ports from each of those. Does this change things?

![image](https://user-images.githubusercontent.com/14020230/68895456-4b67bd00-06f7-11ea-83b5-bed861f2b38f.png)

**Comment by Tyrrrz** [comment]
Those are DisplayPorts, not DisplayLink. As far as I know there's a problem only with DisplayLink.

**Comment by ChrisLMerrill** [comment]
Ah...yeah. False lead :(

**Comment by spacecheese** [comment]
I think it might be easier to diagnose issues like this if SetGamma checked the return value of SetDeviceGammaRamp and then used another native method like GetColorSpace to distinguish issues with the device context and issues with the driver for an error message. I started a pr but I don't have much experience with MVVM so I wasn't sure how to implement this.

**Comment by Tyrrrz** [comment]
I remember having bad experience with diagnosing WinAPI errors in that they were borderlines useless in helping figuring out the problem. But if we just want to check, we can make a simple WinForms/Console diagnostic tool that tries to change gamma and reads the error like you said.

**Comment by Tyrrrz** [comment]
@ChrisLMerrill I added some diagnostics code and removed throttling.
Please try installing [this build](https://github.com/Tyrrrz/LightBulb/suites/314252202/artifacts/340806). Keep it running for around a minute and then exit it. It will have written some diagnostics information to `%appdata%/LightBulb/Test.log`. Please upload this file here.
Hopefully the information inside can help figuring out what's wrong.

**Comment by ChrisLMerrill** [comment]
Works!!!

I tested these situations
- preview in the LightBulb UI
- sleeping and waking the computer
- docking/undocking - i.e. detaching and re-attaching my two external DVI monitors
- adding/removing USB monitor

Seems to work perfect :)

**Comment by ChrisLMerrill** [comment]
Also tested waking the monitors after Windows power saving turns off the display - also works :)

**Comment by ChrisLMerrill** [comment]
Do you still want me to upload the diagnostic file?

**Comment by Tyrrrz** [comment]
Great! Out of curiosity, I'd still like to see the diagnostic file.

**Comment by ChrisLMerrill** [comment]
Here it is.
[Test.log](https://github.com/Tyrrrz/LightBulb/files/3860979/Test.log)

**Comment by Tyrrrz** [comment]
Seems that according to the log, everything works and WinAPI doesn't return any errors.

**Comment by Tyrrrz** [comment]
@ChrisLMerrill please double-check that the fix works on latest master, there were some changes.

**Comment by ChrisLMerrill** [comment]
Works.

I pulled a new installer from Actions > top row (on: push 07fc1e8) > Artifacts pull-down > LightBulb installer and, after removing the previous installation, I installed that one. Tested using the preview feature.  I hope that was the right one to test :)

**Comment by Tyrrrz** [comment]
@ChrisLMerrill awesome, thanks!

**Comment by ChrisLMerrill** [comment]
You're welcome...glad I could help. Thanks for building this app!   :)
