### ISSUE TITLE
Inform gamers of the advantages of this over competitors

### ISSUE THREAD

**Issue by NomDeMorte** [Tyrrrz/LightBulb#103]
I found this because I prefer open-source applications, and discovered [This reddit post](https://www.reddit.com/r/osugame/comments/5rpq1q/lightbulb_gamingfriendly_flux_alternative/) explaining why it's better for gaming. As a gamer, it was a simple choice for me.

But, a lot of gamers still use other apps which are not as good for them.

I think it would be good to put something in readme.md, which explains the performance advantages of LightBulb.

**Comment by Tyrrrz** [comment]
Thanks, that's a good idea.

**Comment by Tyrrrz** [comment]
If you have a good idea what to write, you are welcome to submit a PR for the readme :)

**Comment by NomDeMorte** [comment]
> If you have a good idea what to write, you are welcome to submit a PR for the readme :)

I've never done a PR before but since I appreciate your work so much I will learn how - forgive me if it takes some time. I'll probably just paraphrase your reddit post linked above, since it is very informative and I don't think I could put it any better than you did.

**Comment by Tyrrrz** [comment]
Haha, it's okay. If you don't want to make a PR, you can just post the content here and I'll add it.
I was thinking about putting a bit less text than in that reddit post because that's quite a lot. Maybe also in a specific section in the readme?

**Comment by Tyrrrz** [comment]
You can also add an article in the [wiki](https://github.com/Tyrrrz/LightBulb/wiki).

Note that information I wrote in that reddit post is a bit outdated in regards to F.lux as it was concerning version 3 and they are on version 4 now.
