### ISSUE TITLE
How can I change my location?

### ISSUE THREAD

**Issue by Grace6a** [Tyrrrz/LightBulb#104]
I don't see an option anywhere. It automatically set my location and I would like to change it.

**Comment by Tyrrrz** [comment]
For now please refer to this wiki article: https://github.com/Tyrrrz/LightBulb/wiki/Manual-geolocation
Upcoming new release of LightBulb will have this built-in in UI.

**Comment by Grace6a** [comment]
Thank you for that info. That's fine for me. I'll look forward to the new release also.  Cheers.
