### ISSUE TITLE
Force a background color

### ISSUE THREAD

**Issue by ultrakiller2** [Tyrrrz/LightBulb#109]
It would be even better if there were a disableable dark mode
You can test this issue with **[this](https://www.deviantart.com/eversins/art/GreyEveTheme-FINAL-Windows-10-High-Contrast-Theme-643504863)** theme, it doesn't require any patches
Screenshot with dark theme in Windows:![image_123](https://user-images.githubusercontent.com/25438100/68084071-a90f2600-fe28-11e9-9e67-e6207d45e080.png)

**Comment by Tyrrrz** [comment]
Should be fixed, try now.
