### ISSUE TITLE
Philips Hue lights support

### ISSUE THREAD

**Issue by ukgamer** [Tyrrrz/LightBulb#11]
Just started using this program, it seems like a great alternative to f.lux. I have a feature request:

I have Philips Hue smart lights in my room which I used to have synced to f.lux's colour temperature, up until a change to the Hue API broke its ability to authenticate with the bridge which I only noticed after a clean Windows install (they said that there would be an update to fix this but there still hasn't been).

I realise that probably not many people have Hue lights, but this is the only feature that I'm missing that f.lux had and it would be great to have it built into Lightbulb.

**Comment by vatterspun** [comment]
Even if it's not possible to build something that works with Philips, there are a remarkable number of home automation tools and programs coming out with some very cool APIs.  Although I haven't looked into lighting, I expect a hardware+toolset combo will become available in the next year or two, if it hasn't already.

Anyway, great idea.

**Comment by Tyrrrz** [comment]
I don't own Phillips Hue, so someone else will have to work on this :)

**Comment by Tyrrrz** [comment]
Going to close this as `won't fix` because it got pretty stale and I still don't own a Philips Hue. If someone is willing to implement this, please re-open this issue.
