### ISSUE TITLE
Separate transition time for temperature and brightness

### ISSUE THREAD

**Issue by NomDeMorte** [Tyrrrz/LightBulb#110]
I'm really enjoying the new ability to type in a transition time longer than the slider allows, thanks for that!

One issue I have, is that while my red shift is just how I like it, I wish the brightness didn't reach the minimum at the same time as the redshift reached its maximum. Things are nice and red, but too dark....

Just a little thing on my wish list, if it's not too difficult :)

**Comment by Tyrrrz** [comment]
Thank you for the idea.

To be completely honest, I think this will add a bit too much complexity for its worth. It's already quite difficult to manage state with so many different factors in play (temperature, brightness, enabled/disabled/paused, cycle preview, full transition/limited transition, smooth/not smooth, manual sunrise/auto sunrise, manual sunset/auto sunset) so I'm trying to keep them at minimum to make it easier to maintain and test the app.

**Comment by NomDeMorte** [comment]
Fair enough! Feel free to close this one off. It was just a thought, but it did occur to me that it might be unwieldly.

**Comment by Tyrrrz** [comment]
No worries, thank you for your suggestion anyway!
