### ISSUE TITLE
Error when switching manual vs location-based times in v2

### ISSUE THREAD

**Issue by NomDeMorte** [Tyrrrz/LightBulb#111]
Steps to reproduce:

Start Lightbulb
Open settings dialog and switch between manual or location based times
Save and close settings dialog
Switch again
Save and close dialog
Attempt to switch a third time (it's always the third time)
![image](https://user-images.githubusercontent.com/45681208/68203182-59438100-0019-11ea-8996-9bcb604a6b40.png)

Happy to provide more information if you need it.

**Comment by Tyrrrz** [comment]
Can't seem to reproduce. Are you using the the build from [the very last commit](https://ci.appveyor.com/project/Tyrrrz/LightBulb/build/artifacts)? I think I have encountered and fixed this issue already, although it may be different.

**Comment by NomDeMorte** [comment]
Indeed, the new version has fixed this already - and BTW, it also automatically downloaded the dotnet installer for me. 

Sorry, you're working fast! I'll be sure to try the newest build next time!

**Comment by Tyrrrz** [comment]
Awesome :)
