### ISSUE TITLE
Tray icon is yellow instead of orange

### ISSUE THREAD

**Issue by Tyrrrz** [Tyrrrz/LightBulb#117]
After switching to .NET Core 3.0, the tray icon is now seemingly rendered with lower color range.
Most likely an issue because TrayIcon package is still on .NET Fx. Tracked here: https://github.com/hardcodet/wpf-notifyicon/issues/4

**Comment by NomDeMorte** [comment]
I noticed this and thought that was intentional. I always did prefer the old icon colour ;)

**Comment by xcasxcursex** [comment]
This is fixed in 2.x

**Comment by Tyrrrz** [comment]
Closing as this is technically fixed by installing .NET Core Runtime v3.1 instead of v3.0.
