### ISSUE TITLE
Close to systray only works using the app UI

### ISSUE THREAD

**Issue by NomDeMorte** [Tyrrrz/LightBulb#118]
If I right click the taskbar tab for the application and click 'Close window' or if I alt+f4 (possibly also other ways to exit) the app actually exits rather than minimising to the tray. If I want to minimise to the tray, I need to click the X in the corner of the app.

Not a big deal, TBH I pretty much only touch the UI if I'm testing new version for you, so I never need to close or minimise it anyway ;) but I noticed this today and I'm unsure if it is intentional.

**Comment by Tyrrrz** [comment]
Hm, I never thought about it. Do tray apps usually hide when you do that?

**Comment by NomDeMorte** [comment]
Mostly they do. The one example I can think of is MSI afterburner which closes no matter what, and minimise button sends it to the tray. Thing always makes me paranoid: "Don't click the X don't click the X don't click the X" lol

I think the usual approach is to let minimise actually minimise but keep the window open, close minimises to the tray, and the only way to terminate it is to right-click the tray icon. All my other tray apps right now are working that way.

**Comment by mirh** [comment]
Behavior depends on the kind of application. 
Is it a "live program" like, I don't know, a game or music player? Then if you don't want it in your taskbar, I cannot think to a reason other than having it killed. 
Windows UX [guidelines](https://ux.stackexchange.com/questions/75575/should-the-cross-or-x-button-do-something-other-than-close-e-g-minimize-o) also kind of entails this by telling you application≠window. 

Or is it something supposed to stay in background, where the window is just the tip of the iceberg?
