### ISSUE TITLE
Tooltips sometimes appear without actually hovering the button

### ISSUE THREAD

**Issue by NomDeMorte** [Tyrrrz/LightBulb#119]
For example:

Click the toggle button in the top left of the UI.
Alt-tab away from the application. 
Move the mouse cursor so that it won't hover the window
Alt-tab back to the application.
This happens: 
![image](https://user-images.githubusercontent.com/45681208/69095696-fcc77380-0aa6-11ea-98f6-b883809da35b.png)

I think perhaps the tooltip shows when the UI element is selected, as well as when it is hovered? Reason for this is another method to reproduce this is: Click the close button, move the mouse to the tray, click the icon to reopen - the close button tooltip appears.

**Comment by Tyrrrz** [comment]
Yeah this is just how the framework we use renders the tooltips. Not much we can do here.

**Comment by NomDeMorte** [comment]
No problem. Please don't feel any pressure from my reports here, this is just 'keeping you in the loop'. I'm fine with a close and 'wontfix' status :)
