### ISSUE TITLE
[Feature request] RAM usage?

### ISSUE THREAD

**Issue by vatterspun** [Tyrrrz/LightBulb#12]
Any way to bring down the overall RAM in use by the program?  On my Win7-64 machine it's using almost 66 megs.  I realize this isn't a big deal for most users but my work machine (where I really need this program) is a fairly low-end system.  

I don't know how possible this is in a C# framework but thought I'd ask.

**Comment by Tyrrrz** [comment]
.net applications tend to use more RAM than native applications in general, there's not much you can do about it. While I'd also prefer LightBulb to have minimal resource usage, I don't think 66 megs (40mb for me) usage is anything excessive yet. Also I have no idea how would I go about reducing it, lol.

Also worth a read: http://stackoverflow.com/questions/223283/net-exe-memory-footprint

**Comment by vatterspun** [comment]
Bummer, thanks for the reply
