### ISSUE TITLE
Presets and explaining things

### ISSUE THREAD

**Issue by jantheodor** [Tyrrrz/LightBulb#123]
I think many people, who run the app for the first time and take a look at the gamma values have no clue, why it is, that you chose 6600k for the day-time and 3900k for the night-time, and what to do about them. B̶u̶t̶ ̶i̶f̶ ̶t̶h̶e̶y̶ ̶d̶a̶r̶e̶ ̶t̶o̶ ̶f̶i̶d̶d̶l̶e̶ ̶a̶r̶o̶u̶n̶d̶ ̶w̶i̶t̶h̶ ̶i̶t̶,̶ ̶t̶h̶e̶y̶ ̶m̶a̶y̶ ̶e̶n̶d̶ ̶u̶p̶ ̶w̶i̶t̶h̶ ̶a̶ ̶m̶e̶s̶s̶y̶ ̶r̶e̶s̶u̶l̶t̶,̶ ̶n̶o̶t̶ ̶k̶n̶o̶w̶i̶n̶g̶ ̶h̶o̶w̶ ̶t̶o̶ ̶r̶e̶t̶u̶r̶n̶ ̶t̶o̶ ̶t̶h̶e̶ ̶d̶e̶f̶a̶u̶l̶t̶ ̶(̶w̶i̶t̶h̶o̶u̶t̶ ̶r̶e̶i̶n̶s̶t̶a̶l̶l̶i̶n̶g̶)̶,̶ ̶w̶h̶i̶c̶h̶ ̶i̶s̶ ̶a̶ ̶b̶a̶d̶ ̶t̶h̶i̶n̶g̶,̶ ̶i̶f̶ ̶y̶o̶u̶ ̶w̶a̶n̶t̶ ̶t̶o̶ ̶m̶a̶k̶e̶ ̶y̶o̶u̶r̶ ̶a̶p̶p̶ ̶a̶s̶ ̶u̶s̶e̶r̶ ̶f̶r̶i̶e̶n̶d̶l̶y̶ ̶a̶s̶ ̶p̶o̶s̶s̶i̶b̶l̶e̶.̶.̶.̶

Please consider presets:

Presets would make this much easier to handle AND to grasp. If you take a look at your biggest "competitor" on the "market" (f.lux) which I'm sure you did, they did a great job by creating different presets named in a way, that is somewhat graspable, compared to a bunch of numbers you at least have a fair idea about "what" and "what for" (https://care-eyes.com/wordpress/wp-content/uploads/2019/05/fl_types.png).

I'd highly recommend to add a little wiki- or FAQ-, explanatory-text- button within your apps main window, to give the user easy access to understanding the numbers you have chosen to set as default and what the pros and cons are, and how they compare with the kelvin spectrum that sorround us by nature, like: sunset, daytime, candle-light, etc (https://en.wikipedia.org/wiki/Color_temperature). 

It sure can't hurt to add a little explanation about the circadian rhythm and why it is beneficial for the user to run this beautiful app of yours.

I'd also consider giving the user the "power" to create "custom" presets.

**Comment by Tyrrrz** [comment]
>...not knowing how to return to the default

There is a "Reset" button in the settings window which reverts all settings back to default.

Presets are a great idea and I also agree that we should expand wiki to include more info on what each setting does. We used to have this guide but it got outdated with this release and thus removed.

**Comment by jantheodor** [comment]
Oh boy.*face palm* sorry about that. I sometimes have a "black spot" in my eyes/brain. Thanks for the answer 👍

**Comment by Tyrrrz** [comment]
I've also started [this wiki page](https://github.com/Tyrrrz/LightBulb/wiki/How-LightBulb-works) with some introduction to LightBulb. Anyone can edit the wiki so it's open for improvements.

**Comment by jackgomes** [comment]
Hi I'm from Brazil! I use windows 7 and the 32-bit system. I downloaded the latest version and it didn't work. What is the reason?

**Comment by Tyrrrz** [comment]
@jackgomes I think there's an issue with 32 bit systems currently. Should be fixed in the next release.

**Comment by jackgomes** [comment]
> @jackgomes Acho que há um problema com os sistemas de 32 bits atualmente. Deve ser corrigido na próxima versão.

ok, I'll wait for the next version

**Comment by broizter** [comment]
Presets would be very nice. When I want to watch a movie for example I need to go into settings and change the temperature/brightness to not ruin the image too much.

**Comment by fabiorfreitas** [comment]
Expanding on @broizter's commentary, presets would be very useful for any kind of color sensitive operations, including movies, but also games and working with pictures. When using this color sensitive mode, one would be able to trade in gamma offset for a bigger reduction in brightness.

Color-Sensitive mode and Movie mode sound like good built-in presets, but the best possible version would allow the user to create their own presets, assign hotkeys to them and associate applications to them (in the same manner as whitelisting).

**Comment by jantheodor** [comment]
> but the best possible version would allow the user to create their own presets, assign hotkeys to them and associate applications to them (in the same manner as whitelisting).
agreed. but sounds like a lot of effort for a very little fraction of the userbase

**Comment by fabiorfreitas** [comment]
Well, yes, this is very relevant, but perhaps it doesn't need to be that hard: depending on how presets are implemented, this could be done by manually adding/editing .json files in %appdata%/lightbulb. 

Settings.json looks simple enough, so if this is an advanced feature, maybe leave a bit more of the work to the user.

**Comment by IGrayfoxI** [comment]
Imitating f.luxs "Darkroom mode" would be nice as a preset.

**Comment by Tyrrrz** [comment]
Hi.
Unfortunately I have to descope this issue as the project has moved into maintenance mode, which means that new features are unlikely to get implemented.
