### ISSUE TITLE
Won't start

### ISSUE THREAD

**Issue by lordhellraiser** [Tyrrrz/LightBulb#125]
First at all, terrific job with v1.x, it replaced all the other alternatives I've ever used. Now I can't wait to test v2.0, but it seems the app just don't go along with my PC.

I'm a programmer myself, I've been into PCs since DOS era and as it was perfectly pointed out in #122, the .NET Core stuff is not user friendly at all. Plus its size 27.5mb installer and :

![Capture](https://user-images.githubusercontent.com/3705195/69879606-7ae8fe80-128d-11ea-9219-121e13b8814e.png)

And all for nothing, the app doesn't start. No error is shown or log is created, also there's no _readme_ file for debug/portability command line options. And sadly portability petty much is defunct with the .NET Core requirement.

My environment (Windows v10.0.18363 x64) is perfectly clean, there are no installations other than the drivers installed by Windows itself, and no leftovers from other applications. Before running any app a uninstall snapshot is created, compared and changes are listed in order to create a launcher app that takes care of subsecuent uses. If something wrong happens (like .NET Core installation/LightBulb not running), I rollback a HDD snapshot to the baseline, rather than manually reverting changes.

Tried a couple of times and nothing. Is there any other requirement? Looks pretty proimsing, keep up the good work; the crystal-like fragile MS ecosystem and the community forced to use it, thank you.

**Comment by Tyrrrz** [comment]
Hi,

Noticing how you mentioned "27.5mb", it's actually closer to 60mb in total because there are two installers? Have you installed both?

I know it's terribly unfriendly, I've made a guide here: https://github.com/Tyrrrz/LightBulb/wiki/How-to-install-.NET-Core-runtime

**Comment by lordhellraiser** [comment]
Thanks!

I try my best to RTFM, but sometimes not-so-small details scape from my sight. OTOH, it ran; then crashed while clicking the "About" button, first stating that "Access is denied" and then Windows blocked the app. Even tho it was running as a child of an elevated process, I don't know what's that about. Also tray icon looks pretty Win95.

- 1st crash
![ScreenShot 20191201183159](https://user-images.githubusercontent.com/3705195/69923747-de7d5280-146c-11ea-811b-a3426682c46a.png)

- 2nd crash
![ScreenShot 20191201185104](https://user-images.githubusercontent.com/3705195/69923776-0371c580-146d-11ea-87f3-71a8f4e77957.png)

- Tray icon
![ScreenShot 20191201185153](https://user-images.githubusercontent.com/3705195/69923994-5730de80-146e-11ea-8125-35713ee7cfbf.png)

Anyway, love it... new design is solid. I was able to test in 2 Intels x86 with no hiccups and one AMD x64 and crashed the same; maybe issue is architecture-related. For what is worth, the other Windozes were not sqeaky clean, but are in pretty decent shape.

**Comment by Tyrrrz** [comment]
That's weird. Looks like some it had some restrictions on running a new process (which it needs to open an URL in browser). Can't really say where that's coming from, haven't seen that error before.

Does the core functionality still work besides that?

The icon issue is tracked here: #117

**Comment by lordhellraiser** [comment]
Running sweet, so far no other issues. Tonight it will be tested in around 20 very different PCs (couple of them still have W8.1; In both, x86/x64).

As far as the original issue goes, this is now closed.

**Comment by Tyrrrz** [comment]
Glad to hear :)
