### ISSUE TITLE
Setting to disable brightness adjustment

### ISSUE THREAD

**Issue by kmindi** [Tyrrrz/LightBulb#126]
Some laptops have an included brightnes sensor, in this case there should be a setting to disable brightness adjustments.

**Comment by Tyrrrz** [comment]
Simply set day/night brightness to 100% for that. Laptop brightness is on a different layer.

**Comment by kmindi** [comment]
@Tyrrrz oh okay, then this is relative to what the laptop does, maybe this should be mentioned in a hint or something then?

**Comment by Tyrrrz** [comment]
Good idea.

**Comment by Tyrrrz** [comment]
I'll close this issue since the question was answered :+1:
