### ISSUE TITLE
Clarification for disabling the application during daytime

### ISSUE THREAD

**Issue by 07416** [Tyrrrz/LightBulb#127]
I want to completely disable Lightbulb during the day. 

- Does 6600 (the default for daytime) change my monitor's color temperature in any way?
- Do I have to keep the "default to daytime configuration" option off?

**Comment by Tyrrrz** [comment]
>Does 6600 (the default for daytime) change my monitor's color temperature in any way?

No it doesn't.

>Do I have to keep the "default to daytime configuration" option off?

No. That's only for when your day configuration is not 6600K/100% and you want to use your day configuration for when LightBulb is disabled.
