### ISSUE TITLE
Clarification on auto updates

### ISSUE THREAD

**Issue by sfkpmr** [Tyrrrz/LightBulb#129]
The release notes for 2.0 say that there's an auto updater included, but I don't see any mention of this inside of LightBulb.

**Comment by Gitoffthelawn** [comment]
Can the auto-updater be turned off?

**Comment by Tyrrrz** [comment]
Not at the moment, no

**Comment by Gitoffthelawn** [comment]
Would be best if it could be disabled.

Perhaps on first run, before attempting to access the internet at all, ask the user if they want auto-updates enabled or disabled (and add a toggle in the UI).
