### ISSUE TITLE
Problems with more than one monitor

### ISSUE THREAD

**Issue by broizter** [Tyrrrz/LightBulb#130]
When having more than one monitor, LightBulb v2 never enables the color profile. If I disable my second monitor, I can then get it to work on my first monitor if I disable and reenable LightBulb again. 
I can never get it to work on my second monitor.

**Comment by Tyrrrz** [comment]
Can you give more details about your setup? What OS/build are you using, what is the make of the monitors, what interface are they connected with?

**Comment by broizter** [comment]
OS: Windows 10 - Latest update
LightBulb version: 2.0
Monitor 1:  C27FG73 connected with DP
Monitor 2: BenQ GW2760 connected with DVI

**Comment by Tyrrrz** [comment]
Do you, by any chance have TeamViewer installed?

**Comment by broizter** [comment]
I do not, no.

**Comment by Tyrrrz** [comment]
Hey, @ChrisLMerrill does anything sound familiar? I remember you were having somewhat similar issues.

**Comment by ChrisLMerrill** [comment]
That sounds roughly like my problem (#102), but not quite the same. My problem was specific to the laptop waking (e.g. from power-saving) and affected all attached monitors. And it worked on all monitors if I used the preview feature.

HTH!
Chris

**Comment by broizter** [comment]
Yeah probably not the same then. Preview does nothing for me.

**Comment by Tyrrrz** [comment]
Are there any notable errors in Windows event log?

**Comment by broizter** [comment]
No, nothing. 

Now I've discovered another weird thing. If I restart the program, it starts working again but only on my second monitor. Enable/disable/preview has no effect on my main monitor anymore.

**Comment by Tyrrrz** [comment]
Interesting. Did LightBulb v1 work for you? If you haven't tried, can you temporarily download 1.6.4.1 to see if it works? It used a slightly different approach for updating gamma.

**Comment by broizter** [comment]
No same problem there. It behaved identically if I remember correctly.

**Comment by Tyrrrz** [comment]
That's very weird. Just to be safe, are your both monitors connected to the same GPU?

**Comment by broizter** [comment]
Yes they are, but that helped me find the underlying problem I think!

Although both monitors are connected to my Nvidia GTX 1070, I have my Intel IGPU enabled so that I can use Intel Quick Sync. Disabling the IGPU in BIOS seems to have fixed the problem. I don't need to have it working since I rarely use it, so for my usecase I will consider this issue solved.

**Comment by Tyrrrz** [comment]
Yay :)
