### ISSUE TITLE
Lightbulb keeps crashing after setting location coordinates

### ISSUE THREAD

**Issue by Greentaily** [Tyrrrz/LightBulb#132]
Lightbulb crashes when I try and enter my location coordinates on the "Location" tab in the settings. The application then won't run at all, presumably crashing on startup. I tested this on three separate computers running windows 10. Not sure what else to add here, as otherwise it seems to work fine.

**Comment by Tyrrrz** [comment]
Hi.
By "enter my location" do you mean you've entered an address/zip code or exact coordinates?

**Comment by Greentaily** [comment]
I tried typing in both precise coordinates and the city name, it makes no difference

**Comment by Tyrrrz** [comment]
Does it work with any other location or if you use autodetection?

**Comment by Greentaily** [comment]
It does indeed, however autodetection fails to provide me with correct coordinates (which does not seem to be a lightbulb issue)

**Comment by Tyrrrz** [comment]
Hm, looks like an issue with specific location then. Can you tell me the city name you're using?

**Comment by Greentaily** [comment]
Tromsø, coordinates 69.6489, 18.9551

**Comment by Tyrrrz** [comment]
Thanks, I'll investigate what's wrong.

**Comment by Tyrrrz** [comment]
Looks like the problem is that you guys won't have a proper sunrise until 15th of January. The algorithm currently expects a certain sun ascension which it never reaches at this time of year in Tromsø, Norway.

I'm going to patch it so that it uses the sun's highest point instead as I assume that's the most intuitive solution in this case.

**Comment by Tyrrrz** [comment]
This fix will be in next release. For now you can snatch a CI build from artifacts here: https://github.com/Tyrrrz/LightBulb/runs/372806600 or wait until Jan 15th when it fixes itself on its own. :)
