### ISSUE TITLE
Wake up notification

### ISSUE THREAD

**Issue by AnaruSensei** [Tyrrrz/LightBulb#135]
Hello,
can you add the "wake up" function like the "f.lux" program does?
another nice feature is the "take a break from pc" warning as does the "eye saver" program.
With these changes Lightbulb will be the best program in the world!
best regards
Anaru

**Comment by Tyrrrz** [comment]
Hi,
What is the  "wake up" function?

**Comment by AnaruSensei** [comment]
You can set a time when you wake up, for example 7:30 am, while using the PC for example at 11:30 pm, the alarm will warn you that in 8 hours you have to wake up.
It doesn't work if you play or use full screen programs.
Convenient function for those who do not want to go to bed but the alarm clock reminds you how little you sleep :)
To better understand, try the f.lux program

https://justgetflux.com

**Comment by Tyrrrz** [comment]
I've decided this is out of the scope for this application as I want it to focus only on gamma and not police your sleeping schedule.
