### ISSUE TITLE
LightBulb not launching on Windows 10

### ISSUE THREAD

**Issue by rabbit-93** [Tyrrrz/LightBulb#136]
I have a Windows 10 Pro 64 bit. I have installed both .NET Core Runtime x86 and x64. And I still can't run LightBulb. No reaction at all, even if I try to launch it from a CMD it still doesn't print anything. I've tried to compile it myself but this was the result:

```
The call is ambiguous between the following methods or properties: 'LightBulb.Internal.Extensions.AddRange<T>(System.Collections.Generic.ICollection<T>, System.Collections.Generic.IEnumerable<T>)' and 'Tyrrrz.Extensions.CollectionExtensions.AddRange<T>(System.Collections.Generic.ICollection<T>, System.Collections.Generic.IEnumerable<T>)'	LightBulb	C:\Users\rabbit\Source\Repos\LightBulb\LightBulb\Services\RegistryService.cs	


The call is ambiguous between the following methods or properties: 'LightBulb.Internal.Extensions.OpenInBrowser(System.Uri)' and 'Tyrrrz.Extensions.UriExtensions.OpenInBrowser(System.Uri)'	LightBulb	C:\Users\rabbit\Source\Repos\LightBulb\LightBulb\ViewModels\RootViewModel.cs	
```

**Comment by Tyrrrz** [comment]
Hi,
Just to clarify, you've installed the desktop runtime, not the base runtime, right?
Can you look at the Windows event viewer and see if there are any logs written when you try to launch LightBulb?

**Comment by Tyrrrz** [comment]
Also, the source code definitely should compile, are you sure you've cloned the latest master? It may have been failing 4 days ago but CI is running stable right now: https://github.com/Tyrrrz/LightBulb/commit/830dc1cbfea0c9a1e06728b87350552c5cb73875/checks?check_suite_id=392684772

**Comment by Tyrrrz** [comment]
If you're on 64bit, try uninstall .NET Core runtime 32bit, it may be overriding the other one in PATH.

**Comment by rabbit-93** [comment]
Hi, sorry for the late reply.

> Hi,
> Just to clarify, you've installed the desktop runtime, not the base runtime, right?
Yes I did install desktop runtime.
> Can you look at the Windows event viewer and see if there are any logs written when you try to launch LightBulb?

I found this one:
`Description: A .NET Core application failed.
Application: LightBulb.exe
Path: C:\Program Files (x86)\LightBulb\LightBulb.exe
Message: Failed to load the dll from [C:\Program Files (x86)\LightBulb\hostfxr.dll], HRESULT: 0x800700C1
The library hostfxr.dll was found, but loading it from C:\Program Files (x86)\LightBulb\hostfxr.dll failed
  - Installing .NET Core prerequisites might help resolve this problem.
     https://go.microsoft.com/fwlink/?linkid=798306`


>Also, the source code definitely should compile, are you sure you've cloned the latest master? 
Yes, I'm sure.

>If you're on 64bit, try uninstall .NET Core runtime 32bit, it may be overriding the other one in PATH.
I didn't have 32bit installed at start, I installed it later because I thought it may help, well it didn't.

**Comment by Tyrrrz** [comment]
Have you tried installing prerequisites as it suggests in the error?
https://go.microsoft.com/fwlink/?linkid=798306

**Comment by rabbit-93** [comment]
> 
> 
> Have you tried installing prerequisites as it suggests in the error?
> https://go.microsoft.com/fwlink/?linkid=798306
> 
> Specifically:
> https://www.microsoft.com/download/details.aspx?id=52685

It says that I already have it installed.

> https://support.microsoft.com/help/2533623/microsoft-security-advisory-insecure-library-loading-could-allow-remot

This does not appear to be related to Windows 10.

**Comment by Tyrrrz** [comment]
The only thing else I could think of is to try and uninstall the 32bit .NET Core runtime you installed additionally.

**Comment by rabbit-93** [comment]
I've just uninstalled it and there's no difference.

**Comment by Tyrrrz** [comment]
I'm out of ideas, sorry..

**Comment by Tyrrrz** [comment]
@fasetto 
It's literally mentioned everywhere though.

![image](https://user-images.githubusercontent.com/1935960/72515248-3ecb2680-3858-11ea-89e7-700ae38fe0eb.png)
![image](https://user-images.githubusercontent.com/1935960/72515265-4985bb80-3858-11ea-9713-f8ab1129d136.png)
![image](https://user-images.githubusercontent.com/1935960/72515312-599d9b00-3858-11ea-9441-718b2dac3a27.png)
![image](https://user-images.githubusercontent.com/1935960/72515330-615d3f80-3858-11ea-9251-6e16508343ff.png)

**Comment by fasetto** [comment]
I 've checked the releases again, and I saw you mentioned the dependeny. 
I was dumb to not read all things there. I am sorry (:
Thank you for this great application.

**Comment by Tyrrrz** [comment]
Going to close this as the conversation died down and I don't really have anything else to contribute besides "it should work". The error `The library hostfxr.dll was found` is usually found when .NET Core runtime has not been installed.
