### ISSUE TITLE
Periodic reminder to take a break

### ISSUE THREAD

**Issue by liwenbus** [Tyrrrz/LightBulb#137]
I hope there will be a timer so that it will remind me to take a break every 20 mins or any time. Thank you very much.

**Comment by xcasxcursex** [comment]
I like this idea but I feel like it's a job for a different application. There are LOTS of apps that already exist for this job. Since we're on github I'll assume you prefer a quality open-source option, so maybe check out https://github.com/hovancik/stretchly

**Comment by Tyrrrz** [comment]
I also believe it's out of scope. I know f.lux does it but that program really likes being the dominant one in a relationship.
