### ISSUE TITLE
Fix for SetGammaRamp

### ISSUE THREAD

**Issue by sndcode** [Tyrrrz/LightBulb#138]
Hi,

i dont know how to contact you directly , i tried on instagram but i guess you are not active there.
I ran into the same bug as you some months ago, but cant figure out how to fix the bug on my app..

please contact back on instagram if you see this and delete this ofc

**Comment by Tyrrrz** [comment]
Hi @sndcode.
I can't say much more besides "look at the code" 😄

**Comment by sndcode** [comment]
> Hi @sndcode.
> I can't say much more besides "look at the code" 😄

well , i did .. But since im not a pro and also dont have much time to spend on my hobby anymore i just dont get it done.. 
I found out that you used a "new way" to set up the gammaramp thing but since all i have is parts of the code how it was and how you updated it, but my codebase is completely different here i am confused

**Comment by Tyrrrz** [comment]
Before the fix, I used to pass NULL device context to GetHDC. After the fix, I changed it so that it gets handles of all monitors and updates gamma on each monitor separately.
