### ISSUE TITLE
Gamma setting after Sleep

### ISSUE THREAD

**Issue by LotusOttawa** [Tyrrrz/LightBulb#139]
When coming out of Windows 10 sleep the gamma/brightness setting doesn't apply. I have to manually run through a preview for it to apply.

**Comment by Tyrrrz** [comment]
What version of LightBulb/Windows are you using? What are your monitors connected through?

**Comment by LotusOttawa** [comment]
I've seen this same behaviour on 2 machines.

LightBulb v2.0.0
Windows 10 v1909 and Windows 10 v1803
Monitors are connected through:
Intel i7 on chip GPU -> USB 3.1 -> dock -> HDMI and Display Port
AMD video card -> DVI-D and Display Port

**Comment by Tyrrrz** [comment]
This is indeed weird. Looks like I'll have to re-add gamma polling as an option for such cases.

**Comment by motiontwelve** [comment]
I have been observing the same issue with v2.0.0 as well.  The only way to see the adjusted gamma & brightness again is to go into the settings and set them manually.

**Comment by Tyrrrz** [comment]
You can try the latest CI build https://github.com/Tyrrrz/LightBulb/actions/runs/49690507

I've added an option in settings called "Gamma polling" which, if enabled, causes gamma to force-refresh every second.
