### ISSUE TITLE
The app ran perfectly yesterday but the gamma doesn't change today when I start my PC

### ISSUE THREAD

**Issue by Tristan1416** [Tyrrrz/LightBulb#143]
Hi, Tyrrrz. Thx for the app. But it is a pitty to enjoy it for one day. I have done everything it needs to run  , and it runs perfectly yesterday. My PC is win10 64bit

**Comment by Tyrrrz** [comment]
Hi.
Just to clarify, it's not changing gamma in the evening?

**Comment by Tristan1416** [comment]
Well, it just worked the I installed it. And the other day I start my PC, it does not work for a second.

**Comment by Tyrrrz** [comment]
With the default settings, you won't be able to see any difference until after your local sunset.

**Comment by sfkpmr** [comment]
I had to reinstall a few days ago, because I noticed that the times seemed to get reversed. My screens started to turn yellow AT sunrise.

Are there any log files?

**Comment by Tyrrrz** [comment]
Can you clarify on "times seemed to get reversed"? What do you mean?
There are no logs unfortunately, but you can share your configuration file so that I can try replicating it locally. It's in `%appdata%/LightBulb/Settings.json`.

**Comment by sfkpmr** [comment]
Normally LightBulb should be active between sunset and sunrise, but it felt like it wasn't active at all during the night, and then at sunrise I started to notice the screen turning yellow.

{
  "IsFirstTimeExperienceEnabled": false,
  "NightConfiguration": {
    "Temperature": 3900.0,
    "Brightness": 0.85
  },
  "DayConfiguration": {
    "Temperature": 6600.0,
    "Brightness": 1.0
  },
  "ConfigurationTransitionDuration": "01:30:00",
  "IsManualSunriseSunsetEnabled": false,
  "ManualSunriseTime": "07:20:00",
  "ManualSunsetTime": "16:30:00",
  "Location": {
    "Latitude": 59.3251172,
    "Longitude": 18.0710935
  },
  "IsAutoStartEnabled": true,
  "IsDefaultToDayConfigurationEnabled": false,
  "IsConfigurationSmoothingEnabled": true,
  "IsPauseWhenFullScreenEnabled": false,
  "IsApplicationWhitelistEnabled": false,
  "WhitelistedApplications": null,
  "ToggleHotKey": {
    "Key": 0,
    "Modifiers": 0
  }
}

**Comment by Tyrrrz** [comment]
Can't seem to replicate this. Is the system clock configured properly? The timezone needs to match your actual timezone, as well as your time.

**Comment by sfkpmr** [comment]
Yes, clock and timezone is correct. I'll take another look if it happens
again.

**Comment by xcasxcursex** [comment]
Just a thought but - have you ben running linux on the PC at all? (perhaps dual-boot or from a USB stick....or perhaps some other time-sync software is running?) 

Linux will set the time of the PC hardware to use UTC, and compensate for that in the operating system, whereas Windows will set the hardware clock to local time and not compensate. It can be known to cause issues where the time seems 'not right', because the time can be in-and-out of sync depending on the time you check it.

If this is the case, you can configure windows to use UTC for the hardware clock as linux does, and the problem will be resolved. Just a guess, though.

**Comment by Tyrrrz** [comment]
Also, there were some issues with time continuity because of time zones. I don't think this is one of those cases, but you can try downloading the CI build and see if the error persists there as well.

https://github.com/Tyrrrz/LightBulb/actions/runs/63010329

**Comment by Tyrrrz** [comment]
Please try last release (v2.1) and see if the issue persists.
