### ISSUE TITLE
32bit Installer does not detect need to download 32bit runtime when 64bit runtime exists.

### ISSUE THREAD

**Issue by xcasxcursex** [Tyrrrz/LightBulb#145]
I notice you've decided to distribute this as 32bit (sadface. Who's using 32bit OS these days? Anyway....)

Decided to try the new build and when it started it told me I needed the runtime...which I already had, of course. Fortunately I could see what was going on and went and got the 32bit version of the runtimes and it's working OK but... it wasn't a great experience.

You mentioned in another issue, that you wanted to stick to 3.0 as the prerequisite so that earlier adopters would not need to upgrade, but this is going to force them to upgrade, since they'll have a 64bit build that'll need the 32 bit runtime after upgrading.

Also, the ps1 script installs the correct runtime for the bitness of the OS, and not for the bitness of the app.

Some tweaks to the intaller/ps1 script are obviously in order, and I would like to help with that but I'm not sure if you ever plan to release a 64bit version of the app and so the appropriate changes to the script aren't quite clear to me yet. Would you want to install the app depending on the bitness of the OS, or the bitness of the runtimes, or install the runtime according to the bitness of the app, or just ditch 64bit support entirely, or.... You see what I mean. There are many ways to skin this cat. (Edit: I hope that figure of speech translates to wherever you're from, or it will sound really gross hahah... I mean, there are many possible approaches to this issue and I'm not sure which you intend to take)

Any thoughts?

**Comment by Tyrrrz** [comment]
Hmm. The 32bit change should only affect the executable that bootstraps the assembly. It shouldn't require users to install a 32bit runtime, as that's dependent on the OS, not on the apps you want to run (yeah, extremely confusing). Are you saying you couldn't run the app until you had 32bit runtime installed?

**Comment by Tyrrrz** [comment]
Looks like you're right, my understanding was incorrect. I'm reverting the change.

**Comment by xcasxcursex** [comment]
> Ehrm.. Now this is 64-bit only? Wtf?

32 bit OS? What year is this?

Also, giving a thumbs down just because I reported a bug, resolving which could get the app to work on either 64 bit or 32 bit? Control yourself.

**Comment by mirh** [comment]
The thumb is for the boasting.

**Comment by tomasz1986** [comment]
> 32 bit OS? What year is this?

There are still plenty of Windows tablets and netbooks around with older Intel Atom processors. All of those are 32-bit only.

**Comment by xcasxcursex** [comment]
I don't think this requires any further discussion. I found a bug, I reported it, it was fixed, this is closed. If there's anyone with a real need to use a 32bit app, I'm sure they can open a new case to discuss it.
