### ISSUE TITLE
Cant use shortcut CTRL+Shift+D0 

### ISSUE THREAD

**Issue by pestrela** [Tyrrrz/LightBulb#149]
thanks for this program. I'm trying to change the keybard shortcut to Ctrl+Shift+D0. 
Othr combinations involving D0 are fine, but not this specific one.

Do you know if this is filtered by windows somehow?

thanks
----
PS: I actually came here from your great article about processing keydown in your own customcontrol
https://github.com/pestrela/cmdr#2020-improvements 

My objective is to add this shortcut in my own program that I've inherited and I'm now learning to maintain it.
https://github.com/pestrela/cmdr#2020-improvements

**Comment by Tyrrrz** [comment]
Seems to work for me

![image](https://user-images.githubusercontent.com/1935960/80367578-0514ad80-8894-11ea-80bd-4fa82340c264.png)

**Comment by pestrela** [comment]
thanks for confirming this. 
I don't get that very specific hotkey in both lightbulb and in my application. 

So it can only be something else that captures the key combination in my particular system. I have AHK scripts but I beleive I disabled them all already.

**Comment by Tyrrrz** [comment]
Yes, most likely something already registered that hotkey. Check your background apps. AMD CCC and Nvidia CP often have a bunch of hotkeys registered and are frequent offenders in this regard.

**Comment by pestrela** [comment]
CTRL+Shift+0 is also used by excel.
Culprit was the language bar of windows 10.
Doing these instructions solved my issue for lightbulb and other programs.
https://excelatfinance.com/xlf18/xlf-change-key-sequence.php

PS: confunsingly the language bar setting did not appear as ON. 
But just accessing this very specifc setting fixed the issue.
