### ISSUE TITLE
Pause on fullscreen doesn't work correctly

### ISSUE THREAD

**Issue by kykym** [Tyrrrz/LightBulb#150]
Hi, Alex 

Your app is great but I'm frustrated with the one bug

I turned "Pause when fullscreen" feature off but when I run fullscreen programs (some fullscreen games) they still change my monitor gamma to normal blue

This still works correctly in fullscreen browsers etc but not in a case of games

**Comment by Tyrrrz** [comment]
Hey.
Do you have anything configured in application whitelist?

**Comment by kykym** [comment]
No, it's clear

I tried on admin rights user and regular user, same result

I tried on a special Administrator account and it seemed to work in games  properly but I'm not sure

**Comment by kykym** [comment]
Also I tried different combinations with launching LigthBulb and games in an administrator mode but no result

**Comment by Tyrrrz** [comment]
It could be that some games are simply overriding gamma on their own. Could you try turning on "Gamma polling" in advanced settings?

**Comment by kykym** [comment]
Tried that, same :(

**Comment by kykym** [comment]
I mean it works really fine in all borderless windowed fullscreen apps (I tested exceptions and app recognize such programs so it turns on or off all that gamma) but not in the simple game fullscreen in my case

**Comment by Tyrrrz** [comment]
Hmm. When you say that polling doesn't work, does it mean you see absolutely no difference? Does it not even flash or change gamma for a split second?

**Comment by kykym** [comment]
You mean that game starts with the LightBulb gamma for a second and then goes blue again?

**Comment by Tyrrrz** [comment]
Well yes. Any sort of flickering that would indicate that the gamma is changed by multiple applications.

**Comment by kykym** [comment]
Yeah, the game looks fine when it loading but goes blue when in menu. Even with Gamma polling on

**Comment by kykym** [comment]
I don't run the game or the app in admin mode but my account has admin rights

**Comment by Tyrrrz** [comment]
Hm, I'm at loss then.

**Comment by kykym** [comment]
I was using another blue light filtering app for a while but changed some uac settings and started having same issue so I moved to your app. It's really user friendly

**Comment by Tyrrrz** [comment]
Could you also try uninstalling it, deleting `%appdata%/LightBulb` folder entirely, and then installing it again?

**Comment by kykym** [comment]
Wow, was preparing to do this and opened game for a last check. The screen turned blue for a second and then your app returned it normal night gamma

**Comment by kykym** [comment]
Reinstalled, works as above. 

Thanks Alex your app is great. Although a flash of a blue light on a start of a game is a bit annoying

**Comment by Tyrrrz** [comment]
Glad to hear!
Unfortunately the flash is unavoidable, but you can close your eyes for a few seconds :)
