### ISSUE TITLE
Lightbulb installer automatically overwrites existing directory without prompting

### ISSUE THREAD

**Issue by diamondavocado** [Tyrrrz/LightBulb#154]
Windows 7 x64 

This is a weird one, but the Lightbulb installer just overwrote my existing Lightbulb installation directory without prompting me. The funny thing is, it only did this the second time I ran it. The first time I ran the installed it allowed me to choose the directory.

I was previously using a portable version and wanted to try the full installer.

Here's what I did:

1. I made a backup copy of my old Lightbulb portable folder i.e. `cp -rf "C:\Program Files\Lightbulb" "C:\Program Files\Lightbulb - Copy"`
2. I ran the new Lightbulb installer -- it prompted me to choose the installation directory and I chose my Lightbulb portable folder: `C:\Program Files\Lightbulb` and it prompted me to overwrite the existing contents, which I did since I had made a backup.
3. Lightbulb iteself wouldn't launch (see my now-closed issue) so I deleted the new installation and restored my backup folder i.e. `rm "C:\Program Files\Lightbulb"; mv "C:\Program Files\Lightbulb - Copy" "C:\Program Files\Lightbulb"`
4. I later decided to try the installer again. I launched it, intending to choose a different installation directory this time and keep my portable version intact, but this time it didn't prompt me and just installed straight to the `C:\Program Files\Lightbulb` folder, thus overwriting my old installation without warning.

**Comment by Tyrrrz** [comment]
I assume that's specific to InnoSetup. I guess you'd have to uninstall the old installation first in order to install another one into a different location.
