### ISSUE TITLE
Startup with a black form on Windows 7

### ISSUE THREAD

**Issue by taozhiyu1978** [Tyrrrz/LightBulb#155]
![无标题](https://user-images.githubusercontent.com/65323773/81887562-f804f780-95d1-11ea-9473-af1c642f770a.png)

when Windows 7 startups, LightBulb (Version:2.1.0) shows a black form.

**Comment by Tyrrrz** [comment]
That doesn't look right. Unfortunately I don't have Windows 7 to test.

Anyone else on Windows 7 sees the same thing?

**Comment by mirh** [comment]
Does it still happen with 2.2, and do you have SP1+KB2670838 installed?

**Comment by taozhiyu1978** [comment]
> Does it still happen with 2.2, and do you have SP1+KB2670838 installed?

if any problem, I will follow this post.thanks. it is ok at the moment.

**Comment by Tyrrrz** [comment]
Closing as this seems to have been fixed.
