### ISSUE TITLE
Development documentation

### ISSUE THREAD

**Issue by KyleBsingh** [Tyrrrz/LightBulb#156]
I was hoping to contribute to, or fork, LightBulb, and was wondering if there was any development documentation available.

**Comment by Tyrrrz** [comment]
No, but you can just ask questions.

**Comment by KyleBsingh** [comment]
Okay, thank you!

 I wanted to know any dependencies needed to build the project, and the process to build it locally.

**Comment by Tyrrrz** [comment]
At minimum: Microsoft Visual Studio 2019 Community Edition or JetBrains Rider. The default loadouts should contain everything needed. Then just clone and build, it should work without any additional setup.
