### ISSUE TITLE
Mouse doesn't change colors with Windows 10

### ISSUE THREAD

**Issue by anderrom** [Tyrrrz/LightBulb#157]
My mouse is a white bright point on the screen. I had the same issue with F.lux, but they added a setting, Software mouse rendering irc, that solved the issue.

**Comment by Tyrrrz** [comment]
Related wiki:

https://github.com/Tyrrrz/LightBulb/wiki/Troubleshooting#cursor-is-not-affected-by-gamma-changes

A common workaround (if you can't or don't want to disable hardware rendering in GPU settings) is to change your cursor to darker/black color scheme.

**Comment by newgivi** [comment]
The dark cursor will remain unaffected anyway. So it will be black, but not yellowish black.

The only workaround I found is to add an invisible trail to the cursor. Thus the system won’t use hardware rendering for a cursor: 

1. Open Registry Editor. Perhaps the easiest way is, just open the Start menu and type "regedit". You'll see.
2. Navigate to HKEY_CURRENT_USER\Control Panel\Mouse
3. In the right-hand pane, double-click MouseTrails.
4. Change the value to either 99 or -1. Both should do the same thing, but you can experiment to see if one works better than the other for some reason. On my computer, they're identical but still.
5. Close Registry Editor
6. Log out of Windows and log back in, or just restart.
7. Test it.

[Source](https://forum.justgetflux.com/topic/3539/mouse-is-unaffected-by-f-lux/3)
