### ISSUE TITLE
LightBulb isn't launching (despite troubleshooting's solutions)

### ISSUE THREAD

**Issue by yarow12** [Tyrrrz/LightBulb#160]
I have Microsoft Visual C++ 2015 Redistributable (x64) - 14.0.24212 installed, but am unable to install the KB2533623 update because it's "not applicable to your computer". Are there any other ways around this? I'm running Windows 7 64bit with Service Pack 1.

For any others in this situation, here:

https://github.com/Tyrrrz/LightBulb/wiki/Troubleshooting#lightbulb-isnt-launching-despite-net-core-runtime-being-correctly-installed

https://social.technet.microsoft.com/Forums/lync/en-US/edaac7af-d67f-4162-85ec-c24a78edaf03/commandprompt-to-check-installed-windows-updates

https://www.techsupportalert.com/content/quick-and-easy-way-list-all-windows-updates-installed-your-system.htm

**Comment by Tyrrrz** [comment]
That's weird. Can you try downloading and installing it directly?
https://www.microsoft.com/en-us/download/details.aspx?id=26767

**Comment by yarow12** [comment]
That link's to the x86 version. I downloaded the x64 version.
https://www.microsoft.com/en-ie/download/details.aspx?id=26764

**Comment by Tyrrrz** [comment]
Googling around suggests that KB2758857 could be an alternative in such cases.
Not sure what's the issue here.

**Comment by yarow12** [comment]
Turns out, I already have [that one](https://www.microsoft.com/en-us/download/details.aspx?id=35936) installed. :/

**Comment by mirh** [comment]
> I have Microsoft Visual C++ 2015 Redistributable (x64) - 14.0.24212 installed, but am unable to install the KB2533623 update because it's "not applicable to your computer".

If you open cmd and run `dotnet --list-runtimes` does it run properly? In this case, indeed the problem shouldn't be on the .net side.

**Comment by yarow12** [comment]
From what I can tell, it does.

> Microsoft.NETCore.App 3.1.3 [C:\Program Files yada yada yada
> Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files yada yada yada

**Comment by mirh** [comment]
What if you try https://github.com/Tyrrrz/LightBulb/issues/172#issuecomment-664456490 from cmd?

**Comment by yarow12** [comment]
> It should be platform agnostic. Try running dotnet LightBulb.dll instead of running LightBulb.exe and see if it helps.

So navigate to LightBulb.exe's directory through cmd and then type "dotnet LightBulb.dll"?

**Comment by Tyrrrz** [comment]
Yes.

**Comment by yarow12** [comment]
Well, it took a few seconds but it actually launched. Thanks.
That being said, I've been been using Iris and am gonna stick with it.

Would users be able to setup a shortcut or exe file to skip/automate the cmd method?
