### ISSUE TITLE
Add time settings to location based transition

### ISSUE THREAD

**Issue by weiwang11** [Tyrrrz/LightBulb#161]
There should be an option to allow LightBulb to start sooner or later based on the location settings as well. 
Lets say that the location settings set the sunset time to 8:00 PM, we should be able to adjust the time based on the location. So if I want it to be 30 minutes sooner, I can input -30Minutes and it will reduce the sunset time to 7:30 PM.

**Comment by Tyrrrz** [comment]
This is probably covered by #131 (aka twilight settings).

Marking as duplicate.
