### ISSUE TITLE
Errors in FUNDING.yml when clicking Sponsor

### ISSUE THREAD

**Issue by fgimian** [Tyrrrz/LightBulb#162]
Hey there, incredible job on LightBulb! 😄 

I noticed that GitHub was complaining about some errors while parsing FUNDING.yml when clicking on Sponsor:

![image](https://user-images.githubusercontent.com/1811813/84592236-6239e200-ae87-11ea-926c-b28ca4b51e04.png)

This may be intentional (due to not being enrolled in the GitHub sponsor program), but just thought I'd raise it in case you were unaware of the error.

Kindest regards
Fotis

**Comment by Tyrrrz** [comment]
Hey, thanks!

I know about this. GitHub Sponsors is not available in Ukraine, so my application is not getting accepted. Until then, the best way to support me is through Patreon or Buymeacoffee.

**Comment by fgimian** [comment]
@Tyrrrz Ah that makes sense.  No worries at all, I'll close this issue for now then. 😄 

Cheers
Fotis
