### ISSUE TITLE
Supoort for multiple time periods throught out the day

### ISSUE THREAD

**Issue by Ashutosh-Kukreti** [Tyrrrz/LightBulb#163]
Is it possible to have 4 different temperatures for 4 different time periods in a day
* Sunrise 6AM - 5000K
* Afternoon 12PM - 4500K
* Evening/Sunset - 3800K
* Midnight 12AM - 2500K

It would be very helpful to have this feature.

**Comment by Tyrrrz** [comment]
Most likely not gonna happen, but #131 should make this somewhat doable using twilight zones.
