### ISSUE TITLE
Power profile follow the sun

### ISSUE THREAD

**Issue by dzmitry-lahoda** [Tyrrrz/LightBulb#166]
Choose switch power profiles according light profile. E.g. high perf during day and economy during night.

**Comment by Tyrrrz** [comment]
Not sure what you're suggesting exactly. The power profile currently already follows the sun.

**Comment by dzmitry-lahoda** [comment]
Profile of screen yes, but there is control of fun speed and processor power in % of max. These can be reduced in the night.

**Comment by Tyrrrz** [comment]
Ah I see. This app is only about gamma control, so those things would be out of scope.

**Comment by dzmitry-lahoda** [comment]
the problem is that w10 has some form of lb already and will increase, cause of arm stuff gets momentum. eventually lb will die out, until it will cover more (specifically sound of fans and notifications):

![image](https://user-images.githubusercontent.com/757125/87904520-21755000-ca67-11ea-817e-6eb6366fffc5.png)

**Comment by Tyrrrz** [comment]
I'm not developing a project that attempts to compete with Microsoft, I'm just developing a project that I personally find useful.

**Comment by dzmitry-lahoda** [comment]
Microsoft competes with LB. eventually people will stop to use LB, until it will allow more options. i would even buy payed version on store to handle both display and monitor.

**Comment by Tyrrrz** [comment]
Well Microsoft may compete all they want and people can stop using LightBulb if they want to. It's not a business, this is open source. What I (and the community) do here is purely for fun, not to create a product that competes with anyone.
