### ISSUE TITLE
The app starts, runs, I have configured settings, but it does nothing, with no error messages

### ISSUE THREAD

**Issue by zzxxddffdle** [Tyrrrz/LightBulb#169]
The app starts, runs, I have configured settings, but it does nothing, with no error messages. #168

**Comment by Tyrrrz** [comment]
https://github.com/Tyrrrz/LightBulb/wiki/Troubleshooting

**Comment by zzxxddffdle** [comment]
Thanks to you I found the answer. It was Team Viewer.

**Comment by Tyrrrz** [comment]
Great!
