### ISSUE TITLE
Time format mismatch

### ISSUE THREAD

**Issue by xcasxcursex** [Tyrrrz/LightBulb#171]
I was just testing out #131 and tried to set a sunset time manually. I've changed it to manual in the past and never had an issue, so I think this may be new.

Easiest explained with images...

I open the dialog and see this:
![image](https://user-images.githubusercontent.com/58130821/88009389-b9516780-cb55-11ea-8e22-a5bdc9654e6d.png)

Click to edit it and see this:
![image](https://user-images.githubusercontent.com/58130821/88009434-d5550900-cb55-11ea-8b36-5bd138def26f.png)

Change the time, and when I try to click away:
![image](https://user-images.githubusercontent.com/58130821/88009449-e271f800-cb55-11ea-9eb8-3104b5b6afa5.png)

Using a colon there, works fine.
![image](https://user-images.githubusercontent.com/58130821/88009497-03d2e400-cb56-11ea-9765-63782d9aab3e.png)

When I click away, the colon disappears:
![image](https://user-images.githubusercontent.com/58130821/88009518-11886980-cb56-11ea-954f-25192fd7beb2.png)

I'm guessing this may be related to the fact that I don't use a colon in my time settings:
![image](https://user-images.githubusercontent.com/58130821/88009625-53b1ab00-cb56-11ea-9438-523a5c6cbb0b.png)

**Comment by Tyrrrz** [comment]
Yeah it's definitely because of colons. Is this an Australian locale thing or just your custom settings?

**Comment by Tyrrrz** [comment]
Should be fixed.

**Comment by xcasxcursex** [comment]
Sorry mate, it's behaving strangely.

When I change a minute value and then click away, it now resets to 00 00 (midnight)
If I change any value after that, I get the 'could not be converted' message.
When I change an hour value and click away, I get the same 'could not be converted' message.
Using a colon still works.

**Comment by Tyrrrz** [comment]
I think it gets really confused when there are no separators.

**Comment by xcasxcursex** [comment]
Well technically, I have a separator, it's a space character. Happy to try it with none to see what happens, if you would like?

Honestly this is not a big deal for me. I can just use the : to work around it. I mentioned it because I figured you might like to know because it's a very rare case, but mostly, the reason I mention it is because I have always used this time format, and I've used lightbulb for ages and this is the first time I've had the problem so I thought it might be a result of a recent change... and of course it would be easier for you to isolate the relevant change if I let you know right away.

My point is, feel free to make it a low low priority fix ;)

**Comment by Tyrrrz** [comment]
Do you have access to a .NET development environment?

Could you run the following code and see what it prints?

```csharp
var input = "13 27";

var date = DateTimeOffset.Parse(input, formatProvider, DateTimeStyles.None);

Console.WriteLine(date);
```

**Comment by xcasxcursex** [comment]
Not really... How about powershell?
```
PS C:\Windows\System32\WindowsPowerShell\v1.0> [Datetimeoffset]::Parse("13:37")


DateTime      : 23/07/2020 13 37 00
UtcDateTime   : 23/07/2020 03 37 00
LocalDateTime : 23/07/2020 13 37 00
Date          : 23/07/2020 00 00 00
Day           : 23
DayOfWeek     : Thursday
DayOfYear     : 205
Hour          : 13
Millisecond   : 0
Minute        : 37
Month         : 7
Offset        : 10:00:00
Second        : 0
Ticks         : 637311082200000000
UtcTicks      : 637310722200000000
TimeOfDay     : 13:37:00
Year          : 2020



PS C:\Windows\System32\WindowsPowerShell\v1.0> [Datetimeoffset]::Parse("13 37")
Exception calling "Parse" with "1" argument(s): "String was not recognized as a valid DateTime."
At line:1 char:1
+ [Datetimeoffset]::Parse("13 37")
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : FormatException

```

**Comment by Tyrrrz** [comment]
PowerShell will do. Looks like .NET doesn't know how to parse your time format :/

**Comment by xcasxcursex** [comment]
Trust me to be the one to find a bug in software used by billions XD

Oh well, at least it's not your job to fix it! Closed :)
