### ISSUE TITLE
Lightbulb is harder to run on Windows x86

### ISSUE THREAD

**Issue by tomasz1986** [Tyrrrz/LightBulb#172]
As of right now, Lightbulb is released as x64 binary only (see https://github.com/Tyrrrz/LightBulb/issues/145). As such, it does not run at all under Windows x86. The installer itself does run and install the software though, so it is only the `Lightbulb.exe` executable that fails to start.

Would it be a big hurdle to provide both x86 and x64 releases? This seems to be a standard procedure with most software, unless there is a specific reason for needing 64-bits only (e.g. RAM-heavy graphics/virtualisation software, etc.).

**Comment by mirh** [comment]
[<2](https://github.com/Tyrrrz/LightBulb/releases/tag/1.6.4) still works for the records. 
Anyway, there's not even need to make a double release. x86 is more than enough for what the program has to do here.

**Comment by Tyrrrz** [comment]
It _should_ be platform agnostic. Try running `dotnet LightBulb.dll` instead of running `LightBulb.exe` and see if it helps.

**Comment by tomasz1986** [comment]
> It _should_ be platform agnostic. Try running `dotnet LightBulb.dll` instead of running `LightBulb.exe` and see if it helps.


I can confirm that Lightbulb does start this way, which would mean that it is only the `Lightbulb.exe` executable that does not support 32-bit.

**Comment by Tyrrrz** [comment]
I think it's an oversight in .NET that the bootstrapper exe is only generated for x64. I'll add a note to the wiki and close this issue then.

**Comment by mirh** [comment]
Doesn't AnyCPU or x86 work for it?

**Comment by Tyrrrz** [comment]
No, the exe is native, it's not running on .NET.

**Comment by Tyrrrz** [comment]
Closing this as it's not something that can be fixed from this end. Wiki now has a troubleshooting entry for this issue. Hopefully upcoming versions of .NET will alleviate this issue.

**Comment by mirh** [comment]
Are you sure it's not https://github.com/dotnet/sdk/issues/6753?

**Comment by Tyrrrz** [comment]
No, we're not targeting .NET Framework.

**Comment by mirh** [comment]
I know, still the problem may be the same?

**Comment by Tyrrrz** [comment]
Looking at it, this issue was fixed. Plus .NET doesn't use package.json anymore.

**Comment by tomasz1986** [comment]
> Closing this as it's not something that can be fixed from this end. Wiki now has a troubleshooting entry for this issue. Hopefully upcoming versions of .NET will alleviate this issue.

I've been playing with this recently, and my suggestion would be to change the Wiki entry from

>If you're on a 32-bit version of Windows, launch LightBulb by going to its directory and running `dotnet LightBulb.dll` instead of running `LightBulb.exe`.

to

>If you're on a 32-bit version of Windows, launch LightBulb by going to its directory and running `start /b dotnet LightBulb.dll` instead of running `LightBulb.exe`.

The reason is that otherwise the command line window will have to stay open to keep LightBulb running, and closing it will result in terminating the program. On the other hand, using `start /b` detaches the process from the command line.

I'd do a PR myself, but GitHub doesn't seem to allow submitting PRs to wikis :roll_eyes:.

**Comment by tomasz1986** [comment]
> Closing this as it's not something that can be fixed from this end. Wiki now has a troubleshooting entry for this issue. Hopefully upcoming versions of .NET will alleviate this issue.

I've been playing around with this recently, and my suggestion would be to change the Wiki entry to recommend using PowerShell and run

```
Start-Process -FilePath "dotnet.exe" -ArgumentList "LightBulb.dll" -WindowStyle Hidden
```

The reason is that running just `dotnet LightBulb.dll` attaches the process to the command line window, which then has to stay open to keep it running, and there doesn't seem to be any way to change this behaviour. Closing the command line window results in LightBulb being terminated as well.

The PowerShell command above doesn't have this problem.

**Comment by Tyrrrz** [comment]
This is no longer necessary with latest version by the way

**Comment by tomasz1986** [comment]
> This is no longer necessary with latest version by the way

How so?

I've literally just tried to run the newest version under Windows 7 x86, but the result it

![image](https://user-images.githubusercontent.com/5626656/133895934-2a52d57f-2ef7-4670-b2d8-677f07919aa7.png)

so there's no difference here between today and July last year, at least for me. Running through `dotnet.exe` does still work though.
