### ISSUE TITLE
LightBulb turns off when Windows displays a notification

### ISSUE THREAD

**Issue by krehera** [Tyrrrz/LightBulb#174]
Windows 10 turns off LightBulb every time it shows a notification.

**Comment by Tyrrrz** [comment]
Try enabling gamma polling in settings to work around this.

**Comment by krehera** [comment]
Now it turns back on after half a second or so. but it still turns off for a brief moment.

**Comment by Tyrrrz** [comment]
Yeah, it's only a workaround. Some applications and even Windows itself may reset gamma randomly. In most cases there isn't a corresponding event we can listen to in order to reset it back, so the best bet is to periodically force-refresh gamma.
