### ISSUE TITLE
A deep problem

### ISSUE THREAD

**Issue by Giannes132** [Tyrrrz/LightBulb#175]
The "temperature" of the screen doesn't change, apparently it's the screen that's broken, the screen was hit and the brightness doesn't change after that, I have no idea how to fix it. Please can someone help me, maybe it's a way to fix the problem without repairing the screen itself or buying a new one. 

p.s. sorry for my English I am a foreigner

**Comment by Tyrrrz** [comment]
Does the screen otherwise work? I doubt it would selectively lose ability to change brightness.
Have you checked the troubleshooting tips here? https://github.com/Tyrrrz/LightBulb/wiki/Troubleshooting
