### ISSUE TITLE
Screen goes yellow-green when temp set to 500K

### ISSUE THREAD

**Issue by IGrayfoxI** [Tyrrrz/LightBulb#176]
I noticed this bug to night after trying to replicate f.luxs "darkroom mode" which sets the screen to a full red color.
By setting the color temperature down to 500K and I had a transition time of 0s

Everything is fine till it hits 505K or lower,as setting it to 505K  keeps the screen red.

If you were to slowly step down(slowly bringing the temperature down after the sunset transition multiple times) the temperature you can get it to 500K with out the screen going yellow.
![Screenshot 2020-09-18 22 25 50](https://user-images.githubusercontent.com/28896310/93597289-25d5cf00-f9fe-11ea-967e-614c4acdc397.png)
The picture is from a frame of video I caught of the bug happening

**Settings used.**
Sunrise temperature: 6500K
Sunset temperature: 500K
Transition Time: 0s
Day time brightness: 100%
Night time Brightness: 85%
Transition Offset: 0%

**Comment by Tyrrrz** [comment]
I'm very confused, what exactly were you expecting and what didn't meet your expectations?

I just tried setting it to 500K and it slowly transitions to saturated orange tint. No jumping and no red screen.

**Comment by IGrayfoxI** [comment]
https://www.dropbox.com/s/aw7wfpwtv656gul/VID.mp4?dl=0

**Comment by Tyrrrz** [comment]
Yeah, I think that's something specific to your drivers or the monitor. Can you test it on some other computer?

**Comment by IGrayfoxI** [comment]
Updated drivers.
Video card is GTX1080
I run triple monitors and it does the same thing on them all
Running Win8.1

I can try in LMDE4 tomorrow

**Comment by IGrayfoxI** [comment]
Had enough time today to test on my laptop which has on board graphics and is running windows 10.
Same thing happened with same color temp settings and transition time.
![IMG_20200926_143435](https://user-images.githubusercontent.com/28896310/94330288-8e2c3e00-0006-11eb-9011-6d4c8e2a623f.png)

**Comment by Tyrrrz** [comment]
Hm, weird. Does it change if you set the transition time to be above 0?

**Comment by IGrayfoxI** [comment]
Has not done it yet on 30seconds.
But if I use the hot key function of Toggle On/Off and I toggle it off then back on with in 2s it will do it most of the time.

**Comment by Tyrrrz** [comment]
Should be fixed now. You can try the downloads in the latest CI build: https://github.com/Tyrrrz/LightBulb/actions/runs/1191432271
