### ISSUE TITLE
First screen locked in night mode after turning off monitors for an long period of time

### ISSUE THREAD

**Issue by Nico207** [Tyrrrz/LightBulb#177]
Hi,

I have a problem with LightBulb on my PC which has two monitors.
LightBulb works perfectly, but in the evening if I turn off both screens (PC is not on standby), I find the next day LightBulb correctly displayed on the second screen, but it seems "blocked" in night display on the first screen.
After a click on the "Preview" button, (and wait the end of the preview) LightBulb works correctly again.

Thanks.

Windows 10 (1909)
LightBulb V2.2.0

**Comment by Tyrrrz** [comment]
Hi,
There are random things in Windows that just reset gamma for no reason.
You can also enable gamma polling in settings so that LightBulb automatically refreshes gamma every ~5 seconds, so that you don't have to do it yourself like you did.

**Comment by Nico207** [comment]
Enable gamma polling solved the problem.

Thanks !
