### ISSUE TITLE
Question about your installer

### ISSUE THREAD

**Issue by derech1e** [Tyrrrz/LightBulb#178]
Hey!
How did you prevent the installer from being recognized as a virus by Windows 10?

I have the issue that my Virus Programm and Windows block my installer exe. 

How did you managed that?

Thanks for your response!

**Comment by Tyrrrz** [comment]
Hey.
I didn't do anything special.

**Comment by Tyrrrz** [comment]
Actually, now I remember. I think at some point Windows Defender market it as a virus so I had to submit a claim and it was manually approved.
