### ISSUE TITLE
Provide signed installer releases

### ISSUE THREAD

**Issue by Abdull** [Tyrrrz/LightBulb#179]

**Comment by Tyrrrz** [comment]
Are you willing to sponsor the certificate?

**Comment by Abdull** [comment]
> Are you willing to sponsor the certificate?

Maybe my donation can help a little towards this. :)

I guess the following links are helpful to find a cheap or even free certificate:

* https://stackoverflow.com/questions/1177552/code-signing-certificate-for-open-source-projects
* https://www.msz.it/a-cheap-code-signing-certificate-for-open-source-projects-by-certum-asseco-an-honest-review-walkthrough/

( ... nevertheless, thank you very much for LightBulb - it's awesome to dim my overly bright computer screen ... )

**Comment by Tyrrrz** [comment]
Thanks, I'll look into it. I was under the impression the certificate was quite expensive.

**Comment by Tyrrrz** [comment]
I finally looked into it, still seems unviable. There are no free certificate options for open source projects, as of today – and the cheapest ones are around $90-150 a year, which is still quite costly. Given that LightBulb is downloaded only about 40k times per year (with ~50% of that being auto-updates), I don't think it's worth the effort, unfortunately. Closing as out of scope.
