### ISSUE TITLE
Performance improvements

### ISSUE THREAD

**Issue by Tyrrrz** [Tyrrrz/LightBulb#182]
Try to reduce CPU usage

**Comment by ArchBacon** [comment]
On my pc it is mostly on 0% usage and sometimes goes 0.1% for at most a second. What are your usage readings?
Based on that it might or might not be worth looking into this.

**Comment by sergeevabc** [comment]
Err… 2–3% CPU and 100 MiB RAM. 

>Minimal performance impact

You’re [serious][1]? :)

[1]: https://www.youtube.com/watch?v=etBufTl7slc

**Comment by sergeevabc** [comment]
![30 seconds of process monitoring](https://i6.imageban.ru/out/2021/03/09/865775ed1d48a280c92caecaa4daf4fa.png)[1]

[1]: https://files.catbox.moe/791ydw.mp4

**Comment by Tyrrrz** [comment]
Closed in favor of #248
