### ISSUE TITLE
Unlock extended gamma range

### ISSUE THREAD

**Issue by Louartan** [Tyrrrz/LightBulb#184]
Hi! Not an issue, more a question: what does "unlock gamma range" do on windows 10 (v. 2004)? Is it a registry edit? Can it be reversed?
Thanks

**Comment by Tyrrrz** [comment]
Hi! Yes, it's a registry edit.

It sets this key to `256`:

https://github.com/Tyrrrz/LightBulb/blob/e15bd6dfd3b657c0b10758b689eb911c120a06f5/LightBulb/Services/SettingsService.cs#L15-L19

You can reverse it simply by deleting it AFAIK, it will restore the default state.

**Comment by Louartan** [comment]
Thanks a lot!
