### ISSUE TITLE
Virus engine problem

### ISSUE THREAD

**Issue by ShimonShore** [Tyrrrz/LightBulb#185]
Great Program. In order to get approval for the use of your program we have passed it through the virus checking site VirusTotal (https://www.virustotal.com/gui/). 

The installation fails and is marked as malware on 5 of the testing sites. 

Any idea why that is?

**Comment by Tyrrrz** [comment]
Not sure, I just checked and it reports 0/82 on both installer and portable:

![image](https://user-images.githubusercontent.com/1935960/101672486-966d1480-3a5e-11eb-9254-24f54b22ff8f.png)

https://www.virustotal.com/gui/url/df96e9076722ac5831d15767524f8324e27a66c52d060e89671ab7ecd0cfe8be/detection

![image](https://user-images.githubusercontent.com/1935960/101672506-9c62f580-3a5e-11eb-88bb-4857df9b5aae.png)

https://www.virustotal.com/gui/url-analysis/u-3bd490bc83f4dacfb5c145165cc569b0e88d476745ab9c3506bc7b007b460e8a-1607539118/detection

**Comment by natanielf** [comment]
Looks like when you upload the latest release .exe it is flagged with malware (4 engines detected), but copying and pasting the download link gives you 0/82 found. The .zip comes back clean when uploaded though.

Uploading the installer gives this:

<img width="938" alt="chrome_muBrKfBvWW" src="https://user-images.githubusercontent.com/49921489/101677018-da392d00-3a10-11eb-8dfb-1357228dba7d.png">

**Comment by Tyrrrz** [comment]
In that case, I recommend using the portable installation if those security warnings are a concern.
