### ISSUE TITLE
Applying folder view to all folders completely disable LightBulb

### ISSUE THREAD

**Issue by weiwang11** [Tyrrrz/LightBulb#186]
When applying folder view to all folders, it completely disable LightBulb and making any changes within the application doesn't do anything until you use the reset button.

Steps to Reproduce:

1. Go to a folder like Documents
2. Click on View on Explorer's ribbon tab and Options to open Folder Options
3. Click on View
4. Click on Apply to Folders
5. Screen resets to default settings and adjusting LightBulb settings again doesn't do anything until you reset.

Sample size is currently only my machine, I'm not sure if this is applicable to others.

**Comment by Tyrrrz** [comment]
That's weird, could you try a CI build?
https://github.com/Tyrrrz/LightBulb/actions/runs/423621177

**Comment by weiwang11** [comment]
I just realized that I was still running on v2.0.0. I updated to the latest version and it doesn't appear to be happening. I'll just close this seeing as I can't reproduce it on the latest version.

Also is it possible to add to the README where the config file is located? I thought it was the Settings.json file in LightBulb's install directory but replacing it with my own backup file doesn't appear to do anything.

**Comment by Tyrrrz** [comment]
@weiwang11 it depends on whether you're using an installed distribution or portable. For portable, it's in the same directory, but for installed it's in `%appdata%/LightBulb`.

**Comment by weiwang11** [comment]
@Tyrrrz Thanks! Also may I ask if the package on chocolately can be updated? I've been using chocolatey for majority of my programs and it makes managing the them easier.

**Comment by Tyrrrz** [comment]
@weiwang11 Chocolatey deployments got annoying to orchestrate properly in CD, so I stopped doing them. There is, however, a WinGet package that is maintained by the community: https://github.com/microsoft/winget-pkgs/tree/master/manifests/Tyrrrz/LightBulb

If someone also wants to take Chocolatey over, I can give the publishing rights to the package (assuming it's possible, I don't know).
