### ISSUE TITLE
Hello author, can you add a multilingual version?

### ISSUE THREAD

**Issue by liuzxdp** [Tyrrrz/LightBulb#187]
Hello author, can you add a multilingual version?

**Comment by roxfr** [comment]
Hi,
Could you make this app translatable, please.
Thank you.
Regards,
Roxfr

**Comment by roxfr** [comment]
RootView.xaml

> 
> 
> Hello author, can you add a multilingual version?

Apparently, it is the "RootView.xaml" file that should be translated.

**Comment by Tyrrrz** [comment]
Duplicate of #45.
I see this is a quite often requested feature, I'll see what I can do.

**Comment by roxfr** [comment]
> Duplicate of #45.
> I see this is a quite often requested feature, I'll see what I can do.

Great ! Thank you very much for this application which saves my life or rather my eyes ;-) because the night lighting system of Windows 10 is crashing !

**Comment by Tyrrrz** [comment]
@roxfr you're welcome 🙂
