### ISSUE TITLE
Make a way of temp 'fast forwarding' to lower light without having to go into settings to change sunset

### ISSUE THREAD

**Issue by ProfessorRich** [Tyrrrz/LightBulb#189]
The option to right-click and disable in the icon bar is really useful if I'm working late. How about if I want to wind down early?

It's be great if you could also right-click and 'begin sunset today' or something like that, which would bring forward the sunset - but only for today (so goes back to whatever is in settings the next day.

**Comment by Tyrrrz** [comment]
Have you tried offset hotkeys? You can set hotkeys to add temperature/brightness offset to your current settings to temporarily increase or decrease them. The offsets are not persisted between sessions.

If you find that you want to regularly wind down early, I recommend setting the sunset manually to match your schedule.
