### ISSUE TITLE
Why remove brightness hotkeys?

### ISSUE THREAD

**Issue by dragons4life** [Tyrrrz/LightBulb#19]
Are they going to be added again?

**Comment by Tyrrrz** [comment]
The brightness hotkeys were added briefly in upstream but I didn't like how they fit the workflow so I removed them. I was thinking of eventually adding Daytime Brightness and Nightime brightness eventually to replace them.

**Comment by Tyrrrz** [comment]
If you have a specific reason or usecase for brightness hotkeys or brightness manipulation in general, you can voice it over. Frankly, I think they are pretty useless.

**Comment by dragons4life** [comment]
I mean, I mostly use it because sometimes my monitor is a bit too bright making it uncomfortable to read at night.

Yes I can change it trough my monitor settings, but well it's honestly tedious compare to something like a hotkey on a keyboard.

**Comment by Tyrrrz** [comment]
So, assuming there are hotkeys, how often times a day do you change the brightness? Do you set it high during the day and then lower at night? Or do you usually find yourself using the same brightness for prolonged amount of time?

**Comment by dragons4life** [comment]
Most of the time I lower it during the night, or when I have no light on my room. (at least 2/1 times a day)

**Comment by Tyrrrz** [comment]
Would it be more useful if brightness was set automatically, on a time basis? Just like color temperature is now.

**Comment by dragons4life** [comment]
I mean having it in a keybind to easily choose the amount you want or don't want would be good enough imo.
