### ISSUE TITLE
Let sunset be controllable by the sun while sunrise is a fixed time

### ISSUE THREAD

**Issue by mfbehrens99** [Tyrrrz/LightBulb#190]
Hi there,

I have a feature request. When I wake up in Winter and start to work at about 6:30 it is still two to three hours until sunrise. When I am still tired and my monitor is still in these warm colours it doesn't let me work very productively.

To fix this issue I could switch to manual. However, I still want the sun to control the sunset time.

Is it possible to add an option where I can select a sunrise time and leave the sunset on automatic?

That would really help me
Best,
Michael

**Comment by Tyrrrz** [comment]
You can play around with transition offset and transition duration. It's not the same but maybe it will help achieve what you want?
https://github.com/Tyrrrz/LightBulb/wiki/How-the-transition-offset-works
