### ISSUE TITLE
Colors become oversaturated during sunset transition at 1900K

### ISSUE THREAD

**Issue by boromyr** [Tyrrrz/LightBulb#191]
Hi, every night during the transition the screen shows wrong colors for 10-20 seconds, like when you bring contrast and saturation to the maximum. The irony is that just as I am typing this message, I go looking for the screenshot showing the problem, only to find that it displays the desktop colors correctly. Even some previous screenshoots fail to highlight the problem.
![Screenshot (222)](https://user-images.githubusercontent.com/52782032/107274003-1fe59680-6a50-11eb-8517-d9e0db405621.png)This should show the problem, but it actually looks good. The problem occurs at the same time.

**Comment by Tyrrrz** [comment]
Possibly related to #176?
Does it flash or stay like this for a while?

**Comment by boromyr** [comment]
No, I don't think so, from the photos it seems to be a uniform problem, in my case the error seems to depend on the underlying colour. Not being able to take a screenshot, I took a classic Windows 10 screen and applied some filters, pushing a lot on saturation.

![windows-10-14328-580797c43df78cbc285096a1](https://user-images.githubusercontent.com/52782032/108555701-200a4f80-72f6-11eb-87c6-d566ad240335.png)
Here, something like that.
By the way, my video card is an Nvidia GeForce MX150. I thought I'd try uninstalling the driver when a new update comes out, and check if the problem persists.

**Comment by Tyrrrz** [comment]
It happens at around 1900K and then when it drops lower than that it becomes normal again? Hm, that's weird.

**Comment by Tyrrrz** [comment]
Should be fixed now. You can try the downloads in the latest CI build: https://github.com/Tyrrrz/LightBulb/actions/runs/1191432271

**Comment by mirh** [comment]
Uh, thanks goodness. Cool.

**Comment by boromyr** [comment]
Yes everything is working properly now. Thank you.
