### ISSUE TITLE
Will this interfere with my monitor's display calibrations (.icc's)?

### ISSUE THREAD

**Issue by nesherman** [Tyrrrz/LightBulb#192]
Flux overrides my monitor's .icc color profile and so I am looking for an alternative. I am looking for something that will simply change the color temperature of my monitor without overriding my set color values during the daytime.

I rely on color accuracy while working in the photography and design industries, however, I still use my machine leisurely and am hoping to find software that will allow me to retain my monitor's color calibration while the program is set to 6600K. I realize this is a niche question/preference, but I do very much appreciate your time. Have a great day.

**Comment by Tyrrrz** [comment]
Yes, most likely. Possibly related to #44.
