### ISSUE TITLE
Command line settings or additional shortcuts

### ISSUE THREAD

**Issue by Baccanno** [Tyrrrz/LightBulb#194]
Can we affect Light bulb settings through cli ?
I'd like to be able to have a light down instantly to 10% (Could We go like 5% as well ?)

Best

**Comment by Tyrrrz** [comment]
You can use the offset hotkeys to bring the brightness down temporarily.
CLI and additional hotkeys will not be added.

**Comment by Baccanno** [comment]
Alright, it works though, Thanks
