### ISSUE TITLE
Lightbulb doesn't change the hue and brightness throughout the day

### ISSUE THREAD

**Issue by UntitleDude** [Tyrrrz/LightBulb#195]
Hi !

I've been using this software for a couple of months and nether had any issue. Great tool, I've loved it so far.
However, I've came across a blunder since the last windows update (yeah I know, fuck windows). Version	10.0.19042 Build 19042, last updated today (03/13/21).

To sum up, the software doesn't change the color and the brightness as configured in the settings. Once started with windows or manually, it doesn't change automatically. I had a gamma message as described in #184 but even activated, the bug still appears. I've downloaded the latest version (2.3.0) with no success either... I hope someone can point me out if I made a mistake or if encountering the same problem as me

Thanks for the reading !

**Comment by Tyrrrz** [comment]
Can you try the last CI build?

**Comment by UntitleDude** [comment]
I don't know how to download it as it says the artifacts have expired.
I'm usually using the .exe installer on windows

**Comment by Tyrrrz** [comment]
Sorry about that. This should link to non-expired builds:
[`LightBulb.zip`](https://github.com/Tyrrrz/LightBulb/suites/2265222947/artifacts/47203633)
[`LightBulb-Installer.zip`](https://github.com/Tyrrrz/LightBulb/suites/2265222947/artifacts/47203634)

**Comment by UntitleDude** [comment]
It works ! Thanks a lot for the help. Still don't know why the installer with the same version didn't work previously, but that's fine.
Have a great one, and thanks for the awesome software ! :)
