### ISSUE TITLE
Latest update causes audio and system stuttering

### ISSUE THREAD

**Issue by ARDEACT** [Tyrrrz/LightBulb#199]
I've been trying to find out what was causing my audio to stutter so suddenly, also my monitor frames would stutter too. I then remembered the only thing I did to my system was update Lightbulb, turns out, exiting it fixed everything. I don't what this update did but it really messes up windows.

**Comment by josephyunzz** [comment]
I'm having the same exact issue too. I'm on Windows 10 20H2 with Ryzen 7 3700x / RTX 2070 Super in case that's anything worth noting.

**Comment by Tyrrrz** [comment]
Looks like it's the same issue as #198 
Going to consolidate the discussion there
