### ISSUE TITLE
Set sunset to occur during night-time

### ISSUE THREAD

**Issue by Tyrrrz** [Tyrrrz/LightBulb#20]
From [this](http://disq.us/p/1hc59pl) comment discussion.
Screenshot of the relevant part:
![2017-04-06 10_54_50-alexey golub - lightbulb](https://cloud.githubusercontent.com/assets/1935960/24743590/7d05487a-1ab7-11e7-9930-a3a88b5f2ea7.png)

**Comment by taxen** [comment]
Sunset time can be set no later than 22:00 right now. Can you make it even later than that, like 1:00 am or even 5:00 am (later the better because I am quite nocturnal)? I know it does not make sense, thinking about what it does.

**Comment by taxen** [comment]
Thank you for the latest update!
It now works as I desired before.
