### ISSUE TITLE
Autoupdate installed latest update despite it being tagged as pre-release

### ISSUE THREAD

**Issue by KovalevArtem** [Tyrrrz/LightBulb#200]
Despite:

> ⚠️ Some users have reported severe performance degradations introduced in this release: #197 #198 #199.
> As a temporary solution, this release has been marked as "pre-release" to **prevent autoupdate** from installing this version.
https://github.com/Tyrrrz/LightBulb/releases/tag/2.3.1

When I turned on the PC, the application suggested installing an update today. I did it...
![image](https://user-images.githubusercontent.com/36500228/111960258-902c1100-8b00-11eb-8798-496965b59894.png)

**Comment by Tyrrrz** [comment]
@KovalevArtem
LightBulb downloads the updates immediately, but installs them on the next startup. So it's likely it downloaded it yesterday, but only installed it now. I marked 2.3.1 as pre-release only about 5 hours ago.

**Comment by eberhardweber** [comment]
This very thing happened to me and performance was definitely reduced - audio became choppy etc.
