### ISSUE TITLE
Gamma range not unlocking (2.3.1 vs 2.3.0)

### ISSUE THREAD

**Issue by Ithiloneth** [Tyrrrz/LightBulb#201]
Hello and thanks for a great program!

I was updated to 2.3.1 some time ago and all was fine. I then installed the 20H2 update for Windows and on next start LightBulb gently informed me that the gamma range had been locked.
Selecting OK to unlock it appears to not have worked, for the gamma range was significantly less than it had been.
To clarify this, I used to be able to turn the screen almost black and almost fully red. Now only minor shifts were possible.

Due to another, hopefully unrelated issue, I had to reinstall Windows and chose to update it fully afterwards. The problem with 2.3.1 persisted so I have now downgraded manually to 2.3.0.
Aside from input lag (other issue is tracking that already) while the options screen is open, things are back to normal!

Worth pointing out is that I had given the OK for extended gamma range via 2.3.1 before downgrading.

**Comment by Tyrrrz** [comment]
Hi.
Did you restart your computer after unlocking the gamma range? I'm not sure if it's actually necessary, but it could be.
Other than that, I believe there were no changes in regarding to gamma range between 2.3.0 and 2.3.1 so it's weird it works properly in one but not in the other.

**Comment by Ithiloneth** [comment]
Before the Windows reinstall:
I think I did at least one reboot with the issue persisting, but I am not sure.

After the Windows reinstall:
Yes; there was at least one restart through which the gamma issue persisted.

Would it be helpful if I downloaded 2.3.1 portable and checked if the issue still persists for me?

**Comment by Tyrrrz** [comment]
> Would it be helpful if I downloaded 2.3.1 portable and checked if the issue still persists for me?

Yes please

**Comment by Ithiloneth** [comment]
Reproduction has failed; 2.3.1 can now reach the full ranges for both brightness and temperature.
Maybe my issue was not caused by LightBulb but something else? Though I am unsure what that would be what with the Windows reinstall.

Issue closed?

**Comment by Tyrrrz** [comment]
@Ithiloneth it's really hard to guess what was the original culprit, especially since there were windows reinstalls in between.
The good thing is it works :)
