### ISSUE TITLE
Hotkeys removed after update

### ISSUE THREAD

**Issue by hazer-hazer** [Tyrrrz/LightBulb#202]
Hi, after recent update I remembered an issue that after any update all shortcuts are removed.
It wouuld be very nice if you'll solve you. Maybe you can store `.json` config or something, or maybe I'll solve it myself.
Thank in advance.

**Comment by Tyrrrz** [comment]
Is it just the hotkeys or all settings? Does it also happen if you just reinstall the latest version?
