### ISSUE TITLE
Screen flickers when wallpaper changes

### ISSUE THREAD

**Issue by michalsieron** [Tyrrrz/LightBulb#206]
### Version

2.3.1

### Details

When I have LightBulb enabled, changing wallpaper (manually or by slideshow) makes the screen flicker momentarily.
I have LightBulb installed from [this CI build](https://github.com/Tyrrrz/LightBulb/issues/198#issuecomment-827673586), but it flickered with previous CI build too (v2.3.1, but don't know which one it was). 
Also it works correctly on v2.3.0.

CPU: i5-8300H
GPU: GTX 1050 Ti

### Steps to reproduce

1. Enable LightBulb 2.3.1
2. Change wallpaper
3. Screen flickers

**Comment by Tyrrrz** [comment]
If the screen flickers, it most likely means that gamma was changed by some other program or that the screen handle was invalidated. When you change wallpaper, it's likely that Windows resets the handle or just restores gamma as precaution. Are you sure there was no flicker in v2.3.0? This behavior should have been around for a while now.

**Comment by michalsieron** [comment]
Yeah, I installed v2.3.0 yesterday. Right now, just to check, I set temperature to 3400 K and changing wallpaper works correctly.

**Comment by gannon345** [comment]
I'm seeing the same behavior since the latest update. I have my desktop wallpaper set to rotate every 60 minutes and whenever it changes the screen flickers brightly twice at the transition.

**Comment by gannon345** [comment]
Just rolled back to 2.3 (was on 2.3.3) based on michalsieron's comment, and sure enough, the flickering is gone. Definitely some kind of regression.

**Comment by Tyrrrz** [comment]
Found the regression and fixed it, sorry about that 🙂 
You can try latest CI build: https://github.com/Tyrrrz/LightBulb/actions/runs/947181821
