### ISSUE TITLE
Latest 'Microsoft Windows Desktop Runtime' is not recognized

### ISSUE THREAD

**Issue by Shakil-Shahadat** [Tyrrrz/LightBulb#207]
### Version

2.3.2

### Details

I have version 5.0.5 of 'Microsoft Windows Desktop Runtime' installed. Instead, it prompted me to install 3.1.0. I think it should work with the latest versions of 'Microsoft Windows Desktop Runtime'.

And this dependency check should be done while installing the app too.

Also, while requiring the dependency it says 'Microsoft.WindowsDesktop.App' which is a little confusing to understand what it is.

### Steps to reproduce

Install & run the app.

**Comment by jantheodor** [comment]
Doesn't work for me as well. Everytime I try to launch LightBulb, the following happens:
1. Missing dependencies [https://abload.de/img/lightbulb1v3yajyj.jpg](url)
2. Downloading Microsoft.WindowsDesktop.App 3.1.0 [https://abload.de/img/lightbulb2v3eskgc.jpg](url)
3. Admin privilege request window [https://abload.de/img/lightbulb3v3q2j2h.jpg](url)
4. Nothing happens. LightBulb has not been started.

**Comment by Shakil-Shahadat** [comment]
Do you see 'Microsoft Windows Desktop Runtime - 3.1' on the windows uninstall programs page?

**Comment by LightShaft** [comment]
I had the exact problem, Shakil-Shahadat response was helpful : I went to the list of programs, searched for Microsoft Windows Desktop Runtime, and I had 2 versions installed : one that was like 3.1.15 or something, and one that was 5. something too.
I uninstalled both and launched lightbulb, now it works properly.

**Comment by jantheodor** [comment]
> Do you see 'Microsoft Windows Desktop Runtime - 3.1' on the windows uninstall programs page?

Yes I do. 1) https://abload.de/img/uninstallprogramms1v2u3jdk.jpg 2) https://abload.de/img/uninstallprogramms2v2fvkfj.jpg

**Comment by jantheodor** [comment]
> I uninstalled both and launched lightbulb, now it works properly.

Didn't work for me *shouldershrug*.

**Comment by Shakil-Shahadat** [comment]
> > I uninstalled both and launched lightbulb, now it works properly.
> 
> Didn't work for me _shouldershrug_.

@jantheodor You mean, you now have only 3.1 and not the other two 3.0.1 versions, right? LightBulb needs 3.1 to work properly. The other two versions might have caused the problem.

@LightShaft Did you restart the system yet? LightBulb needs at least version 3.1 to work properly.

**Comment by jantheodor** [comment]
> @jantheodor You mean, you now have only 3.1 and not the other two 3.0.1 versions, right? LightBulb needs 3.1 to work properly. The other two versions might have caused the problem.

After reading LightShafts comment, I have uninstalled all versions. Launched LightBulb again, which than did install Version 3.1. And ended with the same issue https://github.com/Tyrrrz/LightBulb/issues/207#issuecomment-857677300.

**Comment by Tyrrrz** [comment]
Hi! Sorry for the issue, I've introduced the bootstrapper in the latest release to help with installing the runtime, but it might still have some rough edges.

> I have version 5.0.5 of 'Microsoft Windows Desktop Runtime' installed. Instead, it prompted me to install 3.1.0. I think it should work with the latest versions of 'Microsoft Windows Desktop Runtime'.

Runtimes are only compatible within the same major version. .NET 3.x and .NET 5.x are not compatible with each other unfortunately. I will update LightBulb to .NET 6.x later this year when it's released so that it will target the latest version of the framework.

> And this dependency check should be done while installing the app too.

The goal is to make the process work the same in both the installed version and the portable version, so that there won't be duplicated/repeated logic.

> Also, while requiring the dependency it says 'Microsoft.WindowsDesktop.App' which is a little confusing to understand what it is.

This will be fixed in the next release :)

@jantheodor

> Nothing happens. LightBulb has not been started.

Does the bootstrapper close immediately after you confirm admin privileges? Or does it continue showing indeterminate progress for a while?

Can you also go to the directory where LightBulb is, start a command prompt, and then run `dotnet LightBulb.dll` (note the `dll` instead of `exe`). Does it work or does it produce an error message of some sort?

**Comment by Shakil-Shahadat** [comment]
@Tyrrrz Thank you so much for the reply and for the very useful app.

**Comment by jantheodor** [comment]
> Does the bootstrapper close immediately after you confirm admin privileges? Or does it continue showing indeterminate progress for a while?

Yepp. It does close immediately.

> Can you also go to the directory where LightBulb is, start a command prompt, and then run `dotnet LightBulb.dll` (note the `dll` instead of `exe`). Does it work or does it produce an error message of some sort?

Having done so. Here is what happened https://abload.de/img/commandpromptrkjaj.jpg. As you can see, I have it installed https://abload.de/img/mwdrinstalledsuccessf1ykad.jpg. So the detection, seems to fail here.
 
> Also, having multiple runtimes installed shouldn't cause any issues, as long as the required one is also installed. I would like to investigate that more if someone has extra information.

Yepp. True. Just felt like trying, for the sake of it 😁

**Comment by Tyrrrz** [comment]
@jantheodor if you try launching `LightBulb.exe` does it attempt to install .NET Runtime again every time?

**Comment by jantheodor** [comment]
> @jantheodor if you try launching `LightBulb.exe` does it attempt to install .NET Runtime again every time?

Yepp!

**Comment by Tyrrrz** [comment]
@jantheodor that's really weird, looks like somehow it wasn't installed properly. If you run `dotnet --list-runtimes` does it include that version? Did things work fine with the previous LightBulb version or is this the first time you trying it?

**Comment by jantheodor** [comment]
> @jantheodor that's really weird, 

Yeah it is.

> looks like somehow it wasn't installed properly. If you run `dotnet --list-runtimes` does it include that version? 

It does https://abload.de/img/commandprompt2f9k0b.jpg. 

> Did things work fine with the previous LightBulb version or is this the first time you trying it?

Been using LightBulb for quite some time now. Can't recall any such issues beforehand.

**Comment by Tyrrrz** [comment]
That's `3.0.1` though, LightBulb requires `3.1.x` starting with this last release (this is also probably why it worked for you before).

**Comment by jantheodor** [comment]
> That's `3.0.1` though, LightBulb requires `3.1.x` starting with this last release (this is also probably why it worked for you before).

See https://github.com/Tyrrrz/LightBulb/issues/207#issuecomment-857728651. According to windows uninstaller and geek uninstaller 3.1 is installed. Yet command prompt (dotnet --list-runtimes) says 3.0.1. Really odd. I have tried a full reinstall now. Same result. Switching back to 2.3 works without any issues.

**Comment by Tyrrrz** [comment]
You are on x64 bit OS, right? I'm asking because in a previous comment (https://github.com/Tyrrrz/LightBulb/issues/207#issuecomment-857697225) there was a screenshot where you had both x86 and x64 versions of .NET 3.0.1.

**Comment by jantheodor** [comment]
Yes that's right.

**Comment by Tyrrrz** [comment]
Nice that it's working! Something really weird must have happened during installation that the runtime wasn't getting resolved by `dotnet --list-runtimes`, but I have no idea what could have caused it :/ Although I believe it wasn't bootstrapper who was at fault, but either .NET Runtime's installer or something else entirely. Could also be that having both `x86` and `x64` installations had it confused and maybe running `dotnet` resolved to the `x86` version instead of the `x64`.

**Comment by Tyrrrz** [comment]
Going to close the issue as the questions have been answered and the suggestions were implemented
