### ISSUE TITLE
Color Temp. lower than 2500K is not supported in settings.

### ISSUE THREAD

**Issue by Shakil-Shahadat** [Tyrrrz/LightBulb#208]
### Version

2.3.2

### Details

I can set a color temp. below 2500K in the 'Settings.json' file but the color temp. slider in the app settings does not allow to change range below 2500K. When I try to move the slider, it jumps to 2500K.

### Steps to reproduce

1. Change color temp. to below 2500K in 'Settings.json'.
2. Move color temp. slider in the settings.

**Comment by Tyrrrz** [comment]
The slider doesn't, but you should be able to type in the desired value directly.

**Comment by Shakil-Shahadat** [comment]
Oh, I see now. I changed that value before and pressed enter but nothing happened. I have to click somewhere else or click save after changing the value. That's workable.

Is it possible to change the minimum value of the slider to a lower value than 2500K permanently? I understand this is a feature request. At least if you point me in the right direction I can try to do it myself.

Thanks.

**Comment by Shakil-Shahadat** [comment]
I have found the value in `LightBulb/Views/Components/Settings/GeneralSettingsTabView.xaml`. Changed the value to 1000 and it worked perfectly.

Thanks a lot for the app.
