### ISSUE TITLE
.NET Runtime prerequisites detection fails

### ISSUE THREAD

**Issue by Fourmisain** [Tyrrrz/LightBulb#209]
### Version

2.3.2

### Details

I have a Windows 7 machine that I always used LightBulb on, but with update 2.3.2, the new prerequisites check gives this:
![prerequisites](https://user-images.githubusercontent.com/8464472/121351309-e94f5800-c92b-11eb-9756-851b635a1873.png)

I tried installing it automatically, which failed, I downloaded the KBs and tried installing them manually and it just says that the updates are "not applicable".
After some googling, it seems those updates might be superseeded, which would explain why they cannot be installed - but then, if the replacement KBs are already installed, why does the dependency check list the old ones?

I never had any issues running LightBulb (and I do have the newest .NET Framework and Core Desktop Runtime installed).
It seems that this dependency check cannot currently be skipped, as the "Cancel" button just exits the program.

For the time being I'll switch back to 2.3, as this version works just fine.

### Steps to reproduce

 - Be on an old Win7 machine
 - Observe the .NET prerequisites detection trying to install some KB updates
 - Those updates cannot be installed
 - LightBulb cannot be used because the prerequisites detection cannot be skipped

**Comment by Tyrrrz** [comment]
Sorry about the issue! I've introduced the bootstrapper in the latest version to make installing .NET Runtime easier for users.

> After some googling, it seems those updates might be superseeded, which would explain why they cannot be installed - but then, if the replacement KBs are already installed, why does the dependency check list the old ones?

That's most likely the reason. I tested it on a clean Windows 7 install, but haven't considered that these updates might be superseded by some other ones. I'll look into how to fix this.

Thanks!

**Comment by Tyrrrz** [comment]
Could you please run `wmic qfe list` in a command prompt? This should give a list of updates installed on your system, which will help me better understand what were the original updates superseded by.

It should look something like this (I'm on Win10 though):

![image](https://user-images.githubusercontent.com/1935960/121395111-e726d280-c906-11eb-9e62-3a811f7740a2.png)

**Comment by Fourmisain** [comment]
I trimmed it down and put it on [hastebin](https://hastebin.com/asemivihah.text).

**Comment by Tyrrrz** [comment]
According to what I found on the internet, `KB3154518` seems to be superseded by `KB3125574`, while `KB3063858` appears to be superseded by `KB3068708`. However, it appears your system has none of the above mentioned updates.

**Comment by Fourmisain** [comment]
Huh, I do remember removing KB3068708 because it's a [pure telemetry update](https://support.microsoft.com/en-us/kb/3068708).
No idea why KB3125574 isn't installed though. It's a roundup update, so maybe it wasn't found to be necessary?

Either way, I just installed both of them, but I still get the exact same message.
I also tried installing the original 2 KBs again, to no avail.

**Comment by Tyrrrz** [comment]
I just booted a fresh Windows 7 on a VM and did the following:

- Installed KB3020369 (it's a prerequisite for KB3125574, as mentioned [here](https://msfn.org/board/topic/175618-convenience-rollup-update-for-win-7-sp1))
- Installed KB3125574
- Installed KB3068708
- All of the above updates are listed when running `wmic qfe list`
- Attempted to run the application
- It reported that KB3154518 and KB3063858 were missing (as expected, same as in your case)
- Installed missing components
- Restarted Windows
- Attempted to run the application again
- This time it claimed that only KB3063858 was missing (KB3154518 was evidently installed correctly)

So the conclusion for this is that KB3125574 does not actually supersede KB3154518 or at least both can be installed together. KB3068708 does appear to supersede KB3063858. However, in your case, neither KB3125574 nor KB3068708 are listed.

Regarding KB3125574, it could be that there is another update that supersedes KB3154518, which is included in that rollup, but you had it installed separately. Regarding KB3068708, I have absolutely no clue what could have happened.

I think it's not practical trying to figure out what supersedes what and instead I'm considering to put an "Ignore" button that you could click to override the prerequisites checks altogether.

**Comment by Tyrrrz** [comment]
@Fourmisain @dekvas

Please try the latest CI build and let me know if it works for you:
https://github.com/Tyrrrz/LightBulb/actions/runs/934309453

Note that the next time you run LightBulb, it might still claim that those updates are missing. However, after you go through the installation process it should not do it again.

**Comment by Fourmisain** [comment]
This seems to work just fine!
Pressing Ignore is kinda pointless since it'll ask the next time around, but pressing Install did permanently disable the check as you said.
(Also, on a side note, this time it only complained about KB3063858 just like in your testing, looks like I might have needed a few more restarts.)

One thing I noticed though is that it doesn't seem to recognize existing settings on first launch.
I can reproduce this by uninstalling (seeing that Settings.json is still under AppData\Roaming\LightBulb), reinstalling and launching it.
I get greeted by this
![firstlaunch](https://user-images.githubusercontent.com/8464472/121933029-d383cd80-cd45-11eb-9e17-9d22f83d3c2f.png)
and all settings are reset.

**Comment by Tyrrrz** [comment]
> (Also, on a side note, this time it only complained about KB3063858 just like in your testing, looks like I might have needed a few more restarts.)

Hmm, interesting. It would still be nice to figure out what supersedes KB3063858 on your computer, but you have too many updates to reasonably go through all of them 😅 

> One thing I noticed though is that it doesn't seem to recognize existing settings on first launch.
I can reproduce this by uninstalling (seeing that Settings.json is still under AppData\Roaming\LightBulb), reinstalling and launching it.
I get greeted by this

Just curious, if you exit LightBulb after it welcomes you with that popup and start it again -- does it find the settings correctly?
Also, if you go to LightBulb's installation directory, is there a file called `.installed`?

![image](https://user-images.githubusercontent.com/1935960/121938784-196a7280-cd01-11eb-8f29-4fdc5b03c320.png)

**Comment by Fourmisain** [comment]
Oh, I think the issue is actually super simple: uninstalling deletes the AppData\Roaming\LightBulb directory.

I was getting confused because I previously had a symlink to that directory, which is why I thought the settings were still there when the symlink was in fact deleted.

When I uninstall, put back the LightBulb folder and Settings.json file and reinstall, everything is read correctly (and there's no welcome dialog).

(Also, to answer your question, installing does put the `.installed` file.)

**Comment by Tyrrrz** [comment]
@Fourmisain Awesome. So I gather that means everything is working now? :)

**Comment by Fourmisain** [comment]
> So I gather that means everything is working now?

Yep!

> I completely forgot that uninstall deletes settings, but yeah it does

It shouldn't imho, it's really uncommon for software to delete it's config when uninstalled.

> And as for `.installed` (...)

Yeah, I thought as much.
At the beginning I was wondering why I had a Settings.json in the install directory too, I must have manually put a portable installation there previously, that added to the confusion too.

**Comment by dekvas** [comment]
>@dekvas
> 
> Please try the latest CI build and let me know if it works for you:
> https://github.com/Tyrrrz/LightBulb/actions/runs/934309453
> 
> Note that the next time you run LightBulb, it might still claim that those updates are missing. However, after you go through the installation process it should not do it again.

Yes, it worked
Thanks for such operational treatment. :)

**Comment by Tyrrrz** [comment]
Great!
