### ISSUE TITLE
Extend temperature range

### ISSUE THREAD

**Issue by mirh** [Tyrrrz/LightBulb#21]
F.lux can go as down as 1200k. 
2500 feels so daytime basically.

**Comment by Tyrrrz** [comment]
The temperature ranges are limited in GUI for convenience reasons. If you need to fine-tune your configuration, you can also manually edit the config file.
https://github.com/Tyrrrz/LightBulb/wiki/Config-file

**Comment by mirh** [comment]
I see the GUI should have a footprint as slim as possible. 
And consequentially too "tight" sliders would be a mess. 

But equally.. I don't think this is such of an exotic need? 
Couldn't you just make slider work in 200K steps? Or make range extremes labels double-clickable and editable?

**Comment by Tyrrrz** [comment]
I think the 200k steps would be too large. However I like the idea of manually editing the value. I will need to come up with a good way to put this all together though.

**Comment by mirh** [comment]
Fine tuning of values seems more petty than *range* tbh. I mean, ±100 surely is already a noticeable change, but I can't see your average joe caring for anything special in even a 300-400 span. 
Having gazed some time more to lightbulb UI then.. I guess double-clicking the value yes, would probably be best.. Though, a scaling issue would arise there. 
Maybe adding some additional mode/items in the program icon right-click menu (again, simlarly to flux .-.)?
Your call.

**Comment by Tyrrrz** [comment]
I'll give it more thought later as I was going to improve UI anyway.

**Comment by JJRcop** [comment]
Clicking on the number itself could convert the text to an input box.
