### ISSUE TITLE
Lightbulb reverts colors

### ISSUE THREAD

**Issue by Ryrynz** [Tyrrrz/LightBulb#210]
### Version

2.3.2

### Details

Every once and a while Lightbulb's color changing switches off and goes back to normal colors instantly
When I click disable, the color temporarily changes back to warmer colors then fades out back to normal colors, I then enable it to get the warmer colors back again and it's good for awhile. Never had this problem with 2.3 so I'm reverting.

### Steps to reproduce

Seems to happen randomly, just watching youtube in Chrome and BAM blue light in my eyes.

**Comment by Tyrrrz** [comment]
Color resetting is a sign that some other application or possibly Windows itself is resetting the gamma for one reason or another. In most cases LightBulb can detect this and reset it back (resulting in a flicker). In some cases it cannot, which can be worked around by enabling gamma polling in settings (which will still cause flickers, but at least you won't have to manually disable/enable it).
