### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by dekvas** [Tyrrrz/LightBulb#213]
### Version

2.3.2; 2.3

### Details

For a long time, the latest version of the program was installed, but a couple of days ago (9 or 10) it stopped starting and gave an error about some not downloaded update packages. I thought it was a problem of the new version, I downloaded 2.3, however, it has exactly the same problem.
I tried to install them automatically, but not 1 package could install. Then, I - manually downloaded and installed all 3 packages (not without difficulty) but the last one (KB3063858) is still not considered installed.
I do not want to download older versions of the program, as they are less convenient and practical for me. Can you tell me what to do?

-------------------------------------------------

Screenshot of the error:
https://ibb.co/X3RCqpD

-------------------------------------------------

P.s.
Looked at past bug topics, where you asked to show downloaded updates.
I decided in advance to attach them (sorry there are so many of them).

https://ibb.co/NmyMwyY
https://ibb.co/4f7hhvy
https://ibb.co/VCgsZzz

### Steps to reproduce

1. Download and install Windows 7
2. Download and install the LightBulb program
3. Get depressed

**Comment by Tyrrrz** [comment]
Thanks for reporting and sorry about the issue. I will try to fix it soon.

Related to #209.

**Comment by dekvas** [comment]
> Thanks for reporting and sorry about the issue. I will try to fix it soon.
> 
> Related to #209.

Thank you for answer. I will wait.
