### ISSUE TITLE
Can't start LightBulb (fresh install)

### ISSUE THREAD

**Issue by slasherfun** [Tyrrrz/LightBulb#214]
### Version

2.3.3

### Details

Freshly installed LightBulb on a Windows 10 21H1 computer.

When trying to start LightBulb:
![image](https://user-images.githubusercontent.com/10389790/124924773-101caf00-dffc-11eb-8edd-fb87f6371866.png)
![image](https://user-images.githubusercontent.com/10389790/124924964-45c19800-dffc-11eb-8513-a610fe142345.png)
(clicking "Install")
![image](https://user-images.githubusercontent.com/10389790/124925015-53771d80-dffc-11eb-8509-46904d5d2b60.png)

### Steps to reproduce

See in the "details" section.

**Comment by slasherfun** [comment]
The "machine.config" file was apprently corrupted, it did work after copying the content from "maching.config.default".
Leaving the bug open in case this would have something to do with LightBulb.

**Comment by Tyrrrz** [comment]
This does not seem like anything to do with LightBulb. Looks like your .NET Framework installation (that comes with Windows) was corrupted.
