### ISSUE TITLE
LightBulb instantly disables when I access System and Ease of Access settings in Windows 10

### ISSUE THREAD

**Issue by Dark-Magician** [Tyrrrz/LightBulb#218]
### Version

2.3.3

### Details

LightBulb instantly disables when I access System and Ease of Access settings in Windows 10 (build 19042.1237) until I restart the program.

### Steps to reproduce

1. Open Windows 10 settings.

2. Select System or Ease of Access.

At this point, LightBulb disables until I restart it, but it continues to show enabled in its tray icon.

**Comment by Tyrrrz** [comment]
Yeah, unfortunately no way around it. You can disable-enable LightBulb instead of restarting it to reset it.

**Comment by Tyrrrz** [comment]
Interesting. I wonder what "Always use Windows internal color table" does internally.

**Comment by Tyrrrz** [comment]
Looks like Microsoft is killing `SetDeviceGammaRamp` 🙃 

![image](https://user-images.githubusercontent.com/1935960/144873260-35c0ee1f-1e51-477c-84f9-e6da1d91d674.png)

**Comment by Tyrrrz** [comment]
The workarounds introduced with v2.4.5 should help with this issue. Unfortunately, the screen may still flicker, but at least it will reset the gamma to the correct value.
