### ISSUE TITLE
Crash when reassigning hotkeys

### ISSUE THREAD

**Issue by Koragg618** [Tyrrrz/LightBulb#22]
Hey,

I set a hotkey for disabling Gamma Polling with (CTRL + ALT + 1), but whenever I try to change it, it seems to crash.

Let me know if I should provide logs of sorts.

EDIT: Tried it with the other options as well and it crashes. Fixed the problem for now by editing the .dat file.

**Comment by Tyrrrz** [comment]
Hi.
Does it crash right after setting a new hotkey?
Are you able to test the master branch?

**Comment by Koragg618** [comment]
No, it seems to crash regardless of when I set the hotkey. It seems like as long as there's a hotkey, it will crash when I try to assign a new one.

Also, no I'm not able to test the master branch, so it may have been fixed already?

**Comment by Tyrrrz** [comment]
It may have been fixed already, although I don't remember having that bug in the first place. Either way, I can't reproduce it with the current build so we will see if it persists after next release.

**Comment by Tyrrrz** [comment]
Try the new release

**Comment by Koragg618** [comment]
Tried it out, and works nicely! Thanks for the quick updates 👍
