### ISSUE TITLE
Error when downloading KB3154518 on Windows 7

### ISSUE THREAD

**Issue by he3als** [Tyrrrz/LightBulb#220]
### Version

2.3.3

### Details

There is an error 404 when downloading a certain update (KB3154518).

![explorer_eRclG2JmMt](https://user-images.githubusercontent.com/65787561/138155141-38e2d8dd-75bf-472b-b24b-9a5af7c7b312.png)

### Steps to reproduce

1. Use Windows 7
2. Not have this security update
3. Try to download it with Lightbulb

**Comment by Rajbir98** [comment]
when will this fix

**Comment by Tyrrrz** [comment]
Will be fixed in upcoming release
