### ISSUE TITLE
Throttling for increase/decrease brightness hotkeys is too harsh

### ISSUE THREAD

**Issue by ItsCubeTime** [Tyrrrz/LightBulb#226]
### Version

ver 2.3.3

### Details

Essentially if you press whatever hotkey youve set for offsetting the brightness and temperature several times under the time period of about 0<X<0.2 only the first key press is read, the rest is ignored, this makes it so it takes like 4 seconds to go from the brightest possible setting to the darkest.

Personally I find it much of an annoyance as changing brightness is something you want to go quick and efficient, similar apps such as "dimscreen" does not have this behaviour.

Potential fixes would be either letting the user set a "stepping period" themselves or improving the code to read several keypresses given in a succesion rather than measuring time between each keypress.

### Steps to reproduce

-||-

**Comment by Tyrrrz** [comment]
Yeah, right now it's throttled to one hotkey press per 200 ms, just to avoid accidental multi-presses. I guess it can be lowered a bit.
