### ISSUE TITLE
All the High DPI scailing override data killed at oce

### ISSUE THREAD

**Issue by berlihingen** [Tyrrrz/LightBulb#227]
### Version

2.4

### Details

I can't even remember the last time I was forced to restore the system registry after ditching an app! On a 40" 4k upscaled display this bulb managed to kill all customized DPI settings for other apps at once! WTF? Anyway turned out the bulb is less than 10% of old, out of development, still the best ClickMonitorDDC.

### Steps to reproduce

Start app, read a vague statement on system gamma, press OK. Then start any app with scaling corrected - not anymore.

**Comment by Tyrrrz** [comment]
Shouldn't affect DPI scaling. The only registry key it modifies is this one:

https://github.com/Tyrrrz/LightBulb/blob/2326a80dc92df3fc25222fc500cee5099a057818/LightBulb/Services/SettingsService.cs#L16-L20

Most likely something else caused the corruption.
