### ISSUE TITLE
Strange glitches at 1200K

### ISSUE THREAD

**Issue by mirh** [Tyrrrz/LightBulb#23]
Desktop gets like inverted blue or something for some seconds.. Then switch back to normal.

**Comment by Tyrrrz** [comment]
Does the bug repeat itself after closing/opening LightBulb?

**Comment by mirh** [comment]
Yes. 
Also.. It seemed like I hadn't problems for some minutes when it started this evening. 
Now it's bugging out as hell. I hypothesize something might be going on between 1950 and 1850K,

**Comment by Tyrrrz** [comment]
What do you mean by bugging out as hell? What is happening? Can you send your configuration file?

**Comment by mirh** [comment]
![Here](https://cloud.githubusercontent.com/assets/9366725/24933408/7c16c9c6-1f16-11e7-8ab3-ded59b6d399f.png) you are, with pics. 
I'm on W7 if it can help.

**Comment by Tyrrrz** [comment]
The screenshot isn't opening for me
![2017-04-12 10_16_03-strange glitches at 1200k issue 23 tyrrrz_lightbulb](https://cloud.githubusercontent.com/assets/1935960/24945720/0f05cbf4-1f69-11e7-9ebc-8da17d4c5191.png)

**Comment by Tyrrrz** [comment]
Try the new release

**Comment by mirh** [comment]
Looks fixed!
