### ISSUE TITLE
Brightness goes to the minimum when using shortcuts to decrease it

### ISSUE THREAD

**Issue by BassamAlim** [Tyrrrz/LightBulb#230]
### Version

2.4.0

### Details

brightness offset goes all the way to the minimum when using keyboard shortcuts to decrease brightness offset
windows 10

### Steps to reproduce

using keyboard shortcus to decrease brightness offset

**Comment by Tyrrrz** [comment]
Hi, can you share your settings?

**Comment by BassamAlim** [comment]
Hi thank you for responding quickly

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by Tyrrrz** [comment]
I think I found the bug. Can you try this build from CI (when it finishes)?
https://github.com/Tyrrrz/LightBulb/actions/runs/1556095349

**Comment by BassamAlim** [comment]
Thank you the problem is fixed

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
