### ISSUE TITLE
Antivirus software now detects the portable version as including malware

### ISSUE THREAD

**Issue by CADLG** [Tyrrrz/LightBulb#232]
### Version

2.4.1

### Details

Webroot SecureAnyware started detecting the LightBulb executable as malware today (I have had it running on my machine for a long time).  I came to Github to download the zip file (Ver 2.4.1), and it was detected as malware upon download again.  I proceeded to upload it to virustotal.com, and it reported that 3 security vendors found malware in it as well.

![image](https://user-images.githubusercontent.com/96263041/146438558-e400c00a-06a1-4e47-9a48-85caac43f783.png)

Version 2.4.0 has the same problem.

I went back to version 2.3.3, which is reported as clean.

### Steps to reproduce

Scan it on Virustotal.com or locally using Webroot SecureAnyware.

**Comment by Tyrrrz** [comment]
Unfortunately this happens from time to time. If it's Microsoft Defender at least I can report it as false positive fairly easy. Don't know what to do about those no-name antiviruses. My advice is to ignore them, build from source, or use an older version (like you did).
