### ISSUE TITLE
Crash when adjusting sunrise/sunset to extreme values

### ISSUE THREAD

**Issue by theonlyonerzk** [Tyrrrz/LightBulb#237]
### Version

2.4.1

### Details

screenshot:
https://user-images.githubusercontent.com/61009872/149648709-2331a68c-a96e-4530-a48c-ce42dce97f97.png

video:
https://user-images.githubusercontent.com/61009872/149648681-b295ddb2-dc75-4aa3-8f21-3fc360944ac1.mp4

### Steps to reproduce

open lightbulb
go to settings > location
adjust sunrise/sunset by sliding

(i'm sorry my english is bad)

**Comment by theonlyonerzk** [comment]
> System.ArgumentOut0fRangeException: Ticks must be between 0 and and TimeOnly.MaxValue.Ticks. (Parameter 'ticks') at System.TimeOnly..ctor(Int64 ticks) at System.TimeOnly.FromTimeSpan(TimeSpan timeSpan) at LightBulb.Converters.TimeOnlyToHoursConverter.ConvertBack(Object value, Type targetType, Object parameter, Cultureinfo culture) in D: \ a \ LightBulIALightBulb\ LightBulb\ Converters\TimeOnlyToHoursConverter.cs:line 18 at System.Windows.Data.BindingExpression.ConvertProposedValue(Object value) at System.Windows.Data.BindingExpressionBase.UpdateValue() at System.Windows.Data.BindingExpression.UpdateOverride() at System.\Vindows.Data.BindingExpressionBase.UpdateO at System.\Vindows.Data.BindingExpressionBase.ProcessDirtyQ at System.Windows.Data.BindingExpressionBase.DirtyO at System.Windows.Data.BindingExpressionBase.SetValue(DependencyObject d, DependencyProperty dp, Object value) at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal) at System.Windows.DependencyObject.SetCurrentValueInternal(DependencyProperty dp, Object value) at System.Windows.Controls.Slider.UpdateValue(Double value) at System.Windows.Controls.Slider.OnThumbDragDelta(DragDeltaEventArgs e) at System.Windows.Controls.Slider.OnThumbDragDelta(Object sender, DragDeltaEventArgs e) at System.Windows.Controls.Primitives.DragDeltaEventArgsinvokeEventHandler(Delegate genericHandler, Object genericTarget) at System.Windows.RoutedEventArgsinvokeHandler(Delegate handler, Object target) at System.Windows.EventRoutelnvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised) at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args) at System.Windows.Controls.Primitives.Thumb.OnMouseMove(MouseEventArgs e) at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target) at System.Windows.EventRouteInvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised) at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args) at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args) at System.WindowsinputInputManager.ProcessStagingArea0 at System.WindowsinputinputProviderSite.ReportInput(InputReport inputReport) at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel) at System.Windowsinterop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr IParam, Boolean& handled) at System.Windowsinterop.HwndSourceinputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr IParam, Boolean& handled) at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr IParam, Boolean& handled) at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o) at System.Windows.Threading.ExceptionWrapperInternalRealCall(Delegate callback, Object args, Int32 numArgs) at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Tyrrrz** [comment]
Thanks for reporting! Fixed in the latest CI build.
