### ISSUE TITLE
Wrong maximum temperature?

### ISSUE THREAD

**Issue by mirh** [Tyrrrz/LightBulb#24]
Maximum in flux is just 6500K, and similarly seems default in AMD driver (which stores the setting in `HKLM\SYSTEM\CurrentControlSet\Control\Class\{4D36E968-E325-11CE-BFC1-08002BE10318}\0000\DAL2_DATA__2_0\DisplayPath_#¶\EDID_####_###\Adjustment` btw). 

I'm not sure if that's supposed to be default T for windows in general, or not.. But perhaps what about changing the last notch to a simple "disabled"?

**Comment by Tyrrrz** [comment]
6600k is the temperature that converts to RGB color intensity of 1/1/1 using the algorithm I'm using. I'm not sure why 6500k is the maximum in f.lux, maybe they are using a different algorithm.

**Comment by Tyrrrz** [comment]
It does look like most charts match 6500k to daylight though.
[This](http://www.tannerhelland.com/4435/convert-temperature-rgb-algorithm-code/) is the algorithm I've used to calculate RGB intensity.
I doubt it really matters for an end user, since they typically just set temperature using the preview rather than actual numbers.

**Comment by mirh** [comment]
Ugh, pretty cool reading. 
I guess the "problem" is that between 6500 and 6600 K some RGB values reach the maximum and some already starts to decrease (worsened by slight incongruences between different source color matching functions). 
Moreover, given the purpose of the program, [newest interpolation](http://www.zombieprototypes.com/?p=210) (did you check it?) adds a further variable.
Are we interested to max red, max green, *<*max blue, or highest sum of all components?

**Comment by Tyrrrz** [comment]
> I guess the "problem" is that between 6500 and 6600 K some RGB values reach the maximum and some already starts to decrease 

Nope, this algorithm maxes out all channels at the same time, when it reaches 6600k.

> Moreover, given the purpose of the program, newest interpolation (did you check it?) adds a further variable.

Haven't checked that one yet.

**Comment by mirh** [comment]
> Nope, this algorithm maxes out all channels at the same time, when it reaches 6600k.

~~According to the Charity's datasheet that never happens.~~ 

~~ Ok, that's what approximations are for in the first place.~~ 

Ok, ok, actually.. I'm not sure, even with original algorithm you could ever get green=255 ?

> Haven't checked that one yet.

The only difference there between 6500 and 6600 seems to be green goes down of 1/255, while blue goes up by the same amount. 

I guess that 6600 could be replace by "disabled" then? In this sense implying we are handling back everything to Windows (assuming its default light point is 255, 255, 255, we'd lack it)

**Comment by Tyrrrz** [comment]
6600k isn't disabled because it still overrides gamma, even though there's no difference in most cases. Some users set custom monitor gamma in GPU settings and whatnot, so for them 6600k isn't the original gamma. The actual "disable" is when you disable LightBulb by clicking the button.

**Comment by mirh** [comment]
> 6600k isn't disabled because it still overrides gamma, even though there's no difference in most cases

I know. Indeed my point was exactly to make it like that since the latter assumption. 

Of course that would only be valid if any, once you have checked Bartlett's calculations. 

> Some users set custom monitor gamma in GPU settings and whatnot, so for them 6600k isn't the original gamma.

Indeed, this thought also passed my mind (including wondering if a night shift program should follow a *delta* "relative" behavior, over this baseline, rather than going the absolutist way) but then I said I had already give you enough nuts to crack 😆 

Then, if you want, I can change the issue title to "improve algorithm" or something, but TBH I'm not sure closing threads (even when "path to solution" is laid ahead clear) is the best choice, in the interest of you reminding about this in weeks or months.

**Comment by Tyrrrz** [comment]
What do you mean by "path to solution"? I don't really see the problem in the first place. 😛

**Comment by mirh** [comment]
Perhaps I should have said "new TODO-list item derived from this issue pending".
