### ISSUE TITLE
Option to disable war in Ukraine message

### ISSUE THREAD

**Issue by UttermostUsername** [Tyrrrz/LightBulb#241]
### Version

2.4.4

### Details

There is no way to disable to message about the war in Ukraine on the start of the application. This causes the software to not open to background on start and requires manually closing the window every time the software is launched. There should be a method to disable the message and open to background as was the case before the message was added.
Normally this kind of thing is handled by permanently dismissing the message if someone presses "close" or "read more" on the message.
In this case it could also be implemented by adding a toggle for the message in settings if that is easier.
If the user makes a decision on the message, repeatedly giving the same message will not make them act more favorably toward the cause you are intending to support.

### Steps to reproduce

run the program

**Comment by Tyrrrz** [comment]
> This causes the software to not open to background on start and requires manually closing the window every time the software is launched.

That shouldn't be the case. The window isn't shown on autostart and that's unrelated to the message anyway.

**Comment by UttermostUsername** [comment]
There are multiple aspects to this.
1. Windows startup:  
It appears that the setting to autostart will use the --start-hidden option. I had been using startup by placing a shortcut in `%appdata%\Microsoft\Windows\Start Menu\Programs\Startup` so that part is my bad
2. Running program:  
I don't know if I am miss-remembering but starting the program (ex. double clicking it) used to open it to taskbar without opening a window. This is how shareX works so maybe I'm conflating the two.
3. Disabling message:  
If I intend to open the program to temporarily change the settings (or check sunset/sunrise time) the message will show up. The message has no way to permanently dismiss it.
The extra click to press dismiss is annoying and the message doesn't deliver new information so it is just an annoyance after first viewing.

**Comment by Tyrrrz** [comment]
1. Yes, `--start-hidden` is responsible for that.
2. No, running directly shows the window.
3. I'll remove the message when the war is over. Until then, it will annoy everyone, just like it annoys me.

**Comment by GrimPixel** [comment]
Why don't you condemn the United States?

**Comment by Tyrrrz** [comment]
@GrimPixel because they haven't invaded my country?

**Comment by quietmansoath** [comment]
I don't support the war, but this is just obnoxious. 

You don't care about the war crimes of the US (which is what GrimPixel was asking about) because they haven't effected you, in the same way people will ignore the Ukraine war (and your nagging button talking about it) because it doesn't effect them. 

Instead of making it easier for someone to care and learn a little more, you just pushed someone away.

Uninstalling. There are other free bluelight blocking apps.

**Comment by Tyrrrz** [comment]
> You don't care about the war crimes of the US (which is what GrimPixel was asking about) because they haven't effected you, in the same way people will ignore the Ukraine war (and your nagging button talking about it) because it doesn't effect them.

I condemn all war crimes, but it doesn't take a genius to understand why I would want to bring attention to the ones that personally affect me.

> Instead of making it easier for someone to care and learn a little more, you just pushed someone away.

If a single popup that opens when you bring up the app "pushed you away", then you weren't going to care in the first place.
