### ISSUE TITLE
Crash with "SystemInvalidOperationException: DialogHost is already open."

### ISSUE THREAD

**Issue by tomasz1986** [Tyrrrz/LightBulb#242]
### Version

ver 2.4.4 / Windows 10

### Details

I've experienced this error several times in a row when playing around with display resolution and DPI scaling. I've got a dual monitor setup, and it appears to happen when changing those settings on the second display, although I can't be 100% sure, because the issue isn't exactly reproducible at will. It just seems to occur randomly after changing the resolution/DPI-related Windows settings.

This is what I see when the program crashes:

![image](https://user-images.githubusercontent.com/5626656/162506785-6683c6ef-2d50-4cfe-810f-7b4b65bceb49.png)

Then, after pressing "OK":

![image](https://user-images.githubusercontent.com/5626656/162507754-92cc31cc-be00-408f-90e8-e4cc7d3a85ed.png)

Next, Lightbulb crashes and needs to be restarted manually.

### Steps to reproduce

Play around with monitor resolutions and DPI scaling with LightBulb running in the background. A multi-monitor setup may or may not be required. I apologise for a lack of more specific steps, which is due to being unable to reproduce the problem at will.

**Comment by Tyrrrz** [comment]
Can you please try the latest CI build to see if it fixed the problem?

**Comment by tomasz1986** [comment]
Difficult to say for sure, but I've tried to change the DPI and resolution several times in a row, and the program didn't crash during the operation, so let's say that it's fixed 🙂.
