### ISSUE TITLE
UI very unresponsive during cycle preview

### ISSUE THREAD

**Issue by Antosser** [Tyrrrz/LightBulb#244]
### Version

latest

### Details

If I click the preview button, the orange dot, the temperature, and the brightness, will freeze for a few seconds a couple of times before it reaches the same spot it started at. This bug also occurs when I change the temperature / brightness manually from the settings. It again has very low fps (roughly 1 update / 2 seconds)

https://user-images.githubusercontent.com/71790328/169157567-b78baa0a-8e75-4519-9895-e9ea5f21461a.mp4

Device Specs:
```
Processor	AMD Ryzen 7 5700G with Radeon Graphics            3.80 GHz
Installed RAM	32.0 GB (31.3 GB usable)
Device ID	39AD8145-7327-43C6-8823-9C3B42072992
Product ID	00330-80132-05740-AA560
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display
```
Windows Specs:
```
Edition	Windows 11 Pro
Version	21H2
Installed on	‎23-‎Apr-‎22
OS build	22000.675
Experience	Windows Feature Experience Pack 1000.22000.675.0
```
Graphics:
```
GPU: NVIDIA GeForce RTX 3060 Ti
Drivers: Latest GeForce Game Ready Driver
```

### Steps to reproduce

* Install LightBulb
* (restart windows to make LightBulb function)
* Press the preview button or change the temperature / brightness manually
* It has low fps

**Comment by Antosser** [comment]
Note: The brightness and temperature changes work perfectly. It's just the UI

**Comment by Aman-Anas** [comment]
I have also experienced this exact issue, ever since I installed Lightbulb. Again, everything else works fine.

**Comment by Tyrrrz** [comment]
I think this is just the limitation of the underlying framework. LightBulb triggers a lot of UI updates during cycle preview, and it just can't handle it smoothly.
