### ISSUE TITLE
Cannot start application after installing the latest version of .NET (error)

### ISSUE THREAD

**Issue by coalexandr** [Tyrrrz/LightBulb#247]
### Version

latest

### Details

After installing latest version of .NET (for an application which i wanted to use) i restarted pc and LightBulb gives me this error:

![bwUX0fJ - Imgur](https://user-images.githubusercontent.com/106074213/175253568-c6ad1313-c58c-4c17-9dca-062ce69a2fa1.png)
J

Im using the latest version of LightBulb, tried to re-install, nothing helps.

### Steps to reproduce

1. Install latest version of .NET (or maybe latest windows 10 updates, but not sure)
2. Restart pc.
3. Open lighbulb and get this error.

**Comment by Tyrrrz** [comment]
Are you using portable version or installer?

**Comment by coalexandr** [comment]
I reinstalled all .NET runtimes, and it doesn't solved the problem.

**Comment by Tyrrrz** [comment]
You don't have to reinstall them yourself, just let LightBulb install them

**Comment by hotellinawebmaster** [comment]
I get the same error.
How do we let Lightbulb install the .NET again? Where is the button to do that?

**Comment by Tyrrrz** [comment]
If you uninstall .NET completely, LightBulb will offer to install it for you the next time you launch it. Going to "Add or remove programs" and uninstalling anything that contains ".NET SDK" or ".NET Runtime" should be enough.

**Comment by hotellinawebmaster** [comment]
It seems strange but by just removing the link I used to your application and by making a new fresh link pointing to the same app, now it works ok. Also I noticed that error disappeared when starting your app directly from its executable.
Maybe Windows 10 was starting your app with different configuration/compatibility settings. Thanks.

**Comment by coalexandr** [comment]
Tried to uninstall all components including ".NET" symbols. Part of them was installed by visual studio installer (i also deleted them).
Now when i try to install light bulb, it installs as usually and when i start app i get the same error. 
Seems to be light-bulb doesn't ask me to install any .net components by itself.

**Comment by coalexandr** [comment]
> dotnet LightBulb.dll

I got this error message when i do command

`Cannot use file stream for [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\6.0.3\Microsoft.WindowsDesktop.App.deps.json]: No such file or directory
A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found in 'C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\6.0.3'.`

**Comment by Tyrrrz** [comment]
It does really sound like the desktop version of the runtime wasn't installed, but considering that LightBulb checks for it, it's strange. Could you try manually installing it from [here](https://dotnet.microsoft.com/en-us/download/dotnet/6.0) (look for .NET Desktop Runtime 6.0.7)?

**Comment by coalexandr** [comment]
Im on windows and only this "dotnet-sdk-6.0.302-win-x64.exe" file helped me to fix the error.
Now works fine, thanks.

**Comment by Tyrrrz** [comment]
Really weird, but glad it works at least.
