### ISSUE TITLE
High RAM and some CPU always in use

### ISSUE THREAD

**Issue by djsolidsnake86** [Tyrrrz/LightBulb#248]
### Version

2.4.5

### Details

win 10 here, 2.4.5 is the first version of this app that i'm using, i see a ram consumption of always about 70-75mb and a cpu percentage of using of 0.1% / 0.5% without doing nothing, is this normal?
when using f.lux i have 10mb of ram and 0% of cpu using all the time

### Steps to reproduce

.

**Comment by tomasz1986** [comment]
The situation is same here, except that on low-end hardware like an Intel Atom Bay Trail tablet, the CPU usage always seems to oscillate around ~5%, which is quite a lot. This is during daytime with gamma polling disabled, so I'm not sure what exactly is using the CPU at that time.

Is the constant CPU usage expected and something that cannot really be avoided?

**Comment by Tyrrrz** [comment]
Unfortunately, I can't reproduce the CPU usage on my machine to be able to experiment and see what makes the usage go higher or lower. My attempts at profiling didn't yield many useful insights (although I'm not good at it). It would be great if someone who's experiencing CPU usage issues could clone the project and try to see which parts cause the problem.

**Comment by tomasz1986** [comment]
That's interesting, because I run LightBulb on at least 4 different devices, and the issue is present on all of them.

Is there any way to produce a debug log or similar without diving deep into the code for debugging? My programming skills are rather limited, unfortunately.

**Comment by Tyrrrz** [comment]
> That's interesting, because I run LightBulb on at least 4 different devices, and the issue is present on all of them.

You have ~5% CPU usage on all machines? Mine spikes to 0.1% at most 🤔 

> Is there any way to produce a debug log or similar without diving deep into the code for debugging? My programming skills are rather limited, unfortunately.

There probably is, but I don't know of one... Unfortunately, I'm not skilled enough at performance profiling. :(

**Comment by tomasz1986** [comment]
> You have ~5% CPU usage on all machines? Mine spikes to 0.1% at most 🤔

Yeah, it's ~5% on devices with a slow CPU, and below ~1% on rather fast desktops. It seems to be doing something constantly though, as the CPU usage keeps fluctuating non-stop on all of them.

**Comment by djsolidsnake86** [comment]
the fact is that is a bug of the app, not a problem of our computers configuration
only the author can solve

**Comment by djsolidsnake86** [comment]
if can be useful i tried the version with the old graphic engine, and there wasn't this cpu problem

**Comment by Tyrrrz** [comment]
Old graphic engine?

**Comment by djsolidsnake86** [comment]
> Old graphic engine?

try version 1.6.4.1

**Comment by tomasz1986** [comment]
> try version 1.6.4.1

I can confirm. This version uses only ~1% of CPU on the Intel Atom device. I've also checked a few different 2.x versions, but all of them seem to share the same ~5% CPU usage.

**Comment by djsolidsnake86** [comment]
any news about fix this problem?

**Comment by pbaykalov** [comment]
On my 5600X desktop Lightbulb used 1% of one CPU core on average.
If you are relying on CPU utilization from the Performance tab you should stop doing so because it somehow reports bogus results. Instead, use "CPU time" from "Details" tab which reports how much single core time the process consumed since it launched.

**Comment by StanFromTraction** [comment]
Is 200-500mb average memory usage normal?

**Comment by Tyrrrz** [comment]
> Is 200-500mb average memory usage normal?

No, it's not normal. At least not all the time (it can use more memory when it's performing auto-update).
