### ISSUE TITLE
Add more concrete transition offset examples to Wiki for better understanding

### ISSUE THREAD

**Issue by tomasz1986** [Tyrrrz/LightBulb#249]
### Version

all

### Details

I'd like to apologise in advance, as this isn't really a bug report, but I hope it's still OK to ask this question here.

I've been experimenting with transition offset lately. The Wiki at https://github.com/Tyrrrz/LightBulb/wiki/How-the-transition-offset-works does provide some explanation, but to tell the truth, without real-world examples, I still find it somewhat confusing.

For instance, let's say sunrise is set to `5:00` and transition duration is left at its default of `00:40:00`. With the offset set to `0%`, does this mean that the transition will begin at `4:20` and end at `5:00`? If yes, then does setting the offset to `50%` move the start time to `4:40` and the end time to `5:20`? Analogically, does the offset of `100%` move the start and end times to `5:00` and `5:40` respectively?

I think it'd be useful to have in the Wiki more concrete examples using actual time values in addition to the percentages. If you agree, I'd be willing to create a PR myself, but I first need to be sure that my understanding is correct.

Alternatively, it'd be cool if the application told the user the exact time when the transition starts and ends that includes the offset in its calculation, but this would probably qualify more as a feature request rather than just asking for clarification.

### Steps to reproduce

Change the transition offset to different percentage values and observe how the transition start and end times change.

**Comment by Tyrrrz** [comment]
Does this help a bit?

- 0% offset (default):

```
   Sunrise                 Sunset
      *                       *      
     /------------------------\
----/                          \----

    ^                         ^
    |                         |

  Sunrise                   Sunset
  transition                transition
  start                     start
```

- 100% offset (inverted):

```
   Sunrise                 Sunset
      *                       *      
       /---------------------\
------/                       \----

      ^                      ^
      |                      |

  Sunrise                   Sunset
  transition                transition
  start                     start
```

And then values etween 0% and 100% is everything in between.

**Comment by tomasz1986** [comment]
It does, although I still think hard numbers would be easier to understand 🙂.

At the moment I'm testing an offset of `75%` with a transition time of `00:45:00`. Sunrise is at `05:22`, and sunset at `19:43`. According to my calculations, the actual transition time should be between `05:11 - 05:56`, and `19:32 - 20:17` (with all values rounded to integers). I only hope these values are correct.

The whole reason for playing around with the offset is because with the default settings, I always find the monitor too bright in the morning, and also too bright in the evening, so I'd prefer to have the transition start later in the morning, and earlier in the evening (with location-based solar configuration, so no manual tweaking of the hours themselves).

**Comment by Tyrrrz** [comment]
Here are the formulas btw:

https://github.com/Tyrrrz/LightBulb/blob/9e9214905649eed54374e6ba2b4eb1875ad90a45/LightBulb.Core/Cycle.cs#L8-L58

**Comment by Tyrrrz** [comment]
If you can come up with a better way to explain it or maybe some additional easy-to-understand examples, I'd be happy to add it to the wiki, btw. I'm not good at explaining such concepts myself.

**Comment by tomasz1986** [comment]
No problem. I'd personally suggest enhancing the existing examples with concrete times. It doesn't seem possible to create a PR for the wiki directly, so I'm uploading the patch below. Please feel free to make any changes necessary, if you do like it in the first place, of course.

```
From d01bb566590df44564e98acc1cb13a9b2c2f4d66 Mon Sep 17 00:00:00 2001
From: =?UTF-8?q?Tomasz=20Wilczy=C5=84ski?= <twilczynski@naver.com>
Date: Thu, 25 Aug 2022 21:05:15 +0200
Subject: [PATCH] Add more concrete examples to transition offset
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit

Currently, transition offset is explained using percentate-based values.
This can be confusing for many people, especially if they want to know
the actual transition duration time and how it shifts depending on the
offset.

Therefore, complement the existing percentages with concrete examples
using specific sunrise and sunset times, so that each example includes
the specific time period when the transition takes place.

Signed-off-by: Tomasz Wilczyński <twilczynski@naver.com>
---
 How-the-transition-offset-works.md | 22 +++++++++++-----------
 1 file changed, 11 insertions(+), 11 deletions(-)

diff --git a/How-the-transition-offset-works.md b/How-the-transition-offset-works.md
index f5361d3..6d1470c 100644
--- a/How-the-transition-offset-works.md
+++ b/How-the-transition-offset-works.md
@@ -1,28 +1,28 @@
-Transition offset allows you to specify how early or late the transitions start, relative to sunrise and sunset. It's best to understand how it works by looking at some examples:
+Transition offset allows you to specify how early or late the transitions start, relative to sunrise and sunset. It's best to understand how it works by looking at some examples. For the purpose of demonstration, let's assume that sunset takes place at 5:00 AM, sunrise at 7:00 PM, and transition duration is set to 40 minutes.
 
 - **0% offset** (default)
 
-  - Day-time transition starts before sunrise and ends precisely at sunrise
-  - Night-time transition starts precisely at sunset and ends after sunset
+  - Day-time transition starts before sunrise at 4:20 AM and ends precisely at sunrise at 5:00 AM.
+  - Night-time transition starts precisely at sunset at 7:00 PM and ends after sunset at 7:40 PM.
 
 - **25% offset**
 
-  - Day-time transition starts 75% before sunrise and ends 25% after sunrise
-  - Night-time transition starts 25% before sunset and ends 75% after sunset
+  - Day-time transition starts 75% before sunrise at 4:30 AM and ends 25% after sunrise at 5:10 AM.
+  - Night-time transition starts 25% before sunset at 6:50 PM and ends 75% after sunset at 7:30 PM.
 
 - **50% offset**
 
-  - Day-time transition starts halfway before sunrise and ends halfway after sunrise
-  - Night-time transition starts halfway before sunset and ends halfway after sunset
+  - Day-time transition starts halfway before sunrise at 4:40 AM and ends halfway after sunrise at 5:20 AM.
+  - Night-time transition starts halfway before sunset at 6:40 PM and ends halfway after sunset at 7:20 PM.
 
 - **75% offset**
 
-  - Day-time transition starts 25% before sunrise and ends 75% after sunrise
-  - Night-time transition starts 75% before sunset and ends 25% after sunset
+  - Day-time transition starts 25% before sunrise at 4:50 AM and ends 75% after sunrise at 5:30 AM.
+  - Night-time transition starts 75% before sunset at 6:30 PM and ends 25% after sunset at 7:10 PM.
 
 - **100% offset**
 
-  - Day-time transition starts precisely at sunrise and ends after sunrise
-  - Night-time transition starts before sunset and ends precisely at sunset
+  - Day-time transition starts precisely at sunrise at 5:00 AM and ends after sunrise at 5:40 AM.
+  - Night-time transition starts before sunset at 7:00 PM and ends precisely at sunset at 7:40 PM.
 
 Depending on factors such as window angle, elevation, building density, presence of trees or mountains, etc., adjusting this offset may help bring your monitor's gamma cycle more in line with how the solar cycle is perceived in your environment.
\ No newline at end of file
-- 
2.35.1.windows.2
```

[0001-Add-more-concrete-examples-to-transition-offset.patch.txt](https://github.com/Tyrrrz/LightBulb/files/9427573/0001-Add-more-concrete-examples-to-transition-offset.patch.txt)

**Comment by Tyrrrz** [comment]
Cool, thanks! Added.

**Comment by tomasz1986** [comment]
Thank you very much for applying the changes! There was however a mistake on my part in the last example 🙁. I'm attaching yet another patch to fix it below.

```
From 9faad2a7ce209b1747dd0634442b915095f63344 Mon Sep 17 00:00:00 2001
From: =?UTF-8?q?Tomasz=20Wilczy=C5=84ski?= <twilczynski@naver.com>
Date: Thu, 25 Aug 2022 22:12:37 +0200
Subject: [PATCH] Fix 100% transition offset example times
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit

Fix the incorrect transition start and end times.

Signed-off-by: Tomasz Wilczyński <twilczynski@naver.com>
---
 How-the-transition-offset-works.md | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/How-the-transition-offset-works.md b/How-the-transition-offset-works.md
index f95f394..b2f4491 100644
--- a/How-the-transition-offset-works.md
+++ b/How-the-transition-offset-works.md
@@ -25,6 +25,6 @@ For the purpose of demonstration, let's assume that sunset takes place at 5:00 A
 - **100% offset**
 
   - Day-time transition starts precisely at sunrise at 5:00 AM and ends after sunrise at 5:40 AM.
-  - Night-time transition starts before sunset at 7:00 PM and ends precisely at sunset at 7:40 PM.
+  - Night-time transition starts before sunset at 6:20 PM and ends precisely at sunset at 7:00 PM.
 
 Depending on factors such as window angle, elevation, building density, presence of trees or mountains, etc., adjusting this offset may help bring your monitor's gamma cycle more in line with how the solar cycle is perceived in your environment.
\ No newline at end of file
-- 
2.35.1.windows.2
```
[0001-Fix-100-transition-offset-example-times.patch.txt](https://github.com/Tyrrrz/LightBulb/files/9427986/0001-Fix-100-transition-offset-example-times.patch.txt)

**Comment by Tyrrrz** [comment]
Thanks!
