### ISSUE TITLE
Is the program supposed to be a 3D process?

### ISSUE THREAD

**Issue by mirh** [Tyrrrz/LightBulb#25]
I wouldn't know the exact Windows function, though lightbulb shows up in [msi afterburner](https://www.msi.com/page/afterburner) active 3D processes list. 
Now, should there be any problem, I'm sure I could easily blacklist the executable.. But I was wondering if this thing was an actual hard requirement (perhaps part of the functional differences that makes this better than flux) or something of a perhaps slip.

**Comment by Tyrrrz** [comment]
I think that's just because the GUI is rendered by WPF using DirectX.

**Comment by mirh** [comment]
Cool, pretty stupid thing then. 
But.. Why is the GUI still rendered when "not there"? 😛

**Comment by Tyrrrz** [comment]
Well the rendering context lasts as long as the application is running, even if it's not showing anything.

**Comment by mirh** [comment]
http://stackoverflow.com/questions/3367430/force-wpf-to-render-a-window-while-hidden
People here seems to have the opposite problem in fact, but OOOK.
