### ISSUE TITLE
Brightness/gamma control doesn't work suddenly

### ISSUE THREAD

**Issue by clidx** [Tyrrrz/LightBulb#253]
### Version

2.4.5

### Details

I rebooted and the gamma control doesn't work anymore. I got a warning saying I needed to launch the app as admin to get extended gamma range, clicked OK and nothing happened. I then opened the app with admin rights but it still doesn't work. There is no difference between 0 and 100% brightness anymore.
I have disabled pause when fullscreen, but nothing. The application whitelist is also disabled. It's 22:12 here, sunset is set to 20:00 and sunrise is 07:00 (manual). Not sure why it's not working.

### Steps to reproduce

Run program

**Comment by Tyrrrz** [comment]
Can you check the value of this registry entry?

`HKLM\Software\Microsoft\Windows NT\CurrentVersion\ICM\GdiICMGammaRange`

It should be `256`.

**Comment by clidx** [comment]
It seems that registry tweak requires another reboot. Probably should have tried that.. but hey ho! Thanks.
