### ISSUE TITLE
Computer resources explosion while updating

### ISSUE THREAD

**Issue by Ahmed3457** [Tyrrrz/LightBulb#256]
### Version

2.4.5 while upgrading to 2.4.6

### Details

My computer completely froze while updating using the auto update feature, this is mainly caused by a trash laptop, but this explosion feels very wrong, 14% memory usage >> 88% while update >> back to normal

### Steps to reproduce

# steps
1. install lightbulb 2.4.5
2. enable auto start on login
3. log off
4. log in back again and start the task manager quickly to watch the resources (not necessary)

**Comment by Tyrrrz** [comment]
It's unusual that the computer would freeze, but I guess it's expected that the application will use more resources while updating. I think this is more the case where the issue is in the hardware, though, because I didn't observe any noticeable slowdowns.
