### ISSUE TITLE
False location lock

### ISSUE THREAD

**Issue by Seniorrrr** [Tyrrrz/LightBulb#257]
### Version

2.4.6

### Details

Today the lightbulb crashed and stopped working, I open the .exe and it tells me that I'm located in Russia or Belarus even tho I live nearly in the middle of Ukraine (Dnipro). And I don't have any VPN. And never had this issue before. Please fix it!

I'm not sure about version cuz I can't even open the program to check it. 

![image](https://github.com/Tyrrrz/LightBulb/assets/45339412/619a1895-1367-4b32-ad2e-ab5c2c27e34e)

### Steps to reproduce

just open exe as usual
![image](https://github.com/Tyrrrz/LightBulb/assets/45339412/1a046543-dbc3-4e62-a9a1-db600f0b396b)

**Comment by Seniorrrr** [comment]
The bypass isn't really clear for a non coding user too. In which system settings?

**Comment by Tyrrrz** [comment]
Hey @Seniorrrr.

Make sure your location isn't set to "russia" here:

![image](https://github.com/Tyrrrz/LightBulb/assets/1935960/96bfdf8c-e621-4d30-825f-ddb820d867b2)

It's a common issue, especially for pirated distributions of Windows.

**Comment by Seniorrrr** [comment]
it worked, thanks
