### ISSUE TITLE
Application icon outdated on window banner

### ISSUE THREAD

**Issue by LonelyHowl** [Tyrrrz/LightBulb#258]
### Version

ver 2.4.6

### Details

Since the most recent update, the icon of the application changed (looks great by the way)
However, the banner on the main window still uses the old app icon!

### Steps to reproduce

Have LightBulb running and leftclick on the tray icon to open the window

**Comment by Tyrrrz** [comment]
Indeed, but that's because the icon in the banner isn't really a special icon, but rather just a MaterialDesign icon, which is the design system used for the rest of the app too.

This mismatch might be a bit confusing, but this is not an oversight.
