### ISSUE TITLE
Flash bang effect

### ISSUE THREAD

**Issue by quester02** [Tyrrrz/LightBulb#259]
### Version

v2.4.6

### Platform

Windows 11

### Steps to reproduce

Using touch screen mode resuming from hibernate/lid close state, swipe up the system tray and the app suspends for a half a second and resumes filtering. 

### Details

Creating a jarring flash to the eyes due to the quick jump between warm and cool Temps.

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project

**Comment by Tyrrrz** [comment]
This is caused by Windows resetting gamma. There is no other way to workaround it other than to set it back to the correct ramp, but that unfortunately causes a flicker you're observing. Windows gamma controls suck.
