### ISSUE TITLE
Dll was not found for `CreateResetEvent`

### ISSUE THREAD

**Issue by w4ri0** [Tyrrrz/LightBulb#261]
### Version

2.4.6

### Platform

windows 11

### Steps to reproduce

base settings
<img width="624" alt="2023-11-07 10_58_55-Error occured" src="https://github.com/Tyrrrz/LightBulb/assets/148529201/4379a720-4fa1-4f14-8c2a-10eeba4a5dc6">

### Details

multiples windows error popup shown

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project

**Comment by Tyrrrz** [comment]
Looks like something is wrong with either your .NET or Windows installation.

**Comment by w4ri0** [comment]
I'm on a clean .net and windows install i downgraded to .5 and the problem
disappeared

Le mar. 7 nov. 2023, 13:00, Oleksii Holub ***@***.***> a
écrit :
