### ISSUE TITLE
Screen brightness percentage increase/decreases slowly, while having no effect on display

### ISSUE THREAD

**Issue by AhmedSHussaini** [Tyrrrz/LightBulb#263]
### Version

v2.4.7

### Platform

Windows 11

### Steps to reproduce

Click on the 'Switch LightBulb on/off' button 

https://github.com/Tyrrrz/LightBulb/assets/59965531/9b7da29b-6e26-4334-a4bf-7403dbcef472

### Details

Clicking on the 'Switch LightBulb on/off' button results in the screen brightness percentage increasing/decreasing very slowly while having no effect on the display. There isn't much else to say, as far as I noticed it started before the most recent update.

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project

**Comment by Tyrrrz** [comment]
Have you looked at this: https://github.com/Tyrrrz/LightBulb/wiki/Troubleshooting

**Comment by AhmedSHussaini** [comment]
Yup, Both my windows and display drivers are up to date. 

I'm using a laptop connected to an external monitor, where the laptop display is using the iGPU and the external monitor is using the dGPU. I've tried disabling either one to no effect. Guess I'll just reinstall and see what happens.

**Comment by Tyrrrz** [comment]
Hmm, it might be an issue of two monitors being powered by different GPUs. Does the gamma change on your main monitor?

**Comment by AhmedSHussaini** [comment]
No, it doesn't change on either. Previously it was changing on both

**Comment by AhmedSHussaini** [comment]
v2.4.6 and earlier

**Comment by Tyrrrz** [comment]
Hmm are you sure? Does it work if you install that version again?

**Comment by AhmedSHussaini** [comment]
It wasn't, but I reinstalled .Net and it's working again. Think it happened because of the .Net release last week. Thanks for your help!

**Comment by Tyrrrz** [comment]
Glad it's working again now!
