### ISSUE TITLE
Color temperature set to 6600k rather than the standard 6500k when Lightbulb disabled

### ISSUE THREAD

**Issue by GustavoQueipo** [Tyrrrz/LightBulb#265]
### Version

v2.4.6

### Platform

Windows 10 22H2

### Steps to reproduce

While running, disable Lightbulb by clicking on the lightbulb icon on the top left of the main window, or alternatively by using the assigned keyboard shortcut.
The "Default to day-time configuration" must be disabled in settings.

### Details

Expected behavior:
Default Windows system values of 6500k color temperature and 100% brightness are restored while disabled.

Actual behavior:
Color temperature is set to 6600k

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project

**Comment by Tyrrrz** [comment]
Hi.

LightBulb uses a different formula for calculating color temperature. In this formula, 6600K is calibrated to be the neutral value -- i.e. the colors are not modified in any way when the temperature is set to 6600K.

This may not be scientifically correct, but this is how the software works.
