### ISSUE TITLE
Inverted day/night cycle

### ISSUE THREAD

**Issue by vertigo220** [Tyrrrz/LightBulb#269]
### Version

2.4.7

### Platform

Win 10

### Steps to reproduce

Open and configure program

### Details

Middle of the day and it's dimming as if it's night. Ran preview and as it went into night hours it brightened, then in morning hours dimmed again as if entering night. Completely backwards from what it should be. Sunset is shown as being at ~7am and sunrise at ~11pm, so that's probably the cause, due to the fact they're obviously wrong (not only should they not be wrong but the program should recognize that's not even possible). This wasn't clear at first since I assumed (apparently incorrectly) that the yellow portion was daytime and the blue portion was nighttime, thinking the colors represented sun/moon when apparently they represent the display colors. Also, considering I entered my location to have the sunrise/set times set automatically, clearly that function isn't working properly.

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project

**Comment by Tyrrrz** [comment]
What location did you enter to get those sunrise/sunset times?

**Comment by vertigo220** [comment]
I entered my zip code (sorry, not going to put that here).

**Comment by Tyrrrz** [comment]
> I entered my zip code (sorry, not going to put that here).

I would need at least an approximate location to try to reproduce the issue, assuming it resolves the sunrise/sunset times incorrectly for it.

> Also, when is that possible? I can't think of any situation, and searching for such a situation isn't showing any.

Places near the Arctic circle can experience days without either sunrise or sunset, or both being very close in time to each other. For example, there might be a sunset around 00:00 (midnight), followed by sunrise at like 02:00 (night). Technically, it makes the sunset precede the sunrise.

**Comment by vertigo220** [comment]
Wow, typed up and submitted a response to this hours ago and it's just...gone.

So I used city, state and that seems to be working. There are multiple problems here:

1) It doesn't accept zip codes (most apps like this, e.g. f.lux and weather apps, allow using zip for location).
2) The tooltip indicating what inputs are acceptable is too easy to miss (I didn't see it when initially setting it up), and that info could easily fit in the window so it's always visible, ensuring users know what formats they can and can't use.
3) It accepts invalid inputs, such as zip codes. It should recognize it as invalid and inform the user.
4) Your example still has sunset preceding sunrise, which is always the case. Sunset should never come after sunrise, and a PM sunrise followed by an AM sunset should not be allowed by the app.

**Comment by vertigo220** [comment]
As an aside, are there plans to do more than bug fixes in the future? I tried this because f.lux has a couple annoying issues I was hoping LightBulb either would be better at or might actually improve on with feedback, whereas f.lux development is practically nonexistent, and I was disappointed to find it doesn't seem any better and, in fact, may be worse, for those particular aspects. Unfortunately, in the current state (maintenance mode) it seems I'll have to stick with f.lux.

**Comment by Tyrrrz** [comment]
> 3\. It accepts invalid inputs, such as zip codes. It should recognize it as invalid and inform the user.

I think zip codes are valid too, it just might not accurately recognize the one you put in. It works with everything that OpenStreetMap supports as search arguments. But using your city/state as the input is both easier and more accurate.

> As an aside, are there plans to do more than bug fixes in the future? I tried this because f.lux has a couple annoying issues I was hoping LightBulb either would be better at or might actually improve on with feedback, whereas f.lux development is practically nonexistent, and I was disappointed to find it doesn't seem any better and, in fact, may be worse, for those particular aspects. Unfortunately, in the current state (maintenance mode) it seems I'll have to stick with f.lux.

No, there are no plans. Microsoft effectively killed gamma correction apps by abandoning the underlying Windows API, so LightBulb (like others) lives on borrowed time. Plus it's not a very fun project to work on anymore.
