### ISSUE TITLE
Support for arch linux

### ISSUE THREAD

**Issue by joksik** [Tyrrrz/LightBulb#27]
Do you have plans to make versions for linux?

**Comment by Tyrrrz** [comment]
Not at the moment, since I don't use it myself. The platform specific code is decoupled in a separate assembly though, so it should be easy enough for someone to make a fork.

**Comment by DontUseGithub** [comment]
Hi! Just in case you'll change your mind on GNU/Linux support, please consider packaging it as a [flatpak](https://github.com/flathub/flathub/wiki/App-Submission) - which is a universal packaging system that works on multiple different GNU/Linux Operating Systems. Cheers!

**Comment by Tyrrrz** [comment]
I'll change my mind as soon as Microsoft or someone else comes up with a good cross-platform GUI framework on par with WPF :)

**Comment by Ph0rkoz** [comment]
You could always use QT :)

I'm looking for a replacement to this excellent utility and coming up short. The new version is working great on windows.
