### ISSUE TITLE
Brightness can't get as low as before updating to 23H2

### ISSUE THREAD

**Issue by StLa1** [Tyrrrz/LightBulb#270]
### Version

2.4.7

### Platform

Windows 11

### Steps to reproduce

Run the app in administrator

### Details

I have enabled gamma options (as suggested by the dialog that popped up when first opening after the update) and run the app as admin. The brightness does not go as low as it used to.

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project

**Comment by Tyrrrz** [comment]
How low?

**Comment by StLa1** [comment]
![image](https://github.com/Tyrrrz/LightBulb/assets/63193889/2ffe4318-1b3b-4ae0-88b2-7587540ad2a9)

**Comment by StLa1** [comment]
Any news? @Tyrrrz

**Comment by Tyrrrz** [comment]
> Any news? @Tyrrrz I checked the Windows update change log but didnt find anything related

Unfortunately, I can't replicate the issue.

**Comment by StLa1** [comment]
A reinstall fixed the issue
