### ISSUE TITLE
Automatic brightness adjustment

### ISSUE THREAD

**Issue by Trost123** [Tyrrrz/LightBulb#28]
I find myself constantly switching the brightness during day and evening.
Could you add an option to automatically change brightness along with screen temperature?

Also, it would be neat if auto-brightness change could come at separate time with yellow-tint. I'd prefer to have my screen dimmed around 6p.m., when the sun goes down, but the orange filter is needed only at 23p.m. - one hour before bedtime.
I don't know if it's worth the hassle, but I'd really enjoy that kind of setup.

**Comment by mirh** [comment]
https://msdn.microsoft.com/en-us/library/windows/desktop/dd318953(v=vs.85).aspx
https://msdn.microsoft.com/en-us/library/windows/desktop/dd318979(v=vs.85).aspx
https://msdn.microsoft.com/en-us/library/windows/desktop/dd318917(v=vs.85).aspx
https://msdn.microsoft.com/en-us/library/windows/hardware/dn613947(v=vs.85).aspx
