### ISSUE TITLE
Cannot set certain hotkeys since last update

### ISSUE THREAD

**Issue by DiscworldDeath** [Tyrrrz/LightBulb#284]
### Version

2.4.9

### Platform

Windows 10

### Steps to reproduce

Go to settings > Last item on the right > Click on any hotkey, click button to try setting.

### Details

Since the update earlier today, my hotkey for toggling the program do not work, and I cannot set any hotkeys. Hotkeys previously set appear to have been reset as well - prior to hitting "Reset," the toggle option says "IntlYen".
Tried resetting as well, to no avail. Only had the toggle before, tried other hotkeys as well, no luck.

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project

**Comment by Tyrrrz** [comment]
It seems to work for me. Which hotkeys are you trying to use? Does it work if you try to use any other combination? Also, are you using a QWERTY keyboard or a different layout?

![image](https://github.com/Tyrrrz/LightBulb/assets/1935960/82b41c34-1d9f-41f7-8c64-a0061e90bda9)

**Comment by DiscworldDeath** [comment]
QWERTY keyboard. Been using "page up" previously, tried CTRL+C, just C, etc. Nothing seems to work.

Update: Seems Alt+Q works. Or Alt+C. Seems Ctrl+C didn't work because it's a "windows function" obviously, but "Page up" button not working though it did before seems weird.

**Comment by Tyrrrz** [comment]
Yeah, I can reproduce "Page Up". Ctrl+C/Ctrl+X/Ctrl+V/etc are blocked by Windows. Can you list the hotkeys that you think should work, but don't, so I can look into all of them at once? Or is it just Page Up mainly?

**Comment by DiscworldDeath** [comment]
Shift+numbers/symbols (question mark, square brackets, etc.), everything in the "Center area," which includes page up, page down, End, Home, and everything in the NumPad. Those would be my calls for "most likely to be used, aside from alt+whatever, or ctrl+alt+whatever.

**Comment by Tyrrrz** [comment]
Shift+Numbers/Symbols are probably going to be ignored too because they're commonly used in writing. It would be annoying to accidentally trigger a hotkey while typing in some text. Also, this is the same behavior that was used before.

As for other keys, I'll make sure to include them.
