### ISSUE TITLE
LightBulb stuck?

### ISSUE THREAD

**Issue by mirh** [Tyrrrz/LightBulb#29]
Like.. This morning I resumed from standby, it was stuck to night temp. 
Tonight then, I just realized it didn't already triggered. 
Only manually disabling/enabling unstucked the thing, but I wouldn't know if tomorrow it mightn't happen again. 

Is there anyway I can take a memory dump or something to add more detail (I still haven't restarted the program)?

**Comment by Tyrrrz** [comment]
What version are you using?

**Comment by mirh** [comment]
1.6.3.3
And today it was stuck too.

**Comment by Tyrrrz** [comment]
I'll check it

**Comment by Tyrrrz** [comment]
Can you send your config file?

**Comment by mirh** [comment]
[Configuration.dat](https://github.com/Tyrrrz/LightBulb/files/995774/Configuration.pdf)
Besides, I found out that when I [restart](https://www.monitortests.com/cru-1.3.zip) "graphics" (I wouldn't know if they stop and start gpu, dwm, or what) the problem gets fixed too.

**Comment by Tyrrrz** [comment]
Hey
Does it get unstuck if you press the "preview 24hr cycle" button?

**Comment by mirh** [comment]
Yes.

**Comment by mirh** [comment]
Ok, update. 
I.. enabled/disabled (aka unstuck) the program earlier today (like around 7pm instead of 23 like - when I always notice/realize/remember of the problem). 
And, fairly, it got set to like.. 5000K or something like that. And, just because, I had left the "24-h preview" button toggled enabled. 
After 2 hours it still was set on that value though, and further pressing 24h preview had no effect this time.

**Comment by mirh** [comment]
Another hint: I enabled the 24-h preview this evening, and I noticed the slim orange bar progressed like 10-20 pixels, then stopped (irregardless of how many times I then tried to toggle the button)

**Comment by Tyrrrz** [comment]
This is so confusing. Have you tried if it works with default settings? I noticed you have your min. temperature manually set.

**Comment by mirh** [comment]
Yes, no success. 
I uploaded process fulldump [here](https://drive.google.com/file/d/0B5Fd8kTRtzaBRnFIc1NCNmkzWGc/view?usp=sharing) if it can help.

**Comment by Tyrrrz** [comment]
I tested it on two machines, trying sleep, hibernate, lock screen, leaving the PC for 2 days and it seems to work as expected.
Can you replicate your issue on any other PC?

**Comment by mirh** [comment]
I think my uptime is around 2 or 3 weeks (also including standby time in the count). 
I also have another computer with similar cycles (aka no shutdowns) I could test, yes, but unfortunately it has Vista. 
...
Whose "un-suport" I'm not sure if being actually technical or just about you not caring about bug reports from there though?

**Comment by Tyrrrz** [comment]
I meant there was 2 days of standby, the PC itself ran for 5 days without LightBulb getting stuck.
I honestly don't remember whether LightBulb works on Vista or not. If you can install .NET framework 4.5.2 there then it probably should.

**Comment by mirh** [comment]
> I think my uptime is around 2 or 3 weeks

Ok, correction, I just came home and task manager is like ticking for 17:09:47:59. So it's like 2 weeks and half, *not* counting for standby. So, an educate guess of like middle April being last time I started it, and firsts of May when I reported it.. 
I guess like 3 weeks it's the time span?

>  If you can install .NET framework 4.5.2 there then it probably should.

It even supports 4.6 for all that it matters, and indeed it works!
I have set a really slight dim not to disturb my dad, but I hope it might do it as well.

**Comment by Tyrrrz** [comment]
So I was eating and I think I have an idea of what could be the problem. Will try this week if it works.

*Note to self: device context might be becoming stale*

**Comment by mirh** [comment]
Of course the funny thing is that to test the fix I'll have to restart the program 😛

**Comment by Tyrrrz** [comment]
See you in 2 weeks after that then ;)

**Comment by Tyrrrz** [comment]
[Try this](http://tyrrrz.me/dl/LightBulb_Install_1.6.3.3_T.zip), see if it gets stuck

**Comment by Tyrrrz** [comment]
2 weeks have passed, any news? 😛

**Comment by mirh** [comment]
Well, on the one hand I had no problems.. On the other, it's even true that -contrarily than in april/may- I not-so-rarely "interacted" with the program.

**Comment by mirh** [comment]
It happened agaaaaainnn 
On the 7 1.6.3.3_T computer.

**Comment by mirh** [comment]
Ok correction. 
Temperature does seems to increase and decrease normally and all. 

Only 24-h preview seems fucked atm.

**Comment by Tyrrrz** [comment]
How is it fucked? Not changing the gamma or?

**Comment by mirh** [comment]
It doesn't do anything. 
Ie, gamma doesn't change, and also the little "yellow bar" doesn't move. 

Aside of that, the program still works effectively.

**Comment by Tyrrrz** [comment]
Did this also start happening only after a long time has passed?

**Comment by mirh** [comment]
Well, I guess so. 
ProcExp says last time I started lightbulb was 30 May.

**Comment by Tyrrrz** [comment]
Did you manage to replicate it on some other computer?

**Comment by mirh** [comment]
I don't have others :s
Or better, the only other I have has the memory bomb.

**Comment by mirh** [comment]
I'm quite joyful to report I could get lightbulb to bug in, more or less, a day and half. 

So.. well whatever you'll want to test it shouldn't take too long to confirm.

**Comment by mirh** [comment]
Could [this](https://github.com/0xd4d/dnSpy) help?

**Comment by Tyrrrz** [comment]
You can try

**Comment by Tyrrrz** [comment]
Still happens on 1.6.3.6?

**Comment by mirh** [comment]
Ok so.. I just closed lightbulb (for reasons) and realized I was on a 3-4 weeks spree of keeping it running. 
SEEMINGLY I wasn't having any more problems... So, I don't know *solved*?

**Comment by mirh** [comment]
_Surpriiise!_

**Comment by mirh** [comment]
So.. as another random datum, if I rotate the screen, gamma immediately sets to the right value. 
"Stuck/unstuck" aren't probably the right terms then, since it actually seem to be *always* in the stuck position - but in the "instantaneous time window" of whatever special event (24-h cycle, on/off toggle, resolution change) I'm sending it.

**Comment by mirh** [comment]
Whatever timer the program use seems also to be fucked up or something. 
I clicked on "disable for a minute".. And it like stayed off for 5 seconds. 

On a second attempt timing was correct.

**Comment by mirh** [comment]
I stand correct. Lightbulb is batshit stuck period. 
I cannot disable it at all now.

**Comment by mirh** [comment]
*Still a thing*

**Comment by Tyrrrz** [comment]
Can't do much about it :(

**Comment by mirh** [comment]
Would it help anything if I said every day at 18:00 the thing moves to ~4900K?

**Comment by Tyrrrz** [comment]
What's the min/max temperature and what's the sunset time?

**Comment by Tyrrrz** [comment]
So at 18:00 it goes from 1300 to 4900?

**Comment by mirh** [comment]
```
System.Reflection.TargetInvocationException was unhandled
  HResult=-2146232828
  Message=Exception has been thrown by the target of an invocation
  Source=mscorlib
  StackTrace:
       in System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
       in System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
       in System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
       in GalaSoft.MvvmLight.Helpers.WeakAction.Execute()
       in GalaSoft.MvvmLight.CommandWpf.RelayCommand.Execute(Object parameter)
       in MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
       in System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
       in System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       in System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
       in System.Windows.Threading.DispatcherOperation.InvokeImpl()
       in System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
       in System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       in System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       in System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       in MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
       in System.Windows.Threading.DispatcherOperation.Invoke()
       in System.Windows.Threading.Dispatcher.ProcessQueue()
       in System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       in MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       in MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
       in System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       in System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
       in System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
       in MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
       in MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
       in System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
       in System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
       in System.Windows.Application.RunDispatcher(Object ignore)
       in System.Windows.Application.RunInternal(Window window)
       in System.Windows.Application.Run(Window window)
       in LightBulb.App.Main()
  InnerException: 
       HResult=-2146233086
       Message=Specified argument was out of the range of valid values.
Nome parametro: blue
       ParamName=blue
       Source=LightBulb
       StackTrace:
            in LightBulb.Models.ColorIntensity..ctor(Double red, Double green, Double blue)
            in LightBulb.Models.ColorIntensity.FromTemperature(UInt16 temp)
            in LightBulb.Services.TemperatureService.UpdateGamma()
            in LightBulb.Services.TemperatureService.set_Temperature(UInt16 value)
            in LightBulb.Services.TemperatureService.UpdateTemperature(Boolean forceInstantSwitch)
            in LightBulb.Services.TemperatureService.set_IsRealtimeModeEnabled(Boolean value)
            in LightBulb.ViewModels.MainViewModel.set_IsEnabled(Boolean value)
            in LightBulb.ViewModels.MainViewModel.<.ctor>b__52_5()
       InnerException: 
```
Today, while as usual I had to enable/disable it, it crashed
[LightBulbdump.zip](https://github.com/Tyrrrz/LightBulb/files/3561266/LightBulbdump.zip)

**Comment by Tyrrrz** [comment]
Hey, can you try builds from [here](https://ci.appveyor.com/project/Tyrrrz/LightBulb/build/artifacts) to see if it helps?

**Comment by mirh** [comment]
Sure. 
But see you in another year or so with meaningful data :smile:

**Comment by mirh** [comment]
Well, isn't it funny. Now it uses to crash more or less on wake from standby. 
```
Exception: System.Net.WebException
   in System.Net.HttpWebRequest.EndGetResponse(System.IAsyncResult)
   in System.Net.Http.HttpClientHandler.GetResponseCallback(System.IAsyncResult)

Exception: System.Net.Http.HttpRequestException
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   in LightBulb.Services.LocationService+<GetLocationAsync>d__2.MoveNext()
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   in LightBulb.ViewModels.RootViewModel+<>c__DisplayClass55_0+<<-ctor>b__4>d.MoveNext()
   in System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_1(System.Object)
   in System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
   in System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   in System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   in System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   in System.Threading.ThreadPoolWorkQueue.Dispatch()
   in System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

**Comment by mirh** [comment]
With visual studio attached before suspending, in addition to the aforementioned
```
System.Net.Http.HttpRequestException
  HResult=0x80131500
  Messaggio=An error occurred while sending the request.
  Origin=mscorlib

Internal exception 1:
WebException: The remote name could not be resolved.: 'ip-api.com'
```

**Comment by Tyrrrz** [comment]
Hey @mirh does it happen after rework?

**Comment by mirh** [comment]
The program has been running continuously just for 10 days now...
We'll see
