### ISSUE TITLE
Settings do not save

### ISSUE THREAD

**Issue by bnbaz** [Tyrrrz/LightBulb#3]
Really neat. Settings do not save on my computer. I'm not running the program as admin, using Windows 10 64-bits.

I changed the settings by editing the .dat and everything seems to be fine now. So I figure it's a saving issue rather than a reset issue. I just re-tried it settings are now saved via the UI. Could it be the fact that I did not exit LightBulb before shutting down my computer? Cannot test at the moment.

**Comment by Tyrrrz** [comment]
Settings are saved when the program closes, however when shutting down your computer, it should also save, because normally Windows sends exit messages to all applications. Did LightBulb, by any chance, appear in the "Program preventing Windows from shutting down" screen?

**Comment by bnbaz** [comment]
I did not notice it, that is: I did not force-quit LightBulb.

**Comment by Tyrrrz** [comment]
You are right, it indeed doesn't save. I committed a fix, will test for a while before I add it to release.

**Comment by Tyrrrz** [comment]
Fixed in latest commits, should be in release soon
