### ISSUE TITLE
'Tooltip' tooltip shown in notification

### ISSUE THREAD

**Issue by mirh** [Tyrrrz/LightBulb#30]
![immagine](https://cloud.githubusercontent.com/assets/9366725/26405211/ec236964-4094-11e7-8da8-8c1e72b1ba47.png) <-- this was taken in 7
I just now noticed the thing, since in Vista (when you are in the "customize notification area" panel) only the later is shown. 
Guess like that should say Lightbulb too?
Possibly
https://msdn.microsoft.com/en-us/library/windows/desktop/hh298404(v=vs.85).aspx
https://msdn.microsoft.com/en-us/library/062478za(v=vs.110).aspx

**Comment by Tyrrrz** [comment]
Can you make a bigger screenshot? I'm not sure where this is coming from.

**Comment by Tyrrrz** [comment]
Oh yeah, you're right. This is how it (incorrectly) looks on W10.

![2017-05-24 17_05_02-settings](https://cloud.githubusercontent.com/assets/1935960/26407209/27ad6b3e-40a3-11e7-8e6f-4a032d562e8a.png)
