### ISSUE TITLE
Daytime kelvin gets reset when going into settings if you are above slider maximum

### ISSUE THREAD

**Issue by JdotCarver** [Tyrrrz/LightBulb#308]
### Version

2.5.1

### Platform

Windows 10

### Steps to reproduce

![image](https://github.com/Tyrrrz/LightBulb/assets/7091684/a8fdd64c-0736-4978-bd5a-178b8df05f33)

- Go into app settings
- Set "Day-time color temperature:" to 8200
- Tab
- The change occurs
- Click save
- Come back to settings
- It's back to 6600

### Details

This used to work fine.
And this currently works for the "Night-time color temperature" slider.

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project

**Comment by Tyrrrz** [comment]
The fix will be available in the next release. Thanks for reporting.
