### ISSUE TITLE
Problems with fullscreen

### ISSUE THREAD

**Issue by ProManicx** [Tyrrrz/LightBulb#31]
Hi there,
Ok let me tell you this is the best of is kind, works like a boss, the one problem i have find is for some reason doesn't work in fullscreen, especial in  games. the only way to work is to put the  day-time color all the way down. please fix this :(

**Comment by mirh** [comment]
Just yesterday, I had it messing up with my BFBC2 match, so maybe it's your specific game that wants to override the thing.

**Comment by ProManicx** [comment]
nop is not!

**Comment by Tyrrrz** [comment]
It should definitely work in fullscreen. Maybe the specific games you're playing are overriding gamma themselves.

**Comment by ProManicx** [comment]
So far 2 games not working, CSGO and Guil Of Wars.

**Comment by Tyrrrz** [comment]
Just to make sure, you don't have "Pause when fullscreen" enabled?

**Comment by ProManicx** [comment]
http://imgur.com/a/BfeNj

**Comment by mirh** [comment]
I just tested CS:GO and you were right indeed. 
That's just because it overrides OS with I think whatever is set in mat_monitorgamma setting

And you can use -nogammaramp launch options to fix that. 
Other games aren't going to be so.. 'Tweakable' though, and I'm not sure it should be this program business to override the override of the override. 
You may want to check [one of these tools](https://pcgamingwiki.com/wiki/Talk:Microsoft_Windows#Ignored_color_calibration_profiles_.2B_saturation_enhancer_3428) though.

**Comment by Tyrrrz** [comment]
@ProManicx 
>the only way to work is to put the day-time color all the way down

does this actually help?

**Comment by Tyrrrz** [comment]
Closing because there's not really much I can do about gamma conflicts

**Comment by mirh** [comment]
Not even detecting them?

**Comment by Tyrrrz** [comment]
How would it detect it?

**Comment by mirh** [comment]
I'd have been expecting some service/driver somewhere to be hookable and knowable with enough kernel-fu.

**Comment by Tyrrrz** [comment]
Not sure how well that's possible or how to do it. Right now it can "detect" gamma changes, but it can only do so on an interval (known as polling), but even then there will be gamma conflicts between two programs trying to change it for themselves.

**Comment by mirh** [comment]
I wasn't necessarily talking about official APIs though. 
Ie: I know [many](https://github.com/nefarius/ViGEm) [projects](https://github.com/elishacloud/dxwrapper) that checked the relevant windows dlls and found oceans of undocumented functions. 

My supposition was that somewhere Windows had something 'registering' who currently has the handle on gamma (or if not any, a log with last "caller")

**Comment by Tyrrrz** [comment]
Yeah maybe. I definitely don't want to spend time doing that though. :p
