### ISSUE TITLE
"This app can't run on your PC"

### ISSUE THREAD

**Issue by Xeogin** [Tyrrrz/LightBulb#310]
### Version

2.5.2

### Platform

Windows 11

### Steps to reproduce

Install application (I use winget)
Try to launch it

### Details

I was using version 2.4.12 without issue and just updated to the latest version and it no longer launches. I tried running as admin, running the compatibility troubleshooter, uninstalling then reinstalling, and the result is the same. The issue is also present with the 2.5.1 installer. Oddly the 2.4.12 installer somehow shows as version 2.5.1 when launched?

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project

**Comment by MononeV** [comment]
This is because the download url is directed to the arm64 version for all architectures.
@Tyrrrz Since new architectures are introduced, there might be additional work need to be done on the winget side.

**Comment by MononeV** [comment]
> @MononeV which download URL are you referring to?

As refer to https://github.com/microsoft/winget-pkgs/blob/master/manifests/t/Tyrrrz/LightBulb/2.5.2/Tyrrrz.LightBulb.installer.yaml, the download link is https://github.com/Tyrrrz/LightBulb/releases/download/2.5.2/LightBulb-Installer.win-arm64.exe

**Comment by Tyrrrz** [comment]
> > @MononeV which download URL are you referring to?
> 
> As refer to [microsoft/winget-pkgs@`master`/manifests/t/Tyrrrz/LightBulb/2.5.2/Tyrrrz.LightBulb.installer.yaml](https://github.com/microsoft/winget-pkgs/blob/master/manifests/t/Tyrrrz/LightBulb/2.5.2/Tyrrrz.LightBulb.installer.yaml?rgh-link-date=2024-05-31T15%3A17%3A55Z), the download link is [`2.5.2` LightBulb-Installer.win-arm64.exe (download)](https://github.com/Tyrrrz/LightBulb/releases/download/2.5.2/LightBulb-Installer.win-arm64.exe)

I see, yes, that's incorrect. I didn't notice you mentioned you were using winget to install/update.

The package manifest in the winget catalog is managed by the community, not by me personally. I will create an issue there and close this one.

**Comment by Tyrrrz** [comment]
https://github.com/microsoft/winget-pkgs/pull/155887

**Comment by Tyrrrz** [comment]
Should be fixed now
