### ISSUE TITLE
Uninstall LightBulb causing the system color manager broken

### ISSUE THREAD

**Issue by inputrc** [Tyrrrz/LightBulb#33]
**Reproduce**
1. Backup your registry keys, especially the key `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\ICM`;
2. Uninstall LightBulb using the uninstaller;
3. Open Run (Win + R), type `colorcpl.exe' and return;
4. Switch to the `Advanced` tab, will show up an error.

**Cause**
The LightBulb uninstaller seems to delete a whole registry key of ICM which will make `colorcpl.exe` throw an error in Advanced tab.

The code I checked in `Deploy/Installer/Installer.iss`, and found:
```
[Registry]
; Change valid gamma range
Root: HKLM; Subkey: "Software\Microsoft\Windows NT\CurrentVersion\ICM"; ValueType: dword; ValueName: "GdiICMGammaRange"; ValueData: "256"; Flags: uninsdeletekey
```

**Comment by Tyrrrz** [comment]
Hmm I wonder if InnoSetup can backup/restore registry keys :/

**Comment by Spiritreader** [comment]
Thank you so much for posting this. 
Windows, as always, does a very bad job in telling the user what exactly is wrong. 
"The system cannot find the file specified" isn't very helpful.

My Windows color management broke after uninstalling LightBulb 1.6.3.4, which deleted the ICM reg-key.

I was able to restore the functionality of WCM after re-adding said registry key with its subkeys which I retrieved from another Windows computer with color management windows defaults.
This successfully restored functionality.

Here's what I added for anyone who still encounters this issue:

```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\ICM]

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\ICM\Calibration]
"CalibrationManagementEnabled"=dword:00000000
"DisplayCalibrator"="%SystemRoot%\\System32\\DCCW.exe"

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\ICM\RegisteredProfiles]
"camp"="D65.camp"
"riac"="MediaSim.gmmp"
"rip"="Photo.gmmp"
"rirc"="Proofing.gmmp"
"ris"="Graphics.gmmp"
"ri"=dword:00000000
```
