### ISSUE TITLE
Application does not change color temperature on external monitors on Windows 11 for ARM

### ISSUE THREAD

**Issue by PaxITIS** [Tyrrrz/LightBulb#337]
### Version

v2.6

### Platform

Windows 11 for ARM

### Steps to reproduce

Start the application, choose the color temperature and see the result

### Details

If one installs this application on a Windows 11 for ARM PC (Like my Surface Laptop 7) one quickly realizes that the application can handle color temperature change only on the main monitor of the laptop and not on the external monitors that continue to remain with cold colors

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project

**Comment by Tyrrrz** [comment]
I don't think this issue is related to the CPU architecture, but rather to the adapter used to connect the external monitor. Is it DisplayPort by any chance?

**Comment by Tyrrrz** [comment]
In any case, please see the troubleshooting guide: https://github.com/Tyrrrz/LightBulb/wiki/Troubleshooting

If the issue persists, please re-open.

**Comment by MatthewCGalbraith** [comment]
> I don't think this issue is related to the CPU architecture, but rather to the adapter used to connect the external monitor. Is it DisplayPort by any chance?

It is all adapters, seemingly. It appears to be a Qualcomm driver issue where it does not allow for color profiles, unlike other GPU manufacturers. No program that adjusts color seems to work - LightBulb, F.Lux, SunsetScreen...not even the built in Windows Night Mode. 

I'm not sure if there is any workaround, but it would be greatly appreciated if it could be looked into.
