### ISSUE TITLE
Flashing when opening menus in game (Not Full Screen)

### ISSUE THREAD

**Issue by hdiepSun** [Tyrrrz/LightBulb#35]
Hello! I'm on windows 10 with the latest updates, and the latest release of LightBulb. I have a minor issue where if I'm opening any sort of menu in Wizard101 -- the screen flickers back to non-yellow for 1-2 seconds and then back.

**Comment by Tyrrrz** [comment]
Do you have "Pause when fullscreen" enabled? Maybe when Wizard101 opens a menu, it spawns a fullscreen window for whatever reason...

**Comment by hdiepSun** [comment]
The option isn't enabled, and it turns back to being yellow after 1-2 seconds.

**Comment by Tyrrrz** [comment]
In that case it means something (possibly Wizard101) was changing the gamma. LightBulb updates the gamma on a fixed interval basis to make sure the settings weren't changed by some other application. Unfortunately, there is no trigger it could use to detect such changes instantly, so it just has to poll once in a while instead. The setting responsible for this is called "Gamma polling". You can make it more frequent by [manually changing the config file](https://github.com/Tyrrrz/LightBulb/wiki/Config-file) and overriding the "GammaPollingInterval", but updating gamma too often may negatively impact performance.

**Comment by mirh** [comment]
Same as  #31?

**Comment by Tyrrrz** [comment]
@mirh yes, except in case with games they are continuously changing gamma, while Wizard101 seems to only do it once occasionally.

**Comment by mirh** [comment]
Best thing (if possible) would just be to detect these applications and warn the user. 

Otherwise engaging in a "race for the most-est important program ever" seems masochistic.

**Comment by Tyrrrz** [comment]
@hdiepSun nope. The gamma API in Windows is pretty terrible to say the least.

**Comment by hdiepSun** [comment]
Hm, that's a bummer. I was having issues with F.Lux as well -- and I hoped moving over to lightbulb would fix it. Nevertheless, Lightbulb is orders of magnitude better than F.Lux.

**Comment by Tyrrrz** [comment]
Thank you.
I would be very happy to get rid of polling entirely, but unfortunately we don't have that options because of cases exactly like this. :(
