### ISSUE TITLE
Enable/disable does nothing while smoothing is on

### ISSUE THREAD

**Issue by mirh** [Tyrrrz/LightBulb#36]
Still me as always 🙃

**Comment by Tyrrrz** [comment]
Works for me ¯\\\_(ツ)\_/¯

**Comment by mirh** [comment]
😭😭

**Comment by Tyrrrz** [comment]
What about this one? Related to #42?

**Comment by mirh** [comment]
If any, this would be the contrary.

**Comment by Tyrrrz** [comment]
Why contrary? Seems like the same problem, except the other one is also involving hotkeys

**Comment by mirh** [comment]
> Enable/disable does not work when smoothing is off
> Enable/disable does nothing while smoothing is on

@('_')@

**Comment by Tyrrrz** [comment]
Ah oops.

**Comment by Tyrrrz** [comment]
@mirh there was a fix to timers in 1.6.3.6, it could have had an impact on this. Can you try with new version?

**Comment by mirh** [comment]
Yes, but if my guess is correct, I'll need the [usual](https://github.com/Tyrrrz/LightBulb/issues/29) 2-3 weeks of uptime before I can have some pretense of having actually reproduced the right conditions

**Comment by mirh** [comment]
Let's hope magic also solved this.
