### ISSUE TITLE
Lightbulb gets disabled on desktop with more than a single monitor

### ISSUE THREAD

**Issue by mirh** [Tyrrrz/LightBulb#37]
After screen turns off after the usual 2-3 minutes, when I move mouse and it lights up..  LB turns is off (until I toggle enabled/disable). 
If I duplicate the displays (instead of "extend") it all works correctly.

**Comment by Tyrrrz** [comment]
Do you have gamma polling disabled?

**Comment by mirh** [comment]
It's the only option I had enabled actually.

**Comment by Tyrrrz** [comment]
I'm honestly impressed by how you manage to find this issues lol

**Comment by mirh** [comment]
Don't tell me... 🤦‍

**Comment by Tyrrrz** [comment]
Does it all happen on the same cursed computer? 🤔

**Comment by mirh** [comment]
Yeees, on the same almost-2-months-long session.

**Comment by Tyrrrz** [comment]
Not supposed to be related. Just curious, what GPU do you have?

**Comment by mirh** [comment]
Radeon 7750 with February/March drivers.

**Comment by mirh** [comment]
Correction: not only whatever I stated in the OP, it like seems to freeze. 
Ie: when I have the two extended monitors, temperature stops to decrease or increase. 

Once I put back to duplicate, I can get all the way down

**Comment by Tyrrrz** [comment]
Yeah I think it's part of the same mysterious issue you have been reporting

**Comment by Tyrrrz** [comment]
Did you find any clues regarding this? Is this duplicate of #29?

**Comment by mirh** [comment]
Let's say it's better if we turn the page
