### ISSUE TITLE
Run Hidden and portable

### ISSUE THREAD

**Issue by Ba11istix** [Tyrrrz/LightBulb#40]
you already have users editing their own config, so simple feature request: can a 'hidden' value be added so than no icon is displayed in the taskbar - obviously this would be an advanced feature (no way to quit) so I would think that it not being accessible in the GUI is fine.

Only other thing - can the program look for a configuration file in its own folder by itself rather than having to specify portable (ie it looks and uses if found, if not then assumes no portable), or even some dummy file ('portable.blank' or something) which if found will run as portable. seems simpler than using the batch file to launch, means that in every case you just run the exe (after registry file).

**Comment by Tyrrrz** [comment]
1. Why would you need the "hidden" feature? Just curious.
2. What happens if it doesn't find config in either places? How is launching an .exe simpler than launching a .bat file? 🤔

**Comment by Ba11istix** [comment]
1. Hidden just because I like to have a clean notification tray; if I don't need to click on it, I don't want to see it. But then I'm fussy and also want to show all icons at all times rather than using the hide thing in Windows. I run a few third party things on all my computers (Ditto, WizMouse, Greenshot), all portable and hidden. Ditto has its icon appear when it loads so I have a thread for them as well, but hidden is an option which I use.

2. I would have thought behaviour could be as follows:

a. Program looks for configuration file in own directory.

If found, this is what is used.

If not found, program looks for configuration file in app data.

If found this is what is used.

If not found make a configuration file in app data.

Then a setting the user can toggle to 'make portable' in which case the program saves all its settings to its app data configuration and copies it to local folder. Then when it next launches it will find the local config and thus be running in portable mode.

**Comment by Ba11istix** [comment]
And I agree launching a bat file is easy enough, but to launch a single exe no matter the use case is easier again. And it means that if you make a shortcut to get the nice icon etc without having to change it yourself.

**Comment by Tyrrrz** [comment]
You can add command line arguments to shortcut, like this:
![2017-08-30 16_58_23-lightbulb properties](https://user-images.githubusercontent.com/1935960/29876104-833a3bbe-8da4-11e7-8877-16a81cfd4457.png)
That way you don't need to use the bat file.

**Comment by Tyrrrz** [comment]
Overall I think the requests add too much complexity for very little gain, so I doubt I will implement it.
