### ISSUE TITLE
Enable/disable hotkey does not work when smoothing is off

### ISSUE THREAD

**Issue by rgfx** [Tyrrrz/LightBulb#42]
Thanks for the great program, Fl.ux's hotkey disable only works for 1 hour at time.

I like to use Lightbulb when am programming at all times of the day. But I can switch to design very quickly. I have it set all the way down. As such the transition takes a whole 6 seconds when I toggle :) 

Just being nit picky, but I would happy with more imitate transition.

**Comment by Tyrrrz** [comment]
Hi.
You can turn off temperature smoothing in settings. Is that what you wanted?

**Comment by rgfx** [comment]
Yes, that's what I wanted. However, it only switches once when I set that. I am using a hotkey. Its it getting toggled cause the icon spins, but it won't change the screens color. Windows 7.

**Comment by Tyrrrz** [comment]
Hmm. The on/off smoothing transition takes the same amount of time regardless of your min/max temperatures and is defined by `"MaximumTemperatureSmoothingDuration"` in config file.
I still don't get what you meant by `However, it only switches once when I set that.`

**Comment by rgfx** [comment]
Made a video doesn't show the overlay :( https://ufile.io/zdyr5

First click screen changes color, Then temperature smoothing is clicked,  following clicks change nothing.

**Comment by Tyrrrz** [comment]
Can you upload the video to https://streamable.com/ instead?

**Comment by rgfx** [comment]
If you insist, as I mentioned previously. The video doesn't show the overlay. 

https://streamable.com/s/i83tn/jrazbs

**Comment by Tyrrrz** [comment]
So when it says it switches to 2500k it doesn't actually change gamma?

**Comment by rgfx** [comment]
Nope, the gamma does not change.  Only when the smoothing is selected.

**Comment by Tyrrrz** [comment]
Can't replicate :/

**Comment by Tyrrrz** [comment]
@rgfx there was a fix to timers in 1.6.3.6, it could have had an impact on this. Can you try with new version?

**Comment by rgfx** [comment]
Hi,

Still only switching once, off not on. Then I can't get the colors to change again. Only when I go to general and slide the night color temps . Transition duration is set to 0. 

It works when I use temperature smoothing like before, but I don't get that immediate change that am after. Like I said before, being nitpicky, but it would be nice...

Anyway thanks for checking back, use your program everyday.

**Comment by Tyrrrz** [comment]
@rgfx hope you're doing well.
Would you be able to check the [latest master build](https://github.com/Tyrrrz/LightBulb/suites/298976768/artifacts/260352) to see if this problem is still around?

**Comment by Tyrrrz** [comment]
Closing as I'm assuming this is fixed by latest changes. Please reopen if it reproduces.
