### ISSUE TITLE
How to powerboot？

### ISSUE THREAD

**Issue by MupoEng** [Tyrrrz/LightBulb#43]

**Comment by Tyrrrz** [comment]
What's powerboot?

**Comment by MupoEng** [comment]
start automatically

**Comment by mirh** [comment]
It already does?

**Comment by MupoEng** [comment]
I use portable edition, not work. Now it works

**Comment by mirh** [comment]
Portable version not interfering with system seems "work as expected"-

**Comment by Tyrrrz** [comment]
Yeah, like @mirh said, portable version is not meant to do that. Use the installer instead or add it to startup manually.
