### ISSUE TITLE
Exclude Windows 8/8.1 start screen from "pause when fullscreen"

### ISSUE THREAD

**Issue by zmni** [Tyrrrz/LightBulb#46]
I know it work as intended (full brightness on fullscreen window). But please make an exception for the start screen. Need to close my eyes or look some where else on every transition back from start screen to the desktop. Really annoying.

**Comment by mirh** [comment]
https://stackoverflow.com/questions/33105881/how-to-detect-windows8-1-start-menu
Guess like one could even implement an user blacklist at this point

**Comment by Tyrrrz** [comment]
We already do it for the desktop because it also appears as a full screen window.
Maybe we can use the same filtering method (window class name) for the start menu.

**Comment by Tyrrrz** [comment]
Can someone help me get the window class of the start menu in Windows 8?

**Comment by zmni** [comment]
Something in this cpp code? https://pastebin.com/in0rhaDg.

**Comment by Tyrrrz** [comment]
Can you test if this helps?
[Test.zip](https://github.com/Tyrrrz/LightBulb/files/1292840/Test.zip)

**Comment by Tyrrrz** [comment]
@zmni did you have a chance to try?

**Comment by DerinQyu** [comment]
Hi windows 8.1 user here.

Tried the test.zip, lightbulb still turns off on start screen.

**Comment by Tyrrrz** [comment]
@zmni @DerinQyu 
Sorry for late reply. Can you try this one instead?
[Test.zip](https://github.com/Tyrrrz/LightBulb/files/1519337/Test.zip)

**Comment by Tyrrrz** [comment]
Found a win8 machine to test it on, seems to work

**Comment by zmni** [comment]
Sorry for very late reply, had some work to do.

Yes, latest [Test.zip](https://github.com/Tyrrrz/LightBulb/issues/46#issuecomment-348307939) work perfectly now, thanks a lot for the fix.
