### ISSUE TITLE
You can put Space and Enter in hotkey editor box

### ISSUE THREAD

**Issue by Tyrrrz** [Tyrrrz/LightBulb#47]

**Comment by mirh** [comment]
And it is a bug because?

**Comment by Tyrrrz** [comment]
Because you're not supposed to be able to use keys you use to type text as global hotkeys.

**Comment by mirh** [comment]
User tastes? 😄 
But what about, say, CTRL+ENTER ?

**Comment by Tyrrrz** [comment]
I can't imagine someone would want to block a commonly-used key like that. On the other hand, I can imagine someone putting it as a hotkey accidentally and then wondering why suddenly their Space key isn't working. :/

Ctrl+Enter is allowed, Enter by itself isn't.
