### ISSUE TITLE
Manually set geolocation

### ISSUE THREAD

**Issue by neomodern** [Tyrrrz/LightBulb#48]
I recently switched from f.lux after discovering that it has started collecting usage data and it was made opt-out and am glad to have found LightBulb.

One feature that I always used on f.lux is a custom geolocation - I work nights so standard sunrise/sunset times don't work well for my body clock. I used to set the geolocation as somewhere across the other side of the world. I'd be grateful if this could be added as a feature, thanks!

**Comment by Tyrrrz** [comment]
If manually setting sunrise/sunset times is not enough, you can refer to [this](https://github.com/Tyrrrz/LightBulb/wiki/Manual-geolocation)
