### ISSUE TITLE
Incompatibilities between LightBulb and MAME

### ISSUE THREAD

**Issue by anewuser** [Tyrrrz/LightBulb#49]
LightBulb disables/restarts itself when launching a game on MAME 0.189 or closing the emulator, even though I haven't checked the option to disable it on fullscreen.

LightBulb 1.6.3.4
MAME 0.189 64-bit
Windows 10  64-bit

**Comment by Tyrrrz** [comment]
Is gamma polling turned on?

**Comment by anewuser** [comment]
Yes, I toggled it but the problem persists.

**Comment by Tyrrrz** [comment]
It seems that MAME and LightBulb are both fighting for control over system gamma. Similar problems seem to occur with other applications, as seen here #35. Not sure what exactly there can be done to fix it.
