### ISSUE TITLE
This program shouldn't require restart of whole computer.

### ISSUE THREAD

**Issue by TETYYS** [Tyrrrz/LightBulb#5]
Last step of installer suggests that you restart the computer.

edit: did it just try to restart when i selected NO..?

**Comment by Tyrrrz** [comment]
The restart is required for HKLM registry keys to take effect. InnoSetup doesn't have a way to prompt restart only if the key was actually overwritten. If you had installed LightBulb or a similar application before (f.lux, RedShift, etc) then the registry key should already be there and the restart is indeed unnecessary.

> edit: did it just try to restart when i selected NO..?

no

**Comment by Tyrrrz** [comment]
In latest releases, LightBulb no longer asks for computer restart, it messages the shell asking to update system variables instead.
