### ISSUE TITLE
Lightbulb disabled after monitor turns off

### ISSUE THREAD

**Issue by Grantapher** [Tyrrrz/LightBulb#50]
Whenever I come home my desktop (not off, sleeping or hibernating. The monitors just turn off), I wake my monitors and lightbulb is not applied. It doesn't say it's disabled, but I have to click around in the settings for it to apply again.

**Comment by Tyrrrz** [comment]
Is gamma polling turned on?

**Comment by Grantapher** [comment]
No, I'll try turning it on and see if that changes this.

**Comment by Tyrrrz** [comment]
Did it help?
