### ISSUE TITLE
Geographical location is undetermined

### ISSUE THREAD

**Issue by jcpro** [Tyrrrz/LightBulb#51]
I'm seeing "Geographical location is undetermined" on both installs of Lightbulb, Laptop and Desktop.

**Comment by Tyrrrz** [comment]
What does it show when you go here? http://freegeoip.net/?q=178.159.236.41

**Comment by jcpro** [comment]
Ah, looks like Pi-Hole is blocking http://freegeoip.net 
;\

**Comment by Tyrrrz** [comment]
Hmm it reminds of #41

**Comment by Tyrrrz** [comment]
I have no idea why freegeoip appears on some ad-blocking lists 🤔

**Comment by jcpro** [comment]
I think it's more potential for location tracking.  In cases like this, it's fine.  Now if I can just get choco to upgrade their sources I could get the latest version of Lightbulb

**Comment by Tyrrrz** [comment]
I think they don't upgrade on their own. Either me or someone else has to do it. I gave up updating them after they took 3 months to confirm one release.
