### ISSUE TITLE
Sunset time is not updating when internet sync is on

### ISSUE THREAD

**Issue by sha-265** [Tyrrrz/LightBulb#52]
I turned on the internet sync option, but the sunset time is stack on the sunset time when I first set Lightbulb.

Any idea way?

**Comment by Tyrrrz** [comment]
Not sure, maybe it can't parse the response for some reason.

You can try going to http://freegeoip.net/, get your latitude and longitude and then go to http://api.sunrise-sunset.org/json?lat=YOUR_LATITUDE&lng=YOUR_LANGITUDE&formatted=0 and then copy paste the results here so we can check what can be wrong with it.

**Comment by sha-265** [comment]
I tried your suggestion, and I got the currect sunset time from sunrise-sunset.org API.

**Comment by Tyrrrz** [comment]
Can you try deleting the config file entirely and see if it helps?

It can be found in `%appdata%/LightBulb`

**Comment by sha-265** [comment]
After deleting the config file the location is "not set", and accordingly the internet sync feature is not working.

**Comment by Tyrrrz** [comment]
Could it be that it's somehow related to https://github.com/Tyrrrz/LightBulb/issues/51?

**Comment by sha-265** [comment]
Maybe, but before deleteing the config file I got location set in app.

**Comment by sha-265** [comment]
OK, it's indeed releated to #51. I'm using Pi-hole that blocks freegeoip.net:
![image](https://user-images.githubusercontent.com/4103710/31241001-237de29c-aa0b-11e7-8ffb-8f73385cc72b.png)

Maybe adding the option to add location manually will be a good idea.

**Comment by Tyrrrz** [comment]
You mean something like [this](https://github.com/Tyrrrz/LightBulb/wiki/Manual-geolocation)?

**Comment by sha-265** [comment]
Yes :)
So maybe only adding a GUI to set location manually.

**Comment by Tyrrrz** [comment]
I'd love to do that but I don't really have the time+motivation to work on LightBulb as much anymore. 🙁

**Comment by sha-265** [comment]
I'm sorry to hear that :(

**Comment by Tyrrrz** [comment]
Please check if solution in #58 applies to your issue
