### ISSUE TITLE
No adjustment of color temperature if using USB 3.0 DisplayLink dock

### ISSUE THREAD

**Issue by dirks** [Tyrrrz/LightBulb#53]
Hi and thanks for your software.

LightBulb does not adjust color temperature of an external screen if it is connected via a [Dell D3100 USB 3.0 dock](http://www.dell.com/en-us/work/shop/accessories/apd/r6wd9) to a laptop. To be more precise
 - laptop connected via USB 3.0 to D3100
 - external screen connected via display port  to D3100
- color temperature of laptop screen is updated
- color temperature of external screen does not change

If the external screen is connected directly to the laptop's display port socket LightBulb works as expected. Please let me know if you need any additional info.

**Comment by mirh** [comment]
Can you check the tips in [here](https://superuser.com/questions/257606/is-there-a-work-around-to-configure-brightness-or-color-on-a-displaylink-monitor)?

**Comment by Tyrrrz** [comment]
Looks like there's more information [here](https://www.displaylink.org/forum/showthread.php?p=82958#post82958).
Closing this for now due to inactivity.
