### ISSUE TITLE
"Pause when fullscreen" occasionally switches itself off without user interaction

### ISSUE THREAD

**Issue by diamondavocado** [Tyrrrz/LightBulb#56]
As per the title.  I've noticed "Pause when fullscreen" sometimes sets itself back to being disabled without any interaction at all from me. It should be permanently set but sometimes when playing a game, I'll notice the colour temp is still low and this is why.

I'll try to gather more data on when this occurs.

On Windows 7 x64.

**Comment by Tyrrrz** [comment]
Which version are you using?

**Comment by diamondavocado** [comment]
Sorry; 1.6.3.3. I can try the latest if you want.

**Comment by Tyrrrz** [comment]
yes please try the new version

**Comment by Tyrrrz** [comment]
Hey @diamondavocado, did you get to check the new version?
