### ISSUE TITLE
Connects to internet at startup but I've disabled GEO and updates.

### ISSUE THREAD

**Issue by forkoz** [Tyrrrz/LightBulb#57]
Why? What else is being checked?

**Comment by Tyrrrz** [comment]
It checks for a new version on github

**Comment by Tyrrrz** [comment]
Or did you disable that in config?

**Comment by forkoz** [comment]
yes, disabled update checking. disabled geo checking. I manually set my location as well but stopped using it when the screen would dim at 6pm.

**Comment by Tyrrrz** [comment]
It might be pulling the image for your flag if you still have geolocation cached.

**Comment by forkoz** [comment]
That seems to make sense. I blocked via firewall and get no flag. Maybe should only pull it once if geolcation is fixed vs repeatedly downloading an image every run.

**Comment by Tyrrrz** [comment]
There's not much gain in doing that, the image is like 16x16 png.
