### ISSUE TITLE
Sunset time doesn't match

### ISSUE THREAD

**Issue by Moongose83** [Tyrrrz/LightBulb#58]
Hello, I've noticed that LightBulb sunset time doesn't match the real one. According to `https://www.timeanddate.com/astronomy/czech-republic/plzen` sunset time today in my place is 18:11. I have internet sync turned on in LB, it says that today the sunset is at 16:30 and therefore has already started with lowering the temperature. I have version 1.6.3.4 and I'm not sure how long this doesn't work, but I'm sure it did. Is there anything I could try? TIA.

**Comment by Tyrrrz** [comment]
Does the time actually change with internet sync or does it just retain the manual values?

**Comment by Tyrrrz** [comment]
Is it related to #51 #52?

**Comment by Moongose83** [comment]
> Does the time actually change with internet sync or does it just retain the manual values?
No, it retains the manual values.
Prolly #52.

**Comment by Tyrrrz** [comment]
Make sure the geolocation domain is not blocked by anything.

**Comment by Moongose83** [comment]
Well, it sets the place right. It just doesn't fetch the sunset/sunrise time. I've checked firewall and I don't know what else could it be blocked by.

**Comment by Tyrrrz** [comment]
Can you open `https://api.sunrise-sunset.org/json?lat=YOUR_LAT&lng=YOUR_LNG` in browser, replacing your latitude and longitude which you can see in LightBulb

**Comment by aneyeforsecrets** [comment]
I seem to have encountered the same bug. I've changed the coordinates in the config file, but it still doesn't pull the appropriate sunset/sunrise times. I can reach the API just fine.

`{"results":{"sunrise":"5:57:11 AM","sunset":"3:58:06 PM","solar_noon":"10:57:39 AM","day_length":"10:00:55","civil_twilight_begin":"5:24:51 AM","civil_twilight_end":"4:30:27 PM","nautical_twilight_begin":"4:48:11 AM","nautical_twilight_end":"5:07:06 PM","astronomical_twilight_begin":"4:12:07 AM","astronomical_twilight_end":"5:43:11 PM"},"status":"OK"}`

**Comment by Tyrrrz** [comment]
>I've changed the coordinates in the config file

Did it resolve time fine before you changed the coordinates manually?

**Comment by aneyeforsecrets** [comment]
I couldn't tell, because either the time or the location was very wrong. 
I noticed it when it was dark outside and the screen was still at 5000K 
(instead of the 3300K it was supposed to be at)

------ Originalnachricht ------
Von: "Alexey Golub" <notifications@github.com>
An: "Tyrrrz/LightBulb" <LightBulb@noreply.github.com>
Cc: "Birdface" <me@dennis-irrgang.com>; "Comment" 
<comment@noreply.github.com>
Gesendet: 31.10.2017 10:49:56
Betreff: Re: [Tyrrrz/LightBulb] Sunset time doesn't match (#58)

**Comment by Tyrrrz** [comment]
I still couldn't replicate the issue but I think I have a clue. The API response you posted is in local time (local to those coordinates) while what you see in LightBulb is in your computer's time zone. Could it be the issue you're having?

**Comment by zmni** [comment]
According to this: https://sunrise-sunset.org/api, API response is always in UTC. you need to convert it to your local time in UTC.

I think there is some kind of time conversion bug in LB, my API response and LB also doesn't match.

LB screenshot:
![lb](https://user-images.githubusercontent.com/841523/33887803-9f748002-df7d-11e7-87f6-50eedb4c3bff.jpg)

My coordinates API response:
```
{
  "results": {
    "sunrise": "10:14:59 PM",
    "sunset": "10:49:10 AM",
    "solar_noon": "4:32:05 AM",
    "day_length": "12:34:11",
    "civil_twilight_begin": "9:52:16 PM",
    "civil_twilight_end": "11:11:53 AM",
    "nautical_twilight_begin": "9:25:32 PM",
    "nautical_twilight_end": "11:38:37 AM",
    "astronomical_twilight_begin": "8:58:27 PM",
    "astronomical_twilight_end": "12:05:42 PM"
  },
  "status": "OK"
}
```

If I convert sunrise/sunset to my time (UTC+7), sunrise: 5:14:59 AM, sunset: 5:49:10 PM, result is correct. But LB show wrong value: sunrise: 7:20, sunset: 16:30.

**Comment by Tyrrrz** [comment]
Try adding `formatted=0` to your query

**Comment by Tyrrrz** [comment]
Also, are your timezone settings configured correctly on your PC?

**Comment by Tyrrrz** [comment]
Simply injecting your coordinates doesn't replicate the issue. Is it possible for you to debug it using source code?

**Comment by zmni** [comment]
Yes, timezone is correct, OS language, date, time, number & location configured to my region format.

**Comment by zmni** [comment]
Sorry, I don't have VS, can't help debug.

It looks like LB does not update its sunrise & sunset configuration value at all, its remains the same as mentioned in this file [FileSettingsService.cs#L31](https://github.com/Tyrrrz/LightBulb/blob/master/LightBulb.Impl/Services/FileSettingsService.cs#L31). I tried redo everything but still doesn't work. Here is the [Configuration.dat](https://github.com/Tyrrrz/LightBulb/files/1554891/Configuration.zip) file I'm using.

**Comment by Tyrrrz** [comment]
I might've found a possible bug. Can you try this build?

https://ci.appveyor.com/api/buildjobs/f12witib2tndkbsw/artifacts/Deploy%2FInstaller%2Fbin%2FLightBulb-Installer.exe

**Comment by zmni** [comment]
It's working now. The time is updated as it should be.

![lb 58](https://user-images.githubusercontent.com/841523/33935933-426db4ba-e030-11e7-9a72-6ea68509ad9b.jpg)

**Comment by Tyrrrz** [comment]
Yay!
