### ISSUE TITLE
Add manual lat/lon selectors in GUI

### ISSUE THREAD

**Issue by Nightfirecat** [Tyrrrz/LightBulb#59]
For computers that are on VPN networks or otherwise private networks, the automatically detected latitude/longitude may not be accurate. It would be useful in this case to allow users to set this value manually.

**Comment by mirh** [comment]
Aka allow manual location.

**Comment by Tyrrrz** [comment]
Please use this as a workaround - https://github.com/Tyrrrz/LightBulb/wiki/Manual-geolocation

**Comment by Disaer** [comment]
I've set my geolocation perfectly like:
  "GeoInfo": {
    "Country": "Belarus",
    "CountryCode": "BY",
    "City": Minsk,
    "Latitude": 53.8821,
    "Longitude": 27.44265
  },
But LightBulb resets it to:
  "GeoInfo": {
    "Country": "Belarus",
    "CountryCode": "BY",
    "City": null,
    "Latitude": 53.0,
    "Longitude": 28.0
  },
IsGeoInfoLocked already set to true.
UPD: The fourth time I did it! To force LightBulb not to reset settings, I was forced to leave the City field null.

**Comment by Disaer** [comment]
LightBulb again resets my location while IsGeoInfoLocked set to true.

**Comment by JJRcop** [comment]
@Disaer I have made sure to close LightBulb before messing with the configuration settings, as lightbulb will overwrite them when closed.
