### ISSUE TITLE
Hovering on tray icon produces custom label in wrong location

### ISSUE THREAD

**Issue by TETYYS** [Tyrrrz/LightBulb#6]
As seen in the screenshot: 
![fsnhj7z 1](https://cloud.githubusercontent.com/assets/3091645/22087873/349e9308-dde9-11e6-8dd7-9990a4be5a06.png)

Why does it produce a custom label anyways?

**Comment by Tyrrrz** [comment]
Fixed already, not yet in a release

**Comment by Tyrrrz** [comment]
> Why does it produce a custom label anyways?

Welcome to WPF, everything is custom here
