### ISSUE TITLE
CPU time

### ISSUE THREAD

**Issue by polyvertex** [Tyrrrz/LightBulb#60]
I found LightBulb to be a nice, user-friendly and working alternative to f.lux however I noticed it just keeps on consuming CPU time in an unreasonable way. This is fine I guess for desktop setups but it makes of your app a battery drainer on laptops.

Do you think there is a way it could be optimized?

I tried tweaking the *Gamma polling* and *Pause when fullscreen* settings but did not observe any change.

**Comment by Tyrrrz** [comment]
This is unusual, what CPU usage are you seeing?
![2017-10-27 14_01_39-task manager](https://user-images.githubusercontent.com/1935960/32101086-6b4b689a-bb1f-11e7-9865-74ab17757ccb.png)

**Comment by polyvertex** [comment]
> This is unusual [...]

It does not seem to be. I get a bit more than 1% on a small laptop. I am just surprised that, perhaps *Gamma polling* put aside, the application actually needs to consume that much CPU cycles so I was wondering if there was a way to optimize this.

**Comment by Tyrrrz** [comment]
Gamma polling isn't really a CPU intensive operation, the biggest performance bottleneck is the micro-freeze that occurs when GPU switches gamma ramps. Other than that, there are some recurring tasks which aren't frequent enough to consume any CPU. There's also an operation that executes every time a foreground window changes or re-positions - which is probably the reason for your 1% CPU usage. Technically it can be optimized by turning it off when the "pause when fullscreen" option is off, but I decided not to do it to avoid extra branching and points of failure, also considering that the CPU usage in that case is still very low.

**Comment by Tyrrrz** [comment]
What are your laptop specs?

**Comment by polyvertex** [comment]
Well I would understand you do not especially want to dig into it and I will not insist as this kind of issues might be spare-time eaters. LightBulb will not warm up the CPU if that is what your answer implies, however be aware that it is by an order of magnitude a bigger CPU-cycles consumer than some way-heavier apps I just leave running on the same machine without interacting with them like Chrome's main process and even the Visual Studio IDE (devenv.exe) for example.

**Comment by mirh** [comment]
Mhh, logging with procexp indeed reveals the program never really sleep. 
With a 0.3% usage of a C2D cpu. On more beefy machines I guess that becomes basically nothing, but still. 
And I can see how it could be even 10 times higher on some shittier low-end laptop. 

And I get that even with no movement going on on the screen whatsoever. 
I'm not sure how often and heavily the program should be supposed to check gamma, but flux seemingly manages to do everything right with maximum 0.03% cpu usage in the same conditions.

**Comment by forkoz** [comment]
I never noticed the hit but I also turned gamma polling off and nothing happened.

**Comment by Tyrrrz** [comment]
So `WindowsWindowService` is not the culprit, after all. Removing the event handlers doesn't affect CPU usage.

I profiled LightBulb for 15 minutes, here are the top CPU usages while idle. It appears that idle usage is almost solely generated by WPF's `Application.Run`.
![2017-11-28 22_23_34-lightbulb debugging - microsoft visual studio](https://user-images.githubusercontent.com/1935960/33342484-ec1d29c0-d48a-11e7-8c9a-1880d9a760d5.png)

**Comment by dzmitry-lahoda** [comment]
I see CPU is to high for me. LB is in tray. Not open. 

![image](https://user-images.githubusercontent.com/757125/88151756-c16bde80-cc0b-11ea-9478-81df742a4aec.png)

Attached settings and PC info.

[Settings.zip](https://github.com/Tyrrrz/LightBulb/files/4958699/Settings.zip)

[LAHODA-PC.zip](https://github.com/Tyrrrz/LightBulb/files/4958702/LAHODA-PC.zip)

Anyway, I consider CPU consumption to high for such a program and deleting it. I believe people will follow the way.

#battery #cpu #consumption #energy #waste

**Comment by hotellinawebmaster** [comment]
Hi,

I also noticed a high CPU time on my laptop.
Sometimes even up to 3%.

Best,

Aldo

**Comment by Tyrrrz** [comment]
@hotellinawebmaster yeah I started seeing those too. Probably the changes in the latest versions that added additional checks to prevent gamma invalidation have brought it up. Created #182 to track it.
