### ISSUE TITLE
Manual location has been overwritten

### ISSUE THREAD

**Issue by liangshengzero** [Tyrrrz/LightBulb#64]
I am using a proxy. it makes Lightbulb getting a worse latitude/longitude with me.

I had a try with the link:https://github.com/Tyrrrz/LightBulb/wiki/Manual-geolocation

but I am not found the ShouldUpdateGeoInfo property, when I onpen the LIightbulb, it will  automatically detected latitude/longitude, and overwrite configuration file. 

I try to write an option that  ShouldUpdateGeoInfo，but he does not work.

What should I do to solve this problem?

**Comment by Tyrrrz** [comment]
Current released version has an issue related to manually-edited configuration files, can you try this CI build and check if you still have the same issue? https://ci.appveyor.com/api/buildjobs/urmwy65fwf956uhv/artifacts/Deploy%2FInstaller%2Fbin%2FLightBulb-Installer.exe

**Comment by liangshengzero** [comment]
The problem still exists

**Comment by Tyrrrz** [comment]
It seems that the setting name was updated at some point but the wiki page wasn't. The correct name is `IsGeoInfoLocked` and not `ShouldUpdateGeoInfo`. I'll update the wiki accordingly, sorry for that.
