### ISSUE TITLE
Disable to 'daytime' setting

### ISSUE THREAD

**Issue by martssum** [Tyrrrz/LightBulb#66]
Would be nice to have an option so that when you choose to disable lightbulb, it reverts to your daytime/brightest setting and doesn't disable it entirely.

**Comment by JohnnyP78** [comment]
Yup mode setting with 3 different running modes:
- Auto: The mode that Lightbulb uses now as current version, it runs through night and day automatically
- Day: It stays permanently on the day value all time/any time (static)
- Night: It stays permanently on the night value all time/any time (static)

I believe the current disable feature works as it is supposed to.
