### ISSUE TITLE
Alt-Tab acts as FullScreen with Autohide Taskbar

### ISSUE THREAD

**Issue by Elitetrop** [Tyrrrz/LightBulb#67]
Whenever alt-tab is activated, lights get returned to normal if "fullscreen detection" is activated in Lightbulb. Lights return to redshifted when alt-tab is released again. I tested it on my Win10 LTSB and it does not happen if autohide taskbar is disabled.

**Comment by TheChiefMeat** [comment]
This also happens with UAC prompt windows.

**Comment by TheChiefMeat** [comment]
Possibly, I just found it incredibly frustrating and sometimes it would get stuck at the daytime setting and would suddenly jump back down, I ended up uninstalling for now until it's fixed.

**Comment by Tyrrrz** [comment]
Couldn't replicate it with UAC prompt. Fixed for alt+tab.
