### ISSUE TITLE
Unable to open Configure with: two monitors activated and Dual Monitor Tools app activated

### ISSUE THREAD

**Issue by Elitetrop** [Tyrrrz/LightBulb#68]
Whenenver I have my TV setup with HDMI on my Laptop with the "Extend"-option enabled (so both screens are activated), I can no longer access the Configure-option from right-clicking the tray bar icon. I click Configure, and my mouse instead just jumps to the lower right part of the screen, while the "Configure,Disable,Disable for...,etc" menu is still open. I can access Configure again if I disable one of my screens or close down Dual Monitor Tools. No other programs have given issue with that app before as far I have experienced.

**Comment by Tyrrrz** [comment]
Have you tried double-clicking the tray icon?

**Comment by Elitetrop** [comment]
Double-clicking the tray icon does indeed open up the configuration menu.

**Comment by Tyrrrz** [comment]
Going to close this because this is a rare issue with a workaround, and also because it's most likely fixed by recent changes.
