### ISSUE TITLE
Internet Synchronization picking up IP location could be an unwanted feature

### ISSUE THREAD

**Issue by kamenoccc** [Tyrrrz/LightBulb#69]
For users using a VPN, this can bring times not corresponding to their location. Enabling Internet Synchronization automatically picks up the current IP and syncs based on it. 

How about allowing sync to happen with a manually chosen country?

**Comment by Tyrrrz** [comment]
Is this relevant?
https://github.com/Tyrrrz/LightBulb/wiki/Manual-geolocation

**Comment by kamenoccc** [comment]
It's relevant, yeah. But if set manually, are sunrise/sunset times adjusted through the year? 
I thought Internet synchronization did that, so it'd be usefull to have sync for a manually set location, no?

**Comment by Tyrrrz** [comment]
Yes

**Comment by Tyrrrz** [comment]
Have you managed to get it working the way you wanted?
