### ISSUE TITLE
LightBulb overlay won't appear on some games with full screen mode 

### ISSUE THREAD

**Issue by sha-265** [Tyrrrz/LightBulb#71]
I noticed when playing some games in full screen mode, the LightBulb's overlay not appear, and the colors are blue as default.

Any option to fix that?

Thanks.

**Comment by mirh** [comment]
Play in borderless fullscreen.

**Comment by sha-265** [comment]
@mirh what do you mean by "borderless fullscreen"? There is no border when I'm playing on full screen mode.

**Comment by polyvertex** [comment]
@sha-265 I think @mirh is referring to one of these 3 display modes usually offered as an option by fairly recent games: "windowed", "full screen", and "borderless windowed"

**Comment by Tyrrrz** [comment]
Lightbulb doesn't have an overlay and it doesn't matter whether the game is running exclusive fullscreen or not. Sometimes there are issues though, when both the game and lightbulb are fighting over gamma control.

**Comment by mirh** [comment]
Then I guess it's the usual "games force their own gamma" issue IMO.
