### ISSUE TITLE
About resource usage

### ISSUE THREAD

**Issue by LakeishaKowalczyk** [Tyrrrz/LightBulb#72]
Process Hacker

![default](https://user-images.githubusercontent.com/14090545/37304904-e060f28a-266d-11e8-835d-898cdaa6d8f4.png)

**Comment by mirh** [comment]
Follows #60 - also.. Indeed 70MB feels pretty fatty.

**Comment by LakeishaKowalczyk** [comment]
Thanks, by the way, what is this program, looks cool
![33342484-ec1d29c0-d48a-11e7-8c9a-1880d9a760d5](https://user-images.githubusercontent.com/14090545/37305552-c4f78b6a-266f-11e8-9892-fb508b002d33.png)

**Comment by mirh** [comment]
Buttons design seems Visual Studio related. 
Prolly its profiler.

**Comment by Tyrrrz** [comment]
Yeah, it's VS profiler. Unfortunately, I can't influence resource usage.
