### ISSUE TITLE
Gamma changes when resuming from locked session

### ISSUE THREAD

**Issue by nehz** [Tyrrrz/LightBulb#76]
System: Window 7
Monitors: Multi (2)
Graphics Card: NVidia 760 GTX

On my setup, when I login from a locked session the gamma resets to daytime levels, and only if gamma polling is enabled does it change back to night mode gamma after X seconds.

I've managed to fix it with this hack, but have not really investigated why this occurs:

```
SystemEvents.SessionSwitch += SystemEvents_SessionSwitch;

...

private async void SystemEvents_SessionSwitch(object sender, SessionSwitchEventArgs e)
{
    await Task.Delay(300);
    for (var i = 0; i < 100; i++)
    {
        UpdateGamma();
        await Task.Delay(1);
    }            
}
```

**Comment by Tyrrrz** [comment]
Gamma polling is basically a workaround for issues like this. As you noticed yourself, it's possible to implement a delay to fix it on your end, but it's very likely that it may not help users with other setups, unfortunately.
