### ISSUE TITLE
LightBulb turns off every time USB device is plugged out/in

### ISSUE THREAD

**Issue by LittleEndu** [Tyrrrz/LightBulb#77]
Started happening after I updated Windows

**Comment by wdbw** [comment]
Probably related: https://forum.justgetflux.com/topic/6389/windows-10-april-2018-update-issues

**Comment by Tyrrrz** [comment]
Does it still happen? Is the gamma polling enabled?

**Comment by LittleEndu** [comment]
Doesn't seem to happen right now but it did happen few days ago, I think. Gamma polling is enabled, I assume this is what fixes it after few seconds.

**Comment by Tyrrrz** [comment]
Yes, gamma polling was added exactly for this type of cases.
