### ISSUE TITLE
Lightbulb thinks it's always night when close to the arctic circle.

### ISSUE THREAD

**Issue by LimEJET** [Tyrrrz/LightBulb#78]
I live at 65&deg; lat, which means that sunset/sunrise times go all weird during summer and winter. Lightbulb seems to freak out over this, as it's started believing that it's always night-time. Without looking into the source code, I'd wager it makes at least one out of the two following assumptions:

1. The sun goes down and up *every day*, or
2. The sun goes up *the day after* it goes down.

Sunrise time at my location today is 01:02. Sunset time is 00:03. These will approach eachother until around the 22nd of June, where they will converge. 

The first issue I have is that I can't set those times using the timer sliders, as they bottom out at 04:00 and 22:00. The second issue is that geolocation sets the wrong times, and what Lightbulb does with that information.

Using geolocation currently sets both sunrise and sunset time to 51 seconds after midnight. Either only the first of these is actually checked, or the application only checks for a sunrise after a sunset has occurred *and* the time has passed midnight.

My belief is strengthened by the fact that Lightbulb will not dim the colors when doing a 24-hour preview. If I start out at my night-setting and do a preview, the light fades up to day at "midnight" and stays that way until I close down a fullscreen application (which is, I assume, when the checks happen).

**Comment by Tyrrrz** [comment]
Hello.
Thanks for a very thorough bug report!
You are right, LightBulb was design with a naive assumption that both sunrise and sunset happen during the same day. This is also related to #20.

**Comment by Tyrrrz** [comment]
Hi @LimEJET 
Can you try a CI build that's supposed to fix this issue?
https://ci.appveyor.com/project/Tyrrrz/lightbulb/build/31/artifacts

**Comment by LimEJET** [comment]
The preview certainly seems to behave properly. I'll test it out for a few days and get back to you.

**Comment by LimEJET** [comment]
It has worked well so far! Now we'll have to wait and see if it freaks out when the sun disappears for a few days 😃

**Comment by Tyrrrz** [comment]
:fearful: :fearful: :fearful:
