### ISSUE TITLE
FreeGeoIP is deprecated

### ISSUE THREAD

**Issue by Tyrrrz** [Tyrrrz/LightBulb#79]
Need to find a new IP geolocation provider.

**Comment by kocane** [comment]
@Tyrrrz  This one is also deprecated now lol

https://github.com/nekudocom/shiny_geoip#readme

pls

**Comment by Tyrrrz** [comment]
Shaking my head...

**Comment by kocane** [comment]
Sorry

**Comment by Tyrrrz** [comment]
Let's see how long before this one also stops working. Ideally, in next versions there will be an ability to manually choose location with geo-ip as backup.
