### ISSUE TITLE
internal error cannot access 64 bit registry keys

### ISSUE THREAD

**Issue by jcmwmatt** [Tyrrrz/LightBulb#8]
Operating system > W10-32bit.
Refer these screenshots.
Thank you.

![lightbulb1](https://cloud.githubusercontent.com/assets/25423090/22409069/2d21f56e-e6bf-11e6-8959-40e038bfc76f.gif)
![lightbulb2](https://cloud.githubusercontent.com/assets/25423090/22409070/2d2e5a34-e6bf-11e6-87d4-610ae188a84e.gif)

**Comment by Tyrrrz** [comment]
I'm assuming you're running a 32bit OS, correct?

**Comment by Tyrrrz** [comment]
Looks like InnoSetup doesn't ignore HLKM64 registry entries when running on a 32-bit OS as I expected. Sorry about that. Will fix soon.

**Comment by Tyrrrz** [comment]
This fix is now included in the latest release, enjoy
