### ISSUE TITLE
Tray menu button 'Configure' doesn't do anything

### ISSUE THREAD

**Issue by smaragdus** [Tyrrrz/LightBulb#81]
'Configure' command from tray- right-click on tray icon- 'Configure', does not work. However single-click on tray icon opens configuration.

Off-topic
I preferred double click to single click since double click reduces the chances for misclick.

**Comment by Tyrrrz** [comment]
Not sure why I still haven't removed that button. :pensive:
Thanks for the report.

**Comment by smaragdus** [comment]
> Not sure why I still haven't removed that button. pensive

I see that you intend to dumb down your program, so I decided to switch to [another one](https://github.com/ltGuillaume/Redshift-Tray). I won't be testing and using  **LightBulb** any more,

Good luck

**Comment by Kravimir** [comment]
I'd like to suggest that having multiple navigation paths is often a good thing. Please leave the "configure" item in the context menu and make it work as expected.
