### ISSUE TITLE
Pause on Fullscreen option doesn't work in Firefox

### ISSUE THREAD

**Issue by LimEJET** [Tyrrrz/LightBulb#83]
This is a weird one.

I encountered this issue on version 1.6.3.6, and it seems to persist in 1.6.4. When something in Firefox (61.0.2, x64) goes full screen (including the application window), LightBulb simply "pulses" the colour and then goes back to filtering. The same thing happens again when exiting fullscreen mode.

[Here's a video that demonstrates the effect.](https://gfycat.com/HeartyBoilingChick) The effect is a bit more pronounced because of the camera blooming, but it's still visible, particularly on the white parts below the video when exiting full screen. My screen capture software adds a full screen mask when capturing so I couldn't capture it natively.

I have tried this in Edge, Chromium, and Brave and I've not been able to reproduce it there. It's probably a change in Firefox that has caused this.

**Comment by Dainius14** [comment]
FF 70.0.01, current LightBulb build, seems to not be an issue anymore. Can probably close.

**Comment by Tyrrrz** [comment]
Ok. closing for now.
