### ISSUE TITLE
Sunset/sunrise time offset

### ISSUE THREAD

**Issue by n9r** [Tyrrrz/LightBulb#85]
[suggestion] Add or substract value for sunset and sunrise time. Useful to make it quicker when they are based on geolocation.

**Comment by Tyrrrz** [comment]
Unfortunately, I don't see this being implemented as it adds quite a lot of complexity to an already pretty complex program for comparably small benefit.

In 2.0 you will be able to set location from UI. This lets you configure your location to some other city/country and use its sunrise/sunset times instead, which you can use to achieve something similar to what you want. Alternatively, you can manually set sunrise/sunset to fine-tune it to your schedule.
