### ISSUE TITLE
Dual monitors through docks not working

### ISSUE THREAD

**Issue by pemguin005** [Tyrrrz/LightBulb#86]
Great App by the way

Fresh install of v1.6.4.0

When connecting to a second monitor directly or through a basic passthrough video adapter dongle, LightBulb works perfectly.

When passing through a docking station, port replicator or mini dock (like a Targus VersaLink for example), LightBulb stops functioning on both monitors. There is no error, or crash, the color adjusting effect stops. Adjusting toggles and settings has no effect either. Closing LightBulb and reopening once the 2nd monitor is connect also makes no change.

I've tested this on two separate docks, both are "DisplayLink - Plug and Display" devices which may be relevant.

**Comment by Tyrrrz** [comment]
Perhaps the same as #53
I wonder what's causing this

**Comment by pemguin005** [comment]
I did another test today using a VGA to DP++ dongle adapter to my 2nd screen and immediately LightBulb starting working properly again. I keeping suspecting it's just these DisplayLink labeled devices that aren't working correctly with it. If I find anything useful I'll try to share. Let me know if you want me to test anything. I have access to a lot of different monitors, port types, adapters and docks. If any can help out, just let me know. Until then I'll keep telling myself I'll learn C and maybe I can be more useful in about a year. :\

**Comment by Tyrrrz** [comment]
Going to merge this with #53 as it seems to be the same problem. Please check [latest master build](https://github.com/Tyrrrz/LightBulb/suites/302403101/artifacts/277186) to see if it fixes this issue.

**Comment by vratojr** [comment]
I can say that the problem is still present.
I'm not sure the problem is the dock in itself.
I've been using the docking station "DisplayLink" with linux and redhisft and the monitors where handled correctly in their gamma correction. The same dock with windows and light bulb, fails :(

**Comment by Tyrrrz** [comment]
@vratojr did you look at the troubleshooting page?
https://github.com/Tyrrrz/LightBulb/wiki/Troubleshooting#gamma-is-not-changing

**Comment by vratojr** [comment]
Nope, sorry! :)
