### ISSUE TITLE
Geolocation couldn't identify my city

### ISSUE THREAD

**Issue by beerisgood** [Tyrrrz/LightBulb#9]
In v 1.6.0 i get this:
![location](https://cloud.githubusercontent.com/assets/9625159/22590606/43b997ba-ea10-11e6-8444-672801e405fa.png)

Germany is right, but the exact is unknown. Why i just cant paste my zipcode and finish?

**Comment by Tyrrrz** [comment]
It just means it couldn't accurately determine your city, based on coordinates. Generally, identifying country is good enough for accurate sunrise/sunset times.

Open a new browser tab and type "sunrise time" (or "sunset time"). If it shows the same time, you have nothing to worry about.

**Comment by beerisgood** [comment]
Alright.
Thanks!

Can be closed then.
