### ISSUE TITLE
Allow gamma control down to 1000K?

### ISSUE THREAD

**Issue by lrq3000** [Tyrrrz/LightBulb#90]
For circadian rhythm disorders, removing all blue and even yellow light might be necessary to avoid melatonin suppression.

Currently, the app (even by configuring the config file manually in AppData) can only go down to 2100K, which is still yellowish with some blue lights.

Would it be possible to allow the temperature to be turned down to 1000K or even lower? The goal being to have a mostly reddish screen.

**Comment by Tyrrrz** [comment]
When you try manually changing the temperature to 1000k, does it reset to 2100k?

**Comment by lrq3000** [comment]
Yes, it resets to 2100k at next application start.

Le sam. 17 nov. 2018 à 20:53, Alexey Golub <notifications@github.com> a
écrit :

**Comment by lrq3000** [comment]
I am on Windows 7, so maybe this is a limitation of the OS?

**Comment by Tyrrrz** [comment]
That or perhaps a limitation of the GPU

**Comment by mirh** [comment]
AMD+W7 can go at least as down as 1300K here.
