### ISSUE TITLE
Temperature change is too noticeable 

### ISSUE THREAD

**Issue by diamondavocado** [Tyrrrz/LightBulb#93]
Related to my previous issue #54 - I'm still noticing temperature changes even though I changed the epsilon value to 1 and the adjutment time to 00:00:01 (1 second) in the configuration file.

I think the configuration settings are not being stored/saved correctly or just not being respected properly.

Either that or I simply don't understand how the adjustment works. Maybe someone can help me understand it?

Let's take the following example:
    Sunset time: 20:00
    Transition duration: 2:00:00
    Day temp: 6000K
    Night temp: 2000K

Given the above, I would expect the temp to start reducing at 18:00. I would expect it to reduce by (6000-2000) / (2 hours in seconds) K per second. That works out as 4000K / 7200 seconds which is 0.555...K per second. 

Is this not correct?

**Comment by Tyrrrz** [comment]
Temperature change algorithm is here: https://github.com/Tyrrrz/LightBulb/blob/c5f133715b79f35404ba6a5b85a6b3a031ba899f/LightBulb/Services/TemperatureService.cs#L203
It has changed quite a bit over time. The way it works now is that the transition starts after sunset and lasts the transition duration. It's also not linear but resembles a cos function.
As for your first question, you mentioned your transition duration is 1 second, which means that the whole transition will be near instant, hence why it's not smooth.

**Comment by diamondavocado** [comment]
Thanks for the explanation.

Could you please recommend the settings I should be using if I want to achieve a temperature change which is as smooth as possible (i.e. under 5K per second) from 6000K to 2000K over a period of, say, 1 hour?

Also, would you consider adding features such as:

* Being able to control when the temperature change starts/finishes (e.g. if your transition duration is set to 1 hour, choose whether the change begins 1 hour *before* sunset and finishes at sunset time; begins 30 minutes before sunset time and ends 30 minutes after sunset time; or begins at sunset time and ends at 1 hour after sunset time)?

* Being able to control the temperature change function e.g. from cos curve to linear change?

I can add these as enhancement requests if you think they're reasonable?

Thanks

**Comment by Tyrrrz** [comment]
Generally speaking, the longer your transition duration is, the smoother it will be. Try setting it to 2 hours and check the results, it should be really smooth. You can always press the "play" button for a quick preview.

Regarding your suggestions -- it's really hard to add more variables to any (more or less complex) algorithm as it gets harder to test all the possible permutations and maintain it in the long run.

Ultimately, I would want to have an algorithm which perfectly represents ambient outdoor color temperature, which means it should model what happens to the light after the sun starts to set and before it actually sets.
