### ISSUE TITLE
Upgrade to .NET Core 3

### ISSUE THREAD

**Issue by rogersachan** [Tyrrrz/LightBulb#98]
.NET Core 3 has performance improvements that .NET Framework 4.8 will not be getting. Migration will also be necessary prior to .NET 5.

**Comment by rogersachan** [comment]
Documentation on how to port is available here: https://docs.microsoft.com/en-us/dotnet/core/porting/wpf

**Comment by Tyrrrz** [comment]
I know. There's no point doing it before it's released.
